dafny-lang/dafny

Source/Dafny/Kremlin.cs
@Chris-Hawblitzel as per your email, thanks!
=> Update Kremlin extraction for schema 24

Source/Dafny/Resolver.cs, Test/dafny4/git-issue182.dfy, Test/dafny4/git-issue182.dfy.expect
The only reason I didn't push this to master is that I am traveling and can't run the full test suite.
I'll do it when I get back, or if someone can confirm that this fix doesn't break anything, feel free to merge.
=> Fix #182 by adding a suitable null check

Source/Dafny/Resolver.cs
=> Allow type variables in tuples

README.md, Source/Dafny/Cloner.cs, Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/SubsetTypes.dfy.expect, Test/dafny0/MiscTypeInferenceTests.dfy.expect, Test/dafny0/ModuleExport.dfy, Test/dafny0/ModuleExport.dfy.expect, Test/dafny0/Modules0.dfy.expect, Test/dafny0/ResolutionErrors.dfy.expect, Test/dafny0/SubsetTypes.dfy, Test/dafny0/SubsetTypes.dfy.expect, Test/dafny4/Regression12.dfy.expect, Test/dafny4/git-issue235.dfy, Test/dafny4/git-issue235.dfy.expect, Test/exports/DefaultExport.dfy.expect, Test/exports/ExportErrorLocations.dfy.expect
I had these 3 changes in the same branch, so they're apparently going into the same pull request. (Next time, I'll separate unrelated pull requests.)
=> improved subset type errors, export set name space, cloning bug fix

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Compiler.cs, Test/comp/CSharpStyling.dfy, Test/comp/CSharpStyling.dfy.expect, Test/comp/CSharpStyling2.cs, Test/comp/Extern.dfy, Test/comp/Extern.dfy.expect, Test/comp/Extern2.cs, Test/comp/Extern3.js, Test/comp/Extern4.go, Test/dafny0/Extern2.cs
Improved support for mixing Dafny and C#.
=> Csharp extern improvements

Source/Dafny/Resolver.cs, Test/dafny4/git-issue239.dfy, Test/dafny4/git-issue239.dfy.expect
=> Allow type variables in patterns

Source/Dafny/Translator.cs, Test/dafny4/git-issue245.dfy, Test/dafny4/git-issue245.dfy.expect
The extra merges just contain things that were already on master.
=> Git issue 245

Source/Dafny/RefinementTransformer.cs, Source/Dafny/Translator.cs
=> Make internal attribute more obscure

Source/Dafny/DafnyAst.cs
I don't understand how this could have worked before.
=> Fix bind bug

Source/Dafny/Dafny.atg, Source/Dafny/Parser.cs
I think this (`Dafny.atg`) is our last source file that had trailing white space.
=> Remove white space at end of lines

Source/DafnyDriver/DafnyDriver.cs, Test/git-issues/github-issue-305-a.dfy, Test/git-issues/github-issue-305-b.dfy, Test/git-issues/github-issue-305-c.dfy, Test/git-issues/github-issue-305-c.dfy.expect, Test/lit.site.cfg
This PR contains all commits of https://github.com/dafny-lang/dafny/pull/307, plus the requested changes:
* tests for all scenarios which had bugs at some point
* properly placed comments
=> v2: Take compile flag into consideration and return appropriate exit code

Source/Dafny/Translator.cs, Test/git-issues/git-issue-334.dfy, Test/git-issues/git-issue-334.dfy.expect
=> Note that seq-construction needs heap argument

Source/Dafny/Printer.cs, Test/dafny0/AutoContracts.dfy.expect, Test/dafny0/Bitvectors.dfy.expect, Test/dafny0/BitvectorsMore.dfy.expect, Test/dafny0/ModuleInsertion.dfy.expect, Test/dafny0/PrefixTypeSubst.dfy.expect, Test/dafny0/TypeConstraints.dfy.expect, Test/dafny0/TypeConversions.dfy.expect, Test/dafny0/TypeConversionsCompile.dfy.expect, Test/dafny2/CalcDefaultMainOperator.dfy.expect, Test/dafny4/git-issue228.dfy.expect
Minor change in /rprint output
=> Reduce spaces before printing "special witness" comment for /rprint

Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Printer.cs, Source/Dafny/Translator.cs, Test/dafny0/AutoContracts.dfy.expect, Test/dafny0/Bitvectors.dfy.expect, Test/dafny0/BitvectorsMore.dfy.expect, Test/dafny0/ModuleInsertion.dfy.expect, Test/dafny0/PrefixTypeSubst.dfy.expect, Test/dafny0/TypeConstraints.dfy.expect, Test/dafny0/TypeConversions.dfy.expect, Test/dafny0/TypeConversionsCompile.dfy.expect, Test/dafny2/CalcDefaultMainOperator.dfy.expect, Test/dafny4/git-issue228.dfy.expect
Use an existing helper routine to do some work. (I happened to use another Pull Request as the parent of this change.)
=> Use user defined type from top level decl

Source/Dafny/RefinementTransformer.cs, Test/git-issues/git-issue-332.dfy, Test/git-issues/git-issue-332.dfy.expect
=> Fix refinement checks for two-state predicates.

Docs/StyleGuide/Style-Guide.md
These changes were suggested in comments on https://github.com/dafny-lang/dafny/pull/304,
which was merged before the comments were acted on.
=> Roll in style-guide suggestions

Source/Dafny/Compiler-java.cs
The only effect of this change is to change the formatting of the Java code that is generated.
The `TargetWriter` class has functionality for brace matching and automatic indentation, and
it is used elsewhere. So, I changed the code generation for
* `Array<n>`,
* `ArrayInit<n>`,
* `Function<n>`, and
* `Tuple<n>`
to write using `TargetWriter`.
=> Use TargetWriter to format generated Java code

Docs/StyleGuide/Style-Guide.md
As discussed, add prescription to use newlines between functions, methods, etc. Also added ending each file with a newline since I couldn't find that elsewhere.
=> Add guidelines for newline use

Source/Dafny/Compiler-java.cs, Test/comp/NativeNumbers.dfy, Test/comp/NativeNumbers.dfy.expect
=> Java: Cast to byte or short after +, -

Docs/OnlineTutorial/guide.md
=> Improve online tutorial

Source/Dafny/Dafny.atg, Source/Dafny/Parser.cs, Test/exceptions/ParseErrors.dfy.expect
=> Change "semi expected" to "semicolon expected"

Source/Dafny/Compiler-Csharp.cs
There's overhead in Sequence.Create having to call the passed-in function for each element.  If we know the function is a lambda, we can instead put the body of the lambda in a loop that populates the sequence.
=> C#: Use explicit loop instead of Sequence.Create when possible

Source/Dafny/Translator.cs, Test/git-issues/git-issue-448.dfy, Test/git-issues/git-issue-448.dfy.expect
=> Check well-formedness of receiver in method calls

Test/allocated1/dafny0/Calculations.dfy, Test/allocated1/dafny0/Calculations.dfy.expect, Test/allocated1/dafny0/DirtyLoops.dfy, Test/allocated1/dafny0/LetExpr.dfy, Test/allocated1/dafny0/LetExpr.dfy.expect, Test/dafny0/Calculations.dfy, Test/dafny0/Calculations.dfy.expect, Test/dafny0/LetExpr.dfy, Test/dafny0/LetExpr.dfy.expect
These tests were performed, but the output of the tests was never inspected.
=> Include missing tests, remove /autoTriggers:0

Binaries/dafny, Binaries/dafny-server, buildspec.yml
Uses the bash builtin "type" command. (cc @lavaleri)
Resolves #449
=> Replace "which" utility in launch bash scripts

INSTALL.md
Matches command in buildspec.yml
=> Update INSTALL.ms to clone v2.4.2 of Boogie

Source/Dafny/Compiler-go.cs
This parameter was rendered unnecessary by a recent refactoring.
=> chore: Remove unused parameter

Binaries/DafnyPrelude.bpl, Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Translator.cs, Test/comp/Numbers.dfy, Test/comp/Numbers.dfy.expect
Fixes several problems with conversions between numeric types in compilation.
Fixes range-check problems with ORDINAL.
=> Fix number conversions

Test/dafny4/NumberRepresentations.dfy
Write more detailed proofs to guide the verifier.
Also, remove unnecessary semi-colons.
=> Stabilize number representations

Source/Dafny/DafnyAst.cs, Source/Dafny/Translator.cs, Test/git-issues/git-issue-600.dfy, Test/git-issues/git-issue-600.dfy.expect
=> fix: Fix incorrect optimization

README.md
Updates to the README.md file that generates the GitHub landing page for the dafny-lang site.
=> Cok readme

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-666.dfy, Test/git-issues/git-issue-666.dfy.expect
Fixes #666 
In the test file, I included some additional test that cause a different issue. An separate issue will be filed for them.
=> fix: Correct overly strong assertion

Source/Dafny/Translator.cs, Test/git-issues/git-issue-615.dfy, Test/git-issues/git-issue-615.dfy.expect
=> #615: fixed an erroneous use of null for a heap, instead of a reference to $OneHeap

Test/git-issues/git-issue-289.dfy, Test/git-issues/git-issue-289.dfy.expect, Test/git-issues/git-issue-289b.dfy
=> #289: Verified that this issue is already fixed. Added tests.

Test/git-issues/git-issue-616.dfy, Test/git-issues/git-issue-616.dfy.expect
=> #616: Verified problem fixed and tests added

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-374.dfy, Test/git-issues/git-issue-374.dfy.expect, Test/git-issues/git-issue-386.dfy, Test/git-issues/git-issue-386.dfy.expect
=> #374: guarded ghost check in constructor arguments and added tests

Test/git-issues/git-issue-612.dfy, Test/git-issues/git-issue-612.dfy.expect
Verifies that #612 stays fixed
=> #612: Added tests to verify an issue that has been fixed

Test/git-issues/git-issue-503.dfy, Test/git-issues/git-issue-503.dfy.expect
=> #503: tests added, already fixed, perhaps by issue #615

Test/git-issues/git-issue-504.dfy, Test/git-issues/git-issue-504.dfy.expect
=> #504: confirming fix, adding test cases

Test/git-issues/git-issue-227.dfy, Test/git-issues/git-issue-227.dfy.expect
Fixes #227. Behavior was already fixed. Test added to assure continued correct behavior.
=> #227: adding tests regarding type checking of calc statement

Test/git-issues/git-issue-286.dfy, Test/git-issues/git-issue-286.dfy.expect
=> #286: adding test cases to confirm pattern matching on literals

Source/Dafny/Compiler-java.cs, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-314.dfy, Test/git-issues/git-issue-314.dfy.expect, Test/git-issues/git-issue-701.dfy, Test/git-issues/git-issue-701.dfy.expect
Fixes #314. Similar fix to #701.
=> #314: fix to type inference for arrays

docs/_includes/Modules.md
Initial edit of the modules section to incorporate old edits. Not meant to be complete.
=> Documentation: modules

docs/_includes/Types.md
Initial edit of constructors section, to incorporate old edits. Not considered complete/final.
=> Documentation: constructors

docs/DafnyReferenceManual/DafnyRef.md, docs/_includes/Introduction.md, docs/_includes/UserGuide.md
full edit of Introduction; minor changes to opening material and user guide
=> Documentation: edits of Introduction

Util/interact.py
Some of our Dafny developers prefer to use their own non-Dafny-enlightened editors when writing Dafny code.  This script allows them to benefit from the proof caching done by the Dafny Server.  It also serves as some additional documentation of the Dafny Server's interface.
=> A Python script for interacting with the DafnyServer via a commandline

Source/Dafny/Translator.cs, Test/git-issues/git-issue-784.dfy, Test/git-issues/git-issue-784.dfy.expect
=> #784: Fixes crash because of a bad cast

Test/git-issues/git-issue-588.dfy, Test/git-issues/git-issue-588.dfy.expect
=> #588: Adding test case to confirm fix to Go compiler

Test/git-issues/git-issue-354.dfy, Test/git-issues/git-issue-354.dfy.expect
Fixes #354 
Fixed as a byproduct of other work in generic types.
=> #354: Adding test to confirm fix

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-267.dfy, Test/git-issues/git-issue-267.dfy.expect
=> #267: Raised recursion limit

Source/Dafny/Compiler-Csharp.cs
* better help message emitted at top of target file
* combine /nowarn's into one comma-delimited list
* only try to copy one of the 3 DLLs, do so only for executables, and generate a non-failing warning (instead of crashing with an exception) if that file is not found
=> Improve C# compilation

Source/version.cs, package.py
Change version number to 3.0.0.20820
Include System.Collections.Immutable.dll and System.Runtime.dll in distribution
=> Set up for v3.0.0 pre-release 1

Source/Dafny/Compiler.cs, Test/git-issues/git-issue-261.dfy, Test/git-issues/git-issue-261.dfy.expect
=> #261: Fixed a compiler bug in printing the type of a temporary

Source/Dafny/Resolver.cs
The messages are likely never used, but at least will not cause a crash.
Fixes #838.
=> #838: Correcting the absence of error messages

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-849.dfy, Test/git-issues/git-issue-849.dfy.expect, Test/git-issues/git-issue-849a.dfy, Test/git-issues/git-issue-849a.dfy.expect, docs/_includes/Types.md
=> #849: Corrects error message and documentation regarding datatype update syntax

Source/Dafny/RefinementTransformer.cs, Test/git-issues/git-issue-852.dfy, Test/git-issues/git-issue-852.dfy.expect
=> #852: Fixing a crash in refinement of newtype

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-816.dfy, Test/git-issues/git-issue-816.dfy.expect
Fixed as suggested in the issue. 
Fixes #816.
=> #816: Fix to bug with precondition label and reveal

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-854.dfy, Test/git-issues/git-issue-854.dfy.expect
=> #854: adjusting misleading error messages

Source/Dafny/Translator.cs, Test/git-issues/git-issue-505.dfy, Test/git-issues/git-issue-505.dfy.expect, Test/git-issues/git-issue-867.dfy, Test/git-issues/git-issue-867.dfy.expect
=> #867: fix: Also substitute in constraint-bounds of let expressions

Source/Dafny/Translator.cs, Test/git-issues/git-issue-897.dfy, Test/git-issues/git-issue-897.dfy.expect, Test/git-issues/git-issue-897a.dfy, Test/git-issues/git-issue-897a.dfy.expect, Test/git-issues/git-issue-897b.dfy, Test/git-issues/git-issue-897b.dfy.expect
=> #897: fix to crash because of bug in Substitute for ForallStmt

docs/KDESyntaxDefinition/dafny.xml, docs/_includes/Expressions.md, docs/_includes/Grammar.md, docs/_includes/Statements.md, docs/_includes/Topics.md, docs/_includes/Types.md
This is a mix of new material and typo-level corrections.
=> RefMan: Statements and Expressions edits

Test/git-issues/git-issue-216.dfy, Test/git-issues/git-issue-216.dfy.expect
Behavior is correct. Test added. Leaving Issue open until RM documentation is completed.
=> #216: Adding a test; no change in behavior

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-966.dfy, Test/git-issues/git-issue-966.dfy.expect
=> Allow datatype values as non-last component of NameSegment

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1016.dfy, Test/git-issues/git-issue-1016.dfy.expect, Test/git-issues/git-issue-1016a.dfy, Test/git-issues/git-issue-1016a.dfy.expect
=> #1016: Fix and tests for a type inference error

Test/git-issues/git-issue-975.dfy, Test/git-issues/git-issue-975.dfy.expect
This issue is fixed at the current build.  Adding tests.
Fixes #975.
=> #975: Adding tests to confirm fix

.github/workflows/msbuild.yml, .github/workflows/refman.yml, Scripts/package.py, Source/Dafny/DafnyAst.cs, Source/Dafny/DafnyPipeline.csproj, Source/Dafny/Resolver.cs, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyRuntime/DafnyRuntime.csproj, Source/DafnyServer/DafnyServer.csproj, third_party/Coco/src/Coco.csproj
Move from .NET 3.1 to .NET 5.0, which is the current and recommended version.
=> Dotnet 5.0

Source/Dafny/DafnyAst.cs, Source/Dafny/DafnyOptions.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs
This flag is no longer being used
=> feat!: Remove /dafnycc flag

Source/Dafny/Compiler.cs, Test/git-issues/git-issue-1074.dfy, Test/git-issues/git-issue-1074.dfy.expect
=> Properly substitute type arguments

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1094.dfy, Test/git-issues/git-issue-1094.dfy.expect
=> fix: Avoid name capture in :- desugaring

Source/Dafny/Compiler-go.cs, Test/git-issues/git-issue-1093.dfy, Test/git-issues/git-issue-1093.dfy.expect
=> fix: Make sure Go labels are used

Source/Dafny/Translator.cs, Test/git-issues/git-issue-1112.dfy, Test/git-issues/git-issue-1112.dfy.expect
=> fix: Use labeled heap in well-formedness checks

Source/Dafny/DafnyOptions.cs
=> Mention unsoundness of /loopUnroll in help message

Source/Dafny/Translator.cs, Test/git-issues/git-issue-1130.dfy, Test/git-issues/git-issue-1130.dfy.expect
=> Fix missing type substitution in verifier

Source/DafnyDriver/DafnyDriver.cs, Test/dafny4/git-issue106.dfy, Test/dafny4/git-issue106.dfy.expect
=> Properly detect and report out-of-resource errors returned by Boogie

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1113.dfy, Test/git-issues/git-issue-1113.dfy.expect
=> Allow subset types in LHS of element/range selection

Source/Dafny/Translator.cs, Source/Dafny/Triggers/TriggersCollector.cs, Test/dafny4/Lucas-up.dfy.expect, Test/git-issues/git-issue-1165.dfy, Test/git-issues/git-issue-1165.dfy.expect, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy.expect
=> fix: Make sure auto-triggers don't contain expressions that get rewritten

Source/Dafny/DafnyAst.cs, Source/Dafny/Translator.cs, Test/git-issues/git-issue-1150.dfy, Test/git-issues/git-issue-1150.dfy.expect
=> fix: Don't inline functions that stand for const RHSs

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1184.dfy, Test/git-issues/git-issue-1184.dfy.expect
=> fix: Expand type synonyms when resolving map domain subtraction

Source/Dafny/Triggers/TriggerUtils.cs, Test/git-issues/git-issue-1207.dfy, Test/git-issues/git-issue-1207.dfy.expect, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy.expect
There were some tests designed to catch this bug. Alas, there was no proof obligation in the test method, so it was never sent to Boogie. This PR fixes not just that test, but also fixes the problem.
Fixes #1207
=> Replace proper-subset with subset in triggers

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1227.dfy, Test/git-issues/git-issue-1227.dfy.expect
=> Detect method/function override change

Binaries/DafnyPrelude.bpl, Test/git-issues/git-issue-1248.dfy, Test/git-issues/git-issue-1248.dfy.expect
=> fix: Add antecedent to Mul associativity

Test/dafny4/gcd.dfy, Test/dafny4/gcd.dfy.expect
This PR add as a test case a definition of GCD and a proof of correctness of Euclid's subtractive GCD algorithm.
=> Add GCD example as test case

Source/Dafny/Printer.cs, Test/git-issues/github-issue-1267.dfy, Test/git-issues/github-issue-1267.dfy.expect
=> Fix pretty-printing of formal parameters (fixes #1267)

Source/Dafny/Compiler-Csharp.cs, Test/git-issues/git-issue-1199-extern.cs, Test/git-issues/git-issue-1199.dfy, Test/git-issues/git-issue-1199.dfy.expect
Resolve issue #1199 by preventing external identifiers from being renamed
=> Resolve issue #1199 by preventing external identifiers from being renamed

Source/Dafny/Cloner.cs, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1253.dfy, Test/git-issues/git-issue-1253.dfy.expect
Add test and address issue #1253, and apply some refactorings around the area
=> Add test and address issue 1253

Source/Dafny/Compiler.cs, Test/comp/Collections.dfy, Test/comp/Collections.dfy.expect
=> Fix compilation of superset operations

Source/.editorconfig
Improve how well the editor config settings match with the most common Dafny syntax style. More information here: https://github.com/dafny-lang/dafny/pull/1345#issuecomment-903770580
=> Improve .editorconfig

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs
This PR addresses https://github.com/dafny-lang/ide-vscode/issues/49 and now reports all related information for failed verifications:
=> Show nested related information

.github/workflows/msbuild.yml, Test/git-issues/git-issue-356.dfy, Test/git-issues/git-issue-356.dfy.expect
Currently, two problems are holding up our CI builds, causing us not to be able to merge any PRs. This PR attempts to fix both of those.
* One problem is that `Test/git-issues/git-issue-356.dfy` is taking too much time. This is mitigated by breaking the test methods into smaller pieces and reformulating one check. (The reformulation bears a comment in the test file and can be reverted once PR https://github.com/dafny-lang/dafny/pull/1406 is merged into master.)
* The other problem is `dotnet-format`, which complains bitterly about the automatically generated source files `Scanner.cs` and `Parser.cs`. This PR excludes those files.
=> Fix build problems du jour

Test/hofs/VectorUpdate.dfy
VectorUpdate has caused a timeout in the CI.
=> More time for long verification

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1607.dfy, Test/git-issues/git-issue-1607.dfy.expect
=> fix: constructor query CompileName

Source/version.cs
=> pre release 3.4.0

Source/Dafny/Compilers/Compiler-Csharp.cs, Test/git-issues/git-issue-1761-extern.cs, Test/git-issues/git-issue-1761.dfy, Test/git-issues/git-issue-1761.dfy.expect, Test/git-issues/git-issue-1762.dfy, Test/git-issues/git-issue-1762.dfy.expect
Fixes #1761 and also fixes #1762.
=> fix: two one-line fixes in the C# compiler

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs
=> fix(lsp): Move timeout diagnostic test to Diagnostics.cs

Source/Directory.Build.props, customBoogie.patch
Fixes bug in resource count parsing
=> Bump Boogie dependency to 2.11.4

RELEASE_NOTES.md
These release notes describe (the accepted and merged) pull request #1832 .
=> docs: Write release notes for /functionSyntax

Source/Dafny/AST/DafnyAst.cs
Full description of the issue is in #1858.
=> fix(parser): Memory leak in RevealableTypeDeclHelper (closes #1858) 

.github/workflows/xunit-tests.yml, Source/Dafny/AST/DafnyAst.cs, Source/Dafny/AST/Printer.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyMain.cs, Source/Dafny/DafnyOptions.cs, Source/Dafny/Verifier/Translator.cs, Source/DafnyDriver/DafnyDriver.cs, Source/DafnyLanguageServer.Test/Various/DiagnosticMigrationTest.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs, Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs, Source/DafnyLanguageServer/Workspace/DocumentOptions.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs, Source/DafnyPipeline.Test/IntraMethodVerificationStability.cs, Source/DafnyPipeline.Test/Issue1355.cs, Source/DafnyPipeline.Test/PluginsTest.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyServer/Server.cs, Source/DafnyServer/Utilities.cs, Source/DafnyServer/VerificationTask.cs, Source/DafnyTestGeneration/ProgramModification.cs, Source/DafnyTestGeneration/Utils.cs, Source/Directory.Build.props, customBoogie.patch
=> Update to Boogie 2.12.1

Source/DafnyDriver/BoogieXmlConvertor.cs, Source/Directory.Build.props, customBoogie.patch
=> Bump Boogie to 2.13.0

RELEASE_NOTES.md, Source/version.cs
=> Bump version to 3.5.0

Source/Dafny/DafnyOptions.cs, Source/Dafny/TestGenerationOptions.cs, Source/DafnyLanguageServer/Workspace/ThreadTaskScheduler.cs, Source/Directory.Build.props, customBoogie.patch
=> Upgrade to Boogie 2.13.2

docs/DafnyRef/UserGuide.md
I just added some basic documentation about the Dafny Server.
=> chore: Dafny Server documentation

docs/DafnyRef/UserGuide.md
Might fix #1725 (@robin-aws ?)
Based on my experience and @RustanLeino 's experience, I added a few sections in the User's guide to help someone for whom verification is slow.
=> Added debugging documentation for when verification is slow.

.github/workflows/release-brew.yml
=> chore: Fix broken test in CI

RELEASE_NOTES.md, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-2016.dfy, Test/git-issues/git-issue-2016.dfy.expect
=> fix: Resolution of static functions-by-method

Source/DafnyRuntime/DafnyRuntimeJava/build.gradle
=> Silence Gradle warnings for Java runtime

docs/_config.yml
=> Fix Jekyll warning

Source/DafnyRuntime/DafnyRuntimeJava/gradle/wrapper/gradle-wrapper.properties
=> chore: Bump gradle version

Makefile, Scripts/use-local-boogie.sh
=> Fix default Makefile target

docs/DafnyRef/Modules.md
=> doc: Describe which parts of a declaration are provided/revealed

Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs
=> fix: Fixed null warnings.

.github/CODE_OF_CONDUCT.md, .github/SECURITY.md
=> chore: Change points of contact

RELEASE.md
Adding information about updating and releasing new version of ide-vscode to provide new version of Dafny to VSCode plugin users.
=> Release guide update for VSCode plugin

docs/DafnyRef/Specifications.md
=> Document using sequences and multisets in `reads` clauses

Source/Dafny/Verifier/Translator.cs
Fix concurrency issue in Translator
=> Fix concurrency issue in Translator

RELEASE.md, RELEASE_NOTES.md, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/version.cs
=> chore: Bump version to 3.7.0

.github/workflows/release-downloads-nuget.yml
=> fix: release-downloads-nuget.yml

.github/workflows/release-downloads-nuget.yml
=> chore: Test for latest version on NuGet

.github/workflows/integration-tests-reusable.yml
=> temporary: Target older windows version

Source/Dafny/DafnyMain.cs
=> Use canonical path where needed when handling includes

Source/AutoExtern.Test/Minimal/Library1.cs, Source/AutoExtern.Test/Minimal/Library2.cs, Source/AutoExtern.Test/Tests.cs, Source/AutoExtern.Test/Tutorial/ClientApp/Makefile, Source/AutoExtern.Test/Tutorial/Library/Library1.cs, Source/AutoExtern.Test/Tutorial/Library/Library2.cs, Source/AutoExtern/Program.cs
Enable AutoExtern to consume from multiple source files
Updated both AutoExtern tests to use this new feature
=> Enable AutoExtern to consume from multiple source files

.github/workflows/refman.yml, docs/DafnyRef/Expressions.md, docs/Gemfile.lock
=> chore: Better allocated and fresh documentation

.github/workflows/publish-release-reusable.yml
#2379 did not get the workflow syntax right, and CI didn't try to evaluate it :(
=> chore: Fix workflow syntax

.github/workflows/publish-release-reusable.yml
=> chore: Path fix in command to publish to NuGet

RELEASE_NOTES.md, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/version.cs
=> Prepare to release 3.7.2

docs/DafnyRef/Attributes.md
=> Fix documentation for autocontracts

docs/DafnyRef/Attributes.md, docs/DafnyRef/DafnyRef.md, docs/DafnyRef/Expressions.md, docs/DafnyRef/Grammar.md, docs/DafnyRef/Introduction.md, docs/DafnyRef/Modules.md, docs/DafnyRef/Programs.md, docs/DafnyRef/Refinement.md, docs/DafnyRef/Specifications.md, docs/DafnyRef/Statements.md, docs/DafnyRef/SyntaxTests.md, docs/DafnyRef/Topics.md, docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md
Fixes a section level error, which causes a lot of renumbering
=> doc: section renumbering

RELEASE_NOTES.md, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/version.cs
=> Prepare for releasing 3.7.3

docs/DafnyRef/UserGuide.md
This describes what verification stability is, how to measure it, and a little about how to address it.
=> Add user guide section on verification stability

Test/comp/separate-compilation/Inputs/producer/TimesTwo.csproj, Test/comp/separate-compilation/consumer/Consumer.csproj, Test/lit.site.cfg
=> Chore: exclude broken test in `lit.site.cfg`

Makefile, RELEASE_NOTES.md
Co-authored-by: @MikaelMayer, @sorawee
=> fix: Correct two typos introduced in recent PRs

RELEASE_NOTES.md
Adds release notes that were missing from #2520.
=> Release notes for PR #2520

.github/workflows/deep-tests.yml
=> Upload nightly builds to NuGet again

Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs, Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs
Do not publish gutter status notification when the option is turned off
Added a test
=> Do not publish gutter status notification when the option is turned off

RELEASE_NOTES.md, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/version.cs
=> version bump

Scripts/package.py, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/version.cs
=> fix: Read hard-coded line from `version.cs`

RELEASE_NOTES.md, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/version.cs
=> Release 3.8.1

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Various/DiagnosticMigrationTest.cs, Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs
Migrated errors show up as warnings and with an `Outdated:` prefix in front of them.
=> Migrated errors show up as warnings

.github/workflows/publish-release-reusable.yml
Fixes bug introduced [here](https://github.com/dafny-lang/dafny/commit/709ed5a2669233195a488dceebda2594ee5eb5e5) that causes the nightly build to fail.
=> Add missing qualifier in publish step

.github/workflows/refman.yml, RELEASE_NOTES.md
=> fix: Pin Rouge version when building the manual

Source/Dafny/Compilers/Compiler-python.cs, Source/DafnyRuntime/DafnyRuntime.py, Test/comp/Arrays.dfy, Test/comp/Arrays.dfy.expect, Test/comp/Print.dfy, Test/comp/Print.dfy.expect
=> feat: Full `array` support in Python

RELEASE_NOTES.md, Scripts/package.py, Source/Directory.Build.props
=> Release 3.9.0

docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md
=> Addressing a TODO about /functionSyntax

docs/dev/news/2876.fix
Fixes https://github.com/dafny-lang/dafny/pull/2876#issuecomment-1287460272
=> Chore: Make release notes for PR 2876 clearer

docs/DafnyRef/Types.md
=> fix: Typo in the reference manual

RELEASE_NOTES.md, Source/Directory.Build.props, docs/dev/news/2820.feat, docs/dev/news/2823.feat, docs/dev/news/2826.fix, docs/dev/news/2833.fix, docs/dev/news/2847.fix, docs/dev/news/2854.fix, docs/dev/news/2876.fix, docs/dev/news/2877.fix, docs/dev/news/2884.fix, docs/dev/news/2890.fix, docs/dev/news/2904.fix, docs/dev/news/2910.fix
=> Release Dafny 3.9.1

.github/PULL_REQUEST_TEMPLATE.md
Related to https://github.com/dafny-lang/dafny/issues/2945
=> Update PR template to consider publishing a new patch release

Source/DafnyCore/Compilers/Compiler-cpp.cs, Source/DafnyCore/Compilers/Compiler-go.cs, Source/DafnyCore/Compilers/Compiler-java.cs, Source/DafnyCore/Compilers/Compiler-js.cs, Source/DafnyCore/Compilers/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Test/c++/bit-vectors.dfy, Test/c++/datatypes.dfy, Test/c++/extern.dfy, Test/c++/functions.dfy, Test/c++/tuple.dfy, Test/git-issues/git-issue-1604.dfy.expect, Test/git-issues/git-issue-2733.dfy, Test/git-issues/git-issue-2733.dfy.expect, Test/git-issues/git-issue-2792.dfy
This is a redo of https://github.com/dafny-lang/dafny/pull/2879, which was reverted due to failing tests on Windows.
The first commit is as in that PR; the second one is further clean ups (the commit message has all the details.)
=> `dafny run` cleanup, take 2

Source/DafnyCore/DafnyCore.csproj, customBoogie.patch, docs/DafnyRef/Options.txt, docs/dev/news/3136.fix
=> Bumped boogie version to 2.16.0

Source/DafnyCore/Compilers/DatatypeWrapperEraser.cs
This PR does two code improvements suggested as comments on #3056.
=> chore: Improve code from PR 3056

Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Options/ICommandSpec.cs, Source/DafnyLanguageServer/ServerCommand.cs
Fixes https://github.com/dafny-lang/dafny/issues/3218
=> Fix options for 'dafny resolve'

Source/DafnyCore/DafnyOptions.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Options/DeveloperOptionBag.cs, Source/DafnyCore/Options/ICommandSpec.cs, Test/dafny4/-
=> Accept --.dfy filename

Test/git-issues/git-issue-3288b.dfy, Test/git-issues/git-issue-3288c.dfy, docs/DafnyRef/Modules.md
This PR is a follow-up to PR https://github.com/dafny-lang/dafny/pull/3291, making a few small corrections.
=> Fix minor documentation issues about export sets

.github/workflows/integration-tests-reusable.yml
Fixes old Python on Mac OS and Windows.
=> fix: Specify Python version in the integration tests

Source/DafnyCore/Resolver/Resolver.cs, Test/git-issues/git-issue-3475.dfy, Test/git-issues/git-issue-3475.dfy.expect
=> Add test and fix for AssignOrReturnStmt related crash

Source/DafnyCore/AST/DafnyAst.cs, Source/DafnyCore/DafnyMain.cs, Source/DafnyCore/Resolver/Resolver.cs, Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Unit/GhostStateDiagnosticCollectorTest.cs, Source/DafnyLanguageServer.Test/Unit/ParserExceptionTest.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Language/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Language/Symbols/SignatureAndCompletionTable.cs, Source/DafnyLanguageServer/Workspace/Compilation.cs, Source/DafnyLanguageServer/Workspace/LanguageServerExtensions.cs, Source/DafnyPipeline.Test/FormatterBaseTest.cs, Source/DafnyPipeline.Test/IntraMethodVerificationStability.cs, Source/DafnyPipeline.Test/Issue1355.cs, Source/DafnyPipeline.Test/PluginsTest.cs, Source/DafnyPipeline.Test/Trivia.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyTestGeneration/Utils.cs
Combination of https://github.com/dafny-lang/dafny/pull/3503 and https://github.com/dafny-lang/dafny/pull/3499
=> Combination of two race condition fixes

.github/workflows/check-for-workflow-run.js
=> fix: Check correct member

.github/workflows/doc-tests.yml, .github/workflows/msbuild.yml, .github/workflows/refman.yml, .github/workflows/runtime-tests.yml, .github/workflows/xunit-tests.yml
Fixes the logic in workflows to prevent duplicated tests
=> Restricting principal workflow to pull requests

Source/DafnyCore/Dafny.atg, Test/git-issues/git-issue-1564.dfy.expect
Fixes #2176
Most of the error messages had already been fixed up.
This PR fixes the last of them.
Appropriate tests are on git-issues-1564.dfy
=> #2176: Improvements to error messages for Dafny 4

docs/DafnyRef/Expressions.md, docs/DafnyRef/Statements.md
=> Dafny 4 docs: reorganizes statement chapter sections more intuitively

RELEASE_NOTES.md, Source/Directory.Build.props, docs/dev/news/3299.feat, docs/dev/news/3450.fix, docs/dev/news/3452.fix, docs/dev/news/3456.fix, docs/dev/news/3462.feat, docs/dev/news/3502.fix, docs/dev/news/3540.feat, docs/dev/news/fix-hover-foreign.fix
=> Release Dafny 3.12.0

Test/allocated1/Allocated1.dfy, Test/allocated1/Allocated2.dfy, Test/allocated1/dafny0/Fuel.dfy, Test/allocated1/dafny0/Fuel.dfy.expect, Test/cli/errorLimit.dfy, Test/cli/errorLimit.dfy.expect, Test/dafny0/Fuel.dfy, Test/dafny0/Fuel.dfy.expect, Test/dafny4/SoftwareFoundations-Basics.dfy, Test/patterns/PatternMatchingErrors.dfy
Merging these for both 3.x and 4.x will simplify #3400.
=> Test improvements discovered as part of Z3 upgrade

Source/DafnyCore/AST/IndentationFormatter.cs
=> Fix concurrency issue in whitespaceCache

.github/workflows/deep-tests.yml
Don't release from non-master branches.
=> chore: Don't release from non-master branches

Scripts/prepare_release.py, docs/dev/RELEASE.md, docs/dev/news/3400.break, docs/dev/news/3623.break, docs/dev/news/3637.break, docs/dev/news/3641.feat, docs/dev/news/3641.fix, docs/dev/news/3647.break
Release notes about the breaking changes that we didn't add as we were constructing this branch.
Also updated from `main-3.x` (to pick up #3656)
=> chore: Missing 4.0 news items

.github/workflows/doc-tests.yml, .github/workflows/refman.yml, .github/workflows/runtime-tests.yml
=> Cancel obsolete CI test runs

.github/workflows/doc-tests.yml, .github/workflows/msbuild.yml, .github/workflows/refman.yml, .github/workflows/release-brew.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml, .github/workflows/runtime-tests.yml, .github/workflows/xunit-tests.yml, docs/dev/RELEASE.md, docs/make-snapshot
=> Changes to allow making doc snapshots from branches other than master

RELEASE_NOTES.md, Source/Directory.Build.props, docs/dev/news/2266.fix, docs/dev/news/3479.fix, docs/dev/news/3641.feat, docs/dev/news/3641.fix
=> Release Dafny 3.13.1

.github/workflows/doc-tests.yml, .github/workflows/msbuild.yml, .github/workflows/refman.yml, .github/workflows/release-brew.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml, .github/workflows/runtime-tests.yml, .github/workflows/xunit-tests.yml, RELEASE_NOTES.md, Scripts/allow_on_mac.sh, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyTestGeneration/DafnyTestGeneration.csproj, Source/Directory.Build.props, Test/git-issues/git-issue-2813.dfy, docs/dev/RELEASE.md, docs/dev/news/2266.fix, docs/dev/news/3479.fix, docs/dev/news/3641.feat, docs/dev/news/3641.fix, docs/make-snapshot
Besides the merge:
* Preemptively updated version and fixed git-issue-2813.dfy, which is affected by the major version
* Include DafnyTestGeneration as a NuGet package as well (dependency of DafnyDriver)
=> chore: Update 4.0 from 3.x post release, plus bonus fixes

RELEASE_NOTES.md, Source/Directory.Build.props, docs/dev/news/3165.break, docs/dev/news/3400.break, docs/dev/news/3623.break, docs/dev/news/3637.break, docs/dev/news/3647.break
=> Release 4.0.0

Source/DafnyCore/DafnyMain.cs, Test/name with space/run.dfy, Test/name with space/run.dfy.expect, docs/dev/news/3683.fix
=> Tested support for paths with spaces

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/CSharp/CsharpBackend.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/ExecutableBackend.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/Java/JavaBackend.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/Python/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/DafnyOptions.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyDriver/Commands/TranslateCommand.cs, Source/DafnyPipeline/DafnyPipeline.csproj, Source/XUnitExtensions/Lit/ILitCommand.cs, Source/XUnitExtensions/Lit/LitCommandWithRedirection.cs, Source/XUnitExtensions/Lit/RunCommand.cs, Test/comp/compile1verbose/CompileAndThenRun.dfy.expect, Test/comp/compile3/JustRun.dfy.expect, Test/comp/manualcompile/ManualCompile.dfy, Test/comp/manualcompile/ManualCompile.dfy.expect, Test/dafny0/JavaUseRuntimeLib.dfy, Test/dafny0/JavaUseRuntimeLib.dfy.expect, Test/verification/relaxAssignmentEnforceDeterminism.dfy, docs/dev/news/3611.fix
=> Revert #3619 to fix nightly

.github/workflows/refman.yml, docs/DafnyRef/Grammar.md, docs/DafnyRef/GrammarDetails.md, docs/DafnyRef/Refinement.md, docs/DafnyRef/Statements.md, docs/DafnyRef/Types.22.expect, docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md, docs/DafnyRef/header.tex
Fixes #3614. Fixes #3481. Fixes #3298.
=> Small miscellaneous edits + edits for 3614, 3481, 3298

.github/workflows/refman.yml
Fixes #3765 
Caused by wrong-version 2022.0314 (instead of 2023.0314) hardcoded in: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/basictex.rb
=> fix brew install pandoc github action

.github/workflows/publish-release-reusable.yml
=> Suspending nightly build of pdf until brew is fixed for pandoc

.github/workflows/publish-release-reusable.yml
=> fix: reenable release build

Source/DafnyCore/AST/Expressions/NestedMatchStmt.cs, Test/git-issues/git-issue-283g.dfy.expect, Test/git-issues/github-issue-3797.dfy, Test/git-issues/github-issue-3797.dfy.expect
=> Add test and fix bug for 3797

Source/AutoExtern/Program.cs, Source/DafnyCore/AST/Grammar/SourcePreprocessor.cs, Source/DafnyCore/AST/Statements/AssignSuchThatStmt.cs, Source/DafnyCore/CompileNestedMatch/MatchAst.cs, Source/DafnyCore/CompileNestedMatch/MatchFlattener.cs, Source/DafnyCore/Feature.cs, Source/DafnyCore/Resolver/Abstemious.cs, Source/DafnyCore/Resolver/InferDecreasesClause.cs, Source/DafnyCore/Resolver/RunAllTestsMainMethod.cs, Source/DafnyCore/Resolver/TailRecursion.cs, Source/DafnyCore/Rewriters/InductionHeuristic.cs, Source/DafnyCore/Rewriters/InternalDocstringRewritersPluginConfiguration.cs, Source/DafnyCore/Rewriters/JavadocLikeDocstringRewriter.cs, Source/DafnyCore/Verifier/Translator.ExpressionTranslator.cs, Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs, Source/DafnyCore/Verifier/Translator.cs, Source/DafnyDriver/Commands/TestCommand.cs, Source/DafnyLanguageServer.Test/Unit/DafnyLangSymbolResolverTest.cs, Source/DafnyLanguageServer.Test/Unit/GhostStateDiagnosticCollectorTest.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer.Test/Util/Stringify.cs, Source/DafnyLanguageServer/Handlers/DafnyFormattingHandler.cs, Source/DafnyTestGeneration/DeadCodeCommand.cs, Source/DafnyTestGeneration/GenerateTestsCommand.cs, Source/TestDafny/TestDafny.cs, Source/XUnitExtensions/Lit/ExitCommand.cs, Source/XUnitExtensions/Lit/NotCommand.cs, Source/XUnitExtensions/Lit/StdInCommand.cs, docs/dev/news/3790.fix
1) Applied late code review updates to change indentation and release notes
2) Refactored three chains of if statements in Translator so that it makes it easier to debug, and the compiled code will also run faster. Doing this in prevision of #3778
3) Applied dotnet format whitespace Source/Dafny.sln
=> Chore: refactors enhancement

Source/DafnyCore/Verifier/Translator.cs, Test/git-issues/git-issue-3804b.dfy
=> Minor updates after #3838

docs/DafnyRef/Types.md
=> Revising text about witness clauses

Test/git-issues/git-issue-1992.dfy, Test/git-issues/git-issue-1992.dfy.expect
=> Adding test case for resolved issue #1992

Source/DafnyCore/AST/DafnyAst.cs, Source/DafnyCore/AST/MemberDecls.cs, Source/DafnyCore/AST/TopLevelDeclarations.cs, Source/DafnyCore/DafnyMain.cs, Source/DafnyPipeline.Test/FormatterBaseTest.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyTestGeneration/Utils.cs
These changes are in support of dafny doc, but are generally useful.
=> Adding utility functions; tightening types

Source/TestDafny/MultiBackendTest.cs, Test/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect
Attempt to fix nightly: https://github.com/dafny-lang/dafny/actions/runs/4967410369/jobs/8889391071
=> Use new style argument where appropriate

Source/DafnyCore/Compilers/SinglePassCompiler.cs, Test/git-issues/git-issue-4007.dfy, Test/git-issues/git-issue-4007.dfy.expect, Test/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect, docs/dev/news/4015.fix
=> fix: Correctly update `wStmts`

Test/metatests/InconsistentCompilerBehavior.dfy, Test/metatests/InconsistentCompilerBehavior.dfy.expect, Test/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect
=> Stabilizing a flaky test

Test/git-issues/git-issue-3370.dfy, Test/git-issues/git-issue-3370.dfy.expect
=> Adding test to confirm fix for issue #3370

Source/DafnyCore/Verifier/Translator.TrStatement.cs, Test/git-issues/github-issue-4004.dfy, Test/git-issues/github-issue-4004.dfy.expect, Test/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect
=> Add test and fix for issue 4004

docs/dev/RELEASE.md
=> Add an item to the Release instructions: add new release to the library tests

docs/DafnyRef/Types.25.expect, docs/DafnyRef/Types.md, docs/HowToFAQ/FAQMapMembership.md, docs/HowToFAQ/index.md, docs/HowToFAQ/onepage.md
Fixes #3737
Documentation only PR about an unobvious failing proof about maps.
=> Adding documentation related to proofs about maps

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/Verifier/Translator.ExpressionTranslator.cs, Test/git-issues/git-issue-2778/git-issue-2778.dfy.expect
=> Removing dead code related to :handle

Source/DafnyLanguageServer.Test/Various/IncludeFileTest.cs, Source/DafnyLanguageServer/Workspace/Documents/DocumentAfterParsing.cs
Do not show that an incluced file has errors multiple times for the same file
=> Fix for included file errors

Source/DafnyCore/AST/Substituter.cs, Test/git-issues/git-issue-4000.dfy, Test/git-issues/git-issue-4000.dfy.expect, docs/dev/news/4000.fix
=> Fix: No more crash when using constant in pattern

.github/workflows/publish-release-reusable.yml, .github/workflows/refman.yml
Fixes brew update failures such as https://github.com/dafny-lang/dafny/actions/runs/5452609052/jobs/9920354303?pr=4237
Relevant discussion: https://github.com/orgs/Homebrew/discussions/4612#discussioncomment-6313156
=> Simplify brew update

Source/DafnyCore/Dafny.atg, Source/DafnyCore/DafnyFile.cs, Test/dafny0/Input/IncludesTuples.dfy, Test/dafny0/Stdin.dfy, Test/dafny0/Stdin.dfy.expect
This reverts commit 041e0c35be098f536b99051b7de8184accf61054.
=> Revert "fix: --stdin regressions (#4254)"

Source/DafnyCore/Dafny.atg, Source/DafnyCore/DafnyFile.cs, Test/dafny0/Input/IncludesTuples.dfy, Test/dafny0/Stdin.dfy, Test/dafny0/Stdin.dfy.expect
See https://github.com/dafny-lang/dafny/pull/4254
=> fix: --stdin regressions (un-revert of #4254 with test fix)

Source/DafnyCore/AST/ShouldCompileOrVerify.cs, Source/DafnyLanguageServer/Workspace/ProjectManager.cs, Test/comp/Libraries/consumer.dfy
=> fix: Transitive excludes when skipping files

Scripts/quicktest.sh, Source/DafnyCore/Compilers/Rust/RustBackend.cs
Run Cargo in quiet mode to fix integration tests
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4351).
* #4352
* #4346
* #4343
* __->__ #4351
=> Run Cargo in quiet mode to fix integration tests

.github/workflows/doc-tests.yml, .github/workflows/integration-tests-reusable.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/xunit-tests-reusable.yml, Makefile, Scripts/package.py
Implements #4304.
This PR is not yet complete as it requires a new snapshot in the https://github.com/dafny-lang/solver-builds repo. @atomb, could you please create it?
=> Use arm64 version of Z3 4.12.1 for arm64 macOS releases of Dafny

Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/GeneratedFromDafnyRust.cs
Support datatype destructors in the Rust backend
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4353).
* #4369
* #4368
* #4363
* #4361
* __->__ #4353
=> Support datatype destructors in the Rust backend

Source/DafnyCore/Resolver/HigherOrderHeapAllocationCheckerConstructor.cs, Test/Landin/Knot16.dfy, Test/Landin/Knot16.dfy.expect, Test/Landin/Knot17.dfy, Test/Landin/Knot17.dfy.expect
=> Catching more knots

.github/workflows/refman.yml
Aims to fix build failures like [this one](https://github.com/dafny-lang/dafny/actions/runs/6047794893/job/16415040051?pr=4499).
=> Try building the reference manual on Linux

Source/DafnyLanguageServer.Test/ProjectFiles/ProjectFilesTest.cs, Source/DafnyLanguageServer/Workspace/CompilationManager.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs
Fix a bug that could lead to multiple project managers all using the same project file
Added a server test
=> Fix a bug related to project managers

Source/DafnyCore/AST/IHasUsages.cs, Source/DafnyLanguageServer.Test/Lookup/HoverTest.cs
- Fix an NRE that could occur on hover want the document has parse error
- Added a unit test
=> Fix get member qualification nre

Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Fixes #4540
Do not create verification trees for non-constant fields that can never trigger verification
Added an XUnit test
=> Fix gutter icons fields

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer/Workspace/CompilationManager.cs, docs/dev/news/4607.fix
Allow least lemmas to be verified in the IDE
Added XUnit test
=> Fix least lemma IDE verification bug and add test

.github/PULL_REQUEST_TEMPLATE.md
Update template for pull requests
I copied the new file into this text area and filled in the blanks.
=> Update PR template to add a testing section

Source/DafnyCore/Compilers/ExecutableBackend.cs
Fixes: https://github.com/dafny-lang/dafny/issues/4686
=> Crash in Dafny backend

Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/DafnyGeneratedFromDafny.sh, Source/DafnyCore/GeneratedFromDafny.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-364.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-364.dfy.rs.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/metatests/TestBeyondVerifierExpect.dfy.testdafny.expect
Enable integration tests to run with the Rust backend in CI
=> Enable integration tests to run with the Rust backend in CI

docs/DafnyRef/UserGuide.md
=> Fix typos in UserGuide

Source/DafnyCore/AST/Expressions/DefaultValueExpression.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4724.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4724.dfy.expect, docs/dev/news/4724.fix
=> Fix: Crash using subset type #4724

Source/DafnyCore/DafnyCore.csproj, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/github-issue-4804.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/github-issue-4804.dfy.expect, customBoogie.patch, dotnet-tools.json
Update Boogie to v3.0.8.
Fixes #4804
May also fix #4577
Added `git-issues/github-issue-4804.dfy`.
=> Bump Boogie dependency to v3.0.8

Source/DafnyLanguageServer/Workspace/ProjectManager.cs
Prevent exceptions in the IDE codebase
I don't know how to test this change
=> Improve code hygiene around Dispose methods

.github/workflows/publish-release-reusable.yml
Hopefully fixes https://github.com/dafny-lang/dafny/issues/4838
=> Release process on Mac instead of Ubuntu

Source/IntegrationTests/TestFiles/LitTests/LitTest/VSComp2010/Problem4-Queens.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/VSComp2010/Problem4-Queens.dfy.expect
This PR updates the comments and syntax of the Queens test program, and updates the test to also run the program.
=> Update queens example

Source/IntegrationTests/TestFiles/LitTests/LitTest/autoRevealDependencies/dfyconfig.toml, docs/DafnyRef/UserGuide.md
Fixes https://github.com/dafny-lang/dafny/issues/4895
=> Remove unused and incorrect dfyconfig.toml

.github/workflows/check-for-workflow-run.js
The 'check-deep-tests' step of the CI worflow often fails because the nightly is somewhere in the process of running, but apparently not in the `in_progress` state. This change makes sure that check only fails if nightly actually failed
Careful code review
=> Relax 'check-deep-tests' workflow to make CI incorrectly fail less often

docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md
=> Kill off last uses of "opaque type"

.github/workflows/check-deep-tests-reusable.yml, .github/workflows/check-for-workflow-run.js
- Fix the nightly build check so it fails if the last completed build was a failure or timed out.
- Read the code twice
- I will do a manual test once this is merged
=> Fix bug in check deep tests script

docs/DafnyRef/VSCodeIDE.md
Fixes #4938
Update documentation for Dafny server
=> Update documentation for Dafny server

docs/dev/news/4951.feat
Add a feature description for the feature added in #4951.
=> Add feature description for #4951

.github/workflows/integration-tests-reusable.yml, .github/workflows/runtime-tests.yml, .github/workflows/standard-libraries.yml
Should fix nightly build break caused by https://github.com/dafny-lang/dafny/pull/4777
=> fix: Move “GO111MODULE=on” to env: to work with Windows too

.github/workflows/publish-release-reusable.yml, .github/workflows/refman.yml, docs/DafnyRef/Makefile
We've frequently had trouble building `DafnyRef.pdf` because installing TeXLive fails in some way. This attempts to use Tectonic, instead, to see if it fares better.
=> Attempt to build DafnyRef using Tectonic

Source/DafnyCore/Backends/CSharp/CsharpBackend.cs, Source/DafnyCore/Backends/Cplusplus/CppBackend.cs, Source/DafnyCore/Backends/ExecutableBackend.cs, Source/DafnyCore/Backends/GoLang/GoBackend.cs, Source/DafnyCore/Backends/Java/JavaBackend.cs, Source/DafnyCore/Backends/JavaScript/JavaScriptBackend.cs, Source/DafnyCore/Backends/Library/LibraryBackend.cs, Source/DafnyCore/Backends/Python/PythonBackend.cs, Source/DafnyCore/Backends/Rust/RustBackend.cs, Source/DafnyCore/Pipeline/NoExecutableBackend.cs, Source/DafnyCore/Plugins/IExecutableBackend.cs, Source/DafnyDriver/Legacy/SynchronousCliCompilation.cs, Source/XUnitExtensions/Lit/CombinedWriter.cs
Refactoring
Pure refactoring, no additional tests needed
=> Use Tasks for running processes

Source/IntegrationTests/TestFiles/LitTests/LitTest/logger/VerificationLogger.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/logger/VerificationLogger.dfy.expect
=> Remove fragile .expect file that doesn't test much

Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs
Fix oopsie in TestNotificationReceiver
Change in tests
=> Fix oopsie in TestNotificationReceiver

Source/IntegrationTests/TestFiles/LitTests/LitTest/hofs/ArrowTypeOptimizations.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/hofs/ArrowTypeOptimizations.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/verification/Inputs/progressFirstSequence.check, Source/IntegrationTests/TestFiles/LitTests/LitTest/verification/Inputs/progressSecondSequence.check, Source/IntegrationTests/TestFiles/LitTests/LitTest/verification/isolate-assertions.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/verification/progress.dfy
Update tests that use --progress, so they no longer depend on an unstable order
Tests were changed
=> Update tests that use --progress, so they are stable

Source/DafnyLanguageServer.Test/Performance/ThreadUsageTest.cs
Fixes https://github.com/dafny-lang/dafny/issues/5228
- Add retries to NoExtraThreadAfterEachChange to make it stable
- PR changes tests
=> Add retries to NoExtraThreadAfterEachChange

Source/IntegrationTests/TestFiles/LitTests/LitTest/doofiles/Test4.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/doofiles/Test4.dfy.expect
Fixes https://github.com/dafny-lang/dafny/issues/4070
Turning on doofiles/Test4.dfy
It's adding a test
=> Turning on doofiles/Test4.dfy

Source/DafnyLanguageServer.Test/Synchronization/CloseDocumentTest.cs, Source/DafnyLanguageServer/Workspace/IdeStateObserver.cs, docs/dev/news/5437.fix
- Clear diagnostics when closing documents in projects
- Added IDE test
=> Clear diagnostics when closing documents in projects

Source/DafnyLanguageServer.Test/Synchronization/CachingTest.cs
Fixes https://github.com/dafny-lang/dafny/issues/5434 (hopefully)
=> Attempt to fix the stability of DocumentAddedToExistingProjectDoesNotCrash

docs/DafnyRef/Statements.md
=> docs: The number of left-hand-sides must match the amount of out-parameters

Source/DafnyRuntime/DafnyRuntimeRust/Cargo.toml
remove unused crates from Cargo.toml
If it compiles, that's test enough.
=> chore: remove unused crates from Cargo.toml

.github/workflows/doc-tests.yml, .github/workflows/integration-tests-reusable.yml
=> chore: `apt-get update` before `apt-get install`

.github/workflows/nightly-build.yml
Does exactly what it says on the tin.
=> Publishing nightly builds from 4.9 release branch

Source/DafnyCore/Verifier/BoogieGenerator.ExpressionTranslator.cs, Source/DafnyCore/Verifier/BoogieGenerator.LetExpr.cs
=> Rename variable according to capitalization rules

Source/DafnyCore/AST/Grammar/Printer/Printer.Statement.cs, Source/DafnyCore/AST/Statements/ControlFlow/BreakOrContinueStmt.cs, Source/DafnyCore/AST/Substituter.cs, Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.Statement.cs, Source/DafnyCore/Dafny.atg, Source/DafnyCore/Resolver/GhostInterestVisitor.cs, Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs, Source/DafnyCore/Resolver/PreType/PreTypeResolve.Statements.cs, Source/DafnyCore/Resolver/TailRecursion.cs, Source/DafnyCore/Rewriters/RefinementTransformer.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrStatement.cs
=> Rename BreakStmt to BreakOrContinueStmt

docs/DafnyRef/Types.md
=> docs: fix broken link to newtypes section

README.md, docs/DafnyRef/UserGuide.md
Small PR - Commit 7fc07d3718e153fde20364cb384b018dff0dc81b moved source files into `DafnyCore`. This PR adjusts sources to changes. It also fixes a few typos along the way in those files.
=> Update DafnyCore references

docs/Snapshots.md
=> Documentation snapshot for v4.9.1

script.sh
Add a script.sh file to run scripts
Manually ran the shell file with a few different commands
=> Add a script.sh file to run scripts

docs/news/fix.3809
Adds a FIX file after PR #6031  to ensure fix for #3809 is in the release notes.
=> Adding a fix file for PR 6031

Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.Statement.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/Arrays.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/expectations/ExpectAndExceptions.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/expectations/ExpectAndExceptions.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/unicodecharsFalse/expectations/ExpectAndExceptions.dfy.expect, docs/dev/news/6050.fix
Allow translating by blocks
Updated CLI tests
=> Allow translating by blocks

Source/IntegrationTests/TestFiles/LitTests/LitTest/README.md, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/CoinductiveProofs.dfy
=> Chore: macosx unsupported for a performance file because inconsistent RC

Source/DafnyCore/Backends/Java/JavaCodeGenerator.cs, Source/DafnyCore/Backends/SinglePassCodeGenerator/SinglePassCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6149.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6149.dfy.expect, docs/dev/news/6149.fix
=> Fix: Java lambdas now accepting boxing/unboxing

Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/PrecedenceLinter.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/PrecedenceLinter.dfy.expect
This PR includes some tests that were previously omitted, waiting for another source change to happen. That other source change has now happened, so the tests are being included.
=> Include previously postponed tests

Source/DafnyCore/AST/Statements/OpaqueBlock.cs, Source/DafnyLanguageServer.Test/Diagnostics/DiagnosticsTest.cs, docs/dev/news/6203.fix
Fixes #6203
- Fix handling of opaque blocks by the Dafny IDE
- Added an IDE test
=> Opaque block clone

Source/DafnyCore/AST/Expressions/Applications/MemberSelectExpr.cs, Source/DafnyCore/AST/SyntaxDeserializer/Generated.cs, Source/DafnyCore/AST/TypeDeclarations/ClassLikeDecl.cs, Source/DafnyCore/AST/TypeDeclarations/TraitDecl.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatAnything.dfy, Source/Scripts/Syntax.cs-schema, Source/Scripts/SyntaxSchemaGenerator.cs
- Enable TraitDecl in the binary input
- Updated inputFormatAnything.dfy
=> More syntax constructors

Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs, Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6210.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6210.dfy.expect
Fixes #6210 
Removed old initialization code for Tuple since it's not sound anyway.
The test is now passing, did not pass before.
=> Fix 6210 dafny to rust compilation issue with defaults

Source/DafnyCore/AST/Grammar/ProgramParser.cs, Source/DafnyCore/AST/SyntaxDeserializer/Generated.cs, Source/DafnyCore/AST/SyntaxDeserializer/HandWritten.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatAnything.dfy, Source/Scripts/SyntaxDeserializerGenerator.cs
Needed to add a SystemModuleModifiers to the SyntaxDeserializer
=> Support of MultiSelector in Deserializer

Source/DafnyCore/AST/Tokens.cs
This should fix the nightly tests.
=> FIx: Relative names for CI

.github/workflows/integration-tests-reusable.yml
=> chore: Replace hard-coded path in CI
