Docs/DafnyRef/DafnyRef.bib, Docs/DafnyRef/DafnyRef.mdk
These changes are responses to almost all of Rustan's most
recent comments on the draft Dafny reference manual.
Yet to come is a re-ordering of the sections on
Expressions, and writing the section on module refinement.
=> Changes to Dafny Reference Manual based on Rustan notes

Docs/DafnyRef/DafnyRef.mdk
Closes #121.
Thanks to @cpitclaudel for the script to make these fixes automatically.
=> Fix misencoded characters in DafnyRef

Source/Dafny/Cloner.cs, Source/Dafny/Compiler.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Parser.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/dafny4/git-issue129.dfy, Test/dafny4/git-issue129.dfy.expect
Fixes #129.
This PR allows arbitrary case patterns to appear on the LHS of a LetStmt. See #129 for an example.
There is a parsing ambiguity when the LHS is a simple identifier not followed by parens, which we resolve by choosing VarDeclStatement over LetStmt.
=> Support pattern matching on LHS of LetStmt

Source/Dafny/Translator.cs, Source/Dafny/Triggers/TriggerExtensions.cs, Source/Dafny/Triggers/TriggersCollector.cs, Test/dafny0/Modules1.dfy, Test/triggers/let-expressions.dfy, Test/triggers/let-expressions.dfy.expect, Test/triggers/loop-detection-is-not-too-strict.dfy, Test/triggers/loop-detection-is-not-too-strict.dfy.expect
Fixes #128.
When TriggerAnnotation.Annotate encounters a LetExpr, it now inlines the let using Translator.Substitute (which is now static to make it easy to call from outside the translator).
This improves trigger selection when there are lets inside a quantifier. There was even an (admittedly synthetic) existing test case in the test suite that ran into this problem!
Note that the inlined expression is only considered for the purposes of trigger selection. The rest of the pipeline continues to see the un-inlined expression.
I considered factoring Translator.Substitute out of the translator and into its own file (or into Cloner), but in the end I felt that it made sense to leave it there because of the scary comment about dropping parts of expressions that are only for well-formedness …
=> Inline lets before trigger selection

Binaries/dafny
There's no need to check if the execute permission is granted on the "Dafny.exe" file because the execution is done through mono
=> Checking only if "Dafny.exe" file can be found

Source/Dafny/DafnyAst.cs, Test/dafny4/git-issue161.dfy, Test/dafny4/git-issue161.dfy.expect
Previously two collection types were considered equal if they were the
same type of collection, even if they had different type parameters.
This caused a missing error message and compilation errors if two
datatype destructors shared a name.
Fixes #161 and passes the test suite.
=> Check type parameters when checking if types are equal

Source/Dafny/Translator.cs, Source/Dafny/Triggers/TriggerExtensions.cs, Source/Dafny/Triggers/TriggersCollector.cs, Test/dafny0/LetExpr.dfy, Test/dafny0/LetExpr.dfy.expect
Fix two bugs involving combining let-such-thats with quantifiers:
* When inlining lets during trigger selection, we need to check the let is exact (i.e., not a let-such that)
* After fixing that issue, a let-such-that within a quantifier generates invalid Boogie, because let desugaring reuses a (mutable) substitution map that has had the quantified variables removed
=> Fixes for quantifiers + let-such-that expressions

Source/Dafny/Triggers/QuantifiersCollector.cs, Test/dafny4/git-issue167.dfy, Test/dafny4/git-issue167.dfy.expect
Let expressions can change trigger selections in undesirable ways. For example, this expression:
var p := map n: nat | n in env :: n;
map n: nat | n in p :: n
has `n in p` selected as a trigger, but if we manually inline `p` there is no trigger found. `n in p` isn't a valid trigger here, since `p` will get inlined into the trigger later.
To fix this, we (temporarily) inline all lets before collecting the set of quantifiers to select triggers for. In some sense this is the converse of #130 -- here we inline lets appearing *outside* a quantifier.
Fixes #167.
=> Inline let-expressions before collecting quantifiers for trigger selection

Docs/OnlineTutorial/guide.md
Corrects two possible typos in the conclusion.
"...*one* needs to plow ahead..."
"...what the code does *in* a precise way..."
=> Two typos in the conclusion

Test/lit.site.cfg
GOCACHE needs to be set and forwarded to lit's environment
=> Fixed Go test errors in Windows

Source/Dafny/Resolver.cs
This reverts commit d106ef85c90405206db0319e0ca7420b7cf972c0.
The change breaks wildcard matching, such that even simple
programs like
```
module Foo {
datatype t = A
function method f(x: t): bool {
match x
case _ => true
}
}
```
fail.
=> Revert "Allow type variables in tuples"

Binaries/DafnyPrelude.bpl, Test/dafny4/git-issue250.dfy, Test/dafny4/git-issue250.dfy.expect
Dafny /arith:10 Test/dafny1/Cubes.dfy
gets stuck in a matching loop due to the associativity axiom.
Adding a guard, checking whether the second argument is non-zero prevents the rewrite and hence z3 entering the matching loop.
=> Mul associativity axiom: add a guard to prevent matching loop

Source/Dafny/Compiler-Csharp.cs
This commit fixes the following issue:
In cygwin and I assume other systems with Unix path separators, when Dafny is called with an external C# source file in a subdirectory, the C# compiler would not be passed the correct path. It would assume the external C# file is in the current directory.
e.g. `Dafny.exe src/file.dfy src/file-extern.cs` would call the C# compiler with `file-extern.dfy` instead of `src/file-extern.cs`.
=> Unix path separator in 'otherFilenames' not passed on

Binaries/DafnyPrelude.bpl, Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Translator.cs, Test/dafny0/snapshots/Snapshots0.run.dfy.expect, Test/server/git-issue223.transcript.expect
Fixed a performance issue by changing the antecedent of the axiom, preserving equality of `SeqFromArray` through `HeapSucc`, to check equality of the heap on object instead of field granularity.
This is possible after changing the Heap's type from `type Heap = <alpha>[ref,Field alpha]alpha;` to `type Heap = [ref]<alpha>[Field alpha]alpha;`---i.e., currying.
This required to change the frame condition.
Some test cases had to be updated to reflect changes to the counterexamples or output messages.
Also changed the `HeapSucc` transitivity axiom to exclude cycles, to prevent matching loops.
Test suite after the change sorted by absolute runtime change (positive numbers are slowdowns, negative speedups), compared to master on June 6: https://gist.github.com/mschlaipfer/03814aeacfdc6c4cfe4a74cf0 …
=> Axiomatization of SeqFromArray, HeapSucc, and frame condition

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-277.dfy, Test/git-issues/git-issue-277.dfy.expect
Fixes #277. There were two errors: typechecking did not occur for indices of slices, and there was a formatting error when calling ConstrainSubtypeRelation.
=> Fix type resolution for multi-indexing

Source/Dafny/Resolver.cs, Test/dafny0/ResolutionErrors.dfy, Test/dafny0/ResolutionErrors.dfy.expect
Dafny created incorrect Boogie files that would talk about constants in the frame condition, thus generating syntacticaly incorrect Boogie.
This commit adds a check that will create an error in Dafny and prevent incorrect Dafny files being compiled into incorrect Boogie.
This issue did not occur when Dafny called Boogie directly, without the detour to a Boogie file.
=> Added error reporting when a const is mentioned in frame condition

Source/DafnyDriver/DafnyDriver.cs
This changes reflect the following scenarios
1. If compile flag is set to 0 during invocation of the Dafny command, no compilation should take place, for e.g.
`dafny /spillTargetCode:2 /compile:0 foo.dfy`
hence we can ignore the output returned by 
`var compiled = Compile(dafnyFileNames[0], otherFileNames, dafnyProgram, oc, statss, verified);`
2. If compile flag is anything but 0 during invocation of the Dafny command, then control flow will proceed as normal.
Fixes  https://github.com/dafny-lang/dafny/issues/305
=> Take compile flag into consideration and return appropriate exit code

Source/Dafny/DafnyAst.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/Maps.dfy.expect, Test/dafny0/Maps.dfy.expect, Test/git-issues/git-issue-336.dfy, Test/git-issues/git-issue-336.dfy.expect
If a general map comprehension has the form `map x | R(x) :: x := T(x)`, then
translate it (in the verifier) in the same way as the common `map x | R(x) :: T(x)`.
Fixes #336
=> Try to treat general map comprehension as the common case

Binaries/dafny
I'd like to run `dafny` from a MINGW shell (the shell I get when I open "Git Bash" on Windows).
In the current state, this fails, because I don't have `mono`.
But since I'm on Windows, I don't need `mono`, and running `Dafny.exe` directly works.
This PR makes the `dafny` bash script detect whether we're on MINGW, and if so, it does not require/use `mono`.
Only tested on Windows so far.
=> allow dafny to be invoked from a MINGW/"Git Bash" shell

.travis.yml
The [latest commit on master](https://github.com/dafny-lang/dafny/commit/5c2d097dac070908069906b1f19c6cffbd98748c) built [successfully](https://travis-ci.org/dafny-lang/dafny/builds/556576411) on Travis using mono 5.20.1.19, but since then, mono 6.0.0 has been released, and since `.travis.yml` does not currently specify a mono version explicitly, Travis always picks the latest mono version, so newer PRs (such as eg https://github.com/dafny-lang/dafny/pull/335) are now built with mono 6.0.0, which introduces a few braking changes, so the CI builds for all PRs fails at the moment.
The failure happens when building boogie, so the the correct fix for this would be to figure out how to port boogie from mono 5.20.1 to mono 6.0.0 (note that this is not visible on Boogie's CI because Boogie's CI …
=> pin mono version

Test/lit.site.cfg
In some environments with cygwin (see https://github.com/dafny-lang/dafny/pull/318), os.name returned "posix", which caused mono to be used on Windows.
`platform.system()` returns
- "Windows" in my cmd, git bash, and cygwin shell
- "Linux" on the Ubuntu Travis
- "Darwin" on Mac as tested by Prath
So the most reliable check seems to be `platform.system() != "Windows"`
=> use platform.system() instead of os.name to detect whether to use mono

Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler.cs
Fixes a precondition contract failure. Since CodeContracts generate full run-time checks only on Windows and this affected only 4 test files when compiled with the Go compiler, the precondition violation was apparently not detected until now.
=> Fix null-dereference crash

Source/Dafny/Translator.cs, Test/lambdas/LambdaEq.dfy, Test/lambdas/LambdaEq.dfy.expect
In order to be able to compare two functions for equality we want to ensure that the domains of the functions are the same. In order to achieve that we want to be able to compare two functions' `requires` clauses. For example, the following functions should be considered unequal in Dafny:
```
f: int -> int := (x: int) => x
g: nat -> int := (x: nat) => x
```
However, at the moment, the translations of the `requires` clauses of `f` and `g` would quantify over _all_ inputs and always return true without taking into account that we should quantify only over inputs of type `int` or `nat`. In Boogie pseudocode the translation would look like this:
```
forall x :: f.requires == true
forall x :: g.requires == true
```
As a result, the two functions will be considered equal.
To avoid this, we must …
=> Typecheck variables in the Requires clause of lambda functions (handles)

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Parser.cs, Source/Dafny/RefinementTransformer.cs, Source/Dafny/Scanner.cs, Source/Dafny/Translator.cs
While working on [Exceptions](https://github.com/dafny-lang/dafny/pull/348), I was surprised that in annotations, `{:` is two tokens.
At some point, this created a problem because in order to distinguish between set display `{1, 2, 3}` and `{:myAnnotation}`, a lookahead was needed. However, I changed the parser again, so it's not a problem any more and I believe I could implement Exceptions without making `{:` one token.
But still, I think making `{:` one token would simplify things, so I'm making this PR.
Note that strictly speaking, this is a breaking change: Previously, `{ :myAttribute}` was accepted, but now it isn't any more, and you have to remove the space. But the whole test suite passes, so I think it's ok to enforce a consistent style of not allowing a space between `{` and `:`.
=> Make `{:` one token instead of two for annotations

Source/Dafny/Compiler.cs, Test/comp/Class.dfy, Test/comp/Class.dfy.expect
Dafny does not care about the order in which static or module-level `const` declarations are given, but there must not be any cyclic dependencies among them. The semantics is independent of the order of declaration. Target languages may care about this ordering, so the compiler sorts the declarations according to the dependency relation computed in the Resolver. Alas, the comparison operation used to sort the declarations was reversed, so the declarations ended up in the opposite order of what was needed.
=> Fix ordering of static const's

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Test/dafny0/Compilation.dfy
Previously, a `const` named `namespace` (for example) would generate malformed C# (and similarly for other target languages).
=> Fix name protect for const

Binaries/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.cs, Test/comp/Collections.dfy, Test/comp/Collections.dfy.expect
I thought this had been fixed during the summer, but I couldn't find the change, so I re-implemented the fix.
=> Use BigInteger multiplicities for multisets in C#

INSTALL.md
I made dafny available on homebrew. It can be simply installed with one line now.
=> Simple installation on Mac OS X

Binaries/DafnyRuntime.cs, Source/Dafny/Compiler-Csharp.cs, Source/DafnyRuntime/DafnyRuntime.cs
Currently, s[lo..hi] is translated as s.Take(hi).Drop(lo), which is very expensive if lo is high.  This patch writes s.Subsequence(lo, hi) instead, where Subsequence is a new Sequence method.
=> C#: Add Dafny.Sequence.Subsequence()

Test/dafny2/MajorityVote.dfy
Remove one unneeded function postcondition.
Remove unnecessary parentheses and semi-colons.
=> Clean up MajorityVote example

Source/Dafny/Resolver.cs, Test/dafny0/LabeledAssertsResolution.dfy, Test/dafny0/LabeledAssertsResolution.dfy.expect, Test/dafny0/ParallelResolveErrors.dfy.expect, Test/dafny0/ResolutionErrors.dfy.expect
Do hints checks not just in `calc` hints, but also in `assert-by` hints.
Check LHSs of call statements in hints (to abide by the same rules as LHSs in assignment statements).
Disallow `modify` statement in hints.
Disallow `modify` statements in `forall` statements.
Fixes #408.
=> Assert-by checks

Binaries/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.cs
Building a sequence of length n by repeatedly using + to append them takes O(n^2) time, and there isn't a convenient alternative to doing it this way (since Dafny doesn't have variable-length arrays).  This patch changes the C# runtime library to make concatenation lazy to knock this down to O(n) (so long as none of the intermediate sequences are ever accessed besides using +).
The behavior is very simple:  A sequence built by concatenation remains lazy until any operation besides + is performed on it, at which point all the sequences in the chain get concatenated in one go.  At that point, the sequence's elements are stored in an array as usual.
Caveats: There's all the usual laziness overhead---a little extra setup up front, and then an extra few checks on each access (including …
=> C#: Lazy sequence concatenation

Source/Dafny/DafnyAst.cs, Source/Dafny/Rewriter.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/OpaqueFunctions.dfy.expect, Test/dafny0/OpaqueFunctions.dfy, Test/dafny0/OpaqueFunctions.dfy.expect
Previously, the machinery to process `{:opaque}` only looked at functions in `ClassDecl`s. Now, it handles opaque functions in all types with members.
=> Allow datatype/newtype functions to be opaque

Binaries/DafnyRuntime.cs, Source/Dafny/Compiler-Csharp.cs, Source/DafnyRuntime/DafnyRuntime.cs
The static two-argument object.Equals does the same thing as Dafny.Helpers.AreEqual.
=> C#: Deprecate Dafny.Helpers.AreEqual in favor of static object.Equals

Binaries/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.cs
The only advantage with the `List` was that the underlying `Dictionary` could then be
created with an accurate capacity. That doesn't seem very important compared to having
to always to make a `List` from an `IEnumerable`.
=> Change argument type of Map.FromCollection from List to IEnumerable

Source/Dafny/Compiler-Csharp.cs, Test/dafny0/Extern.dfy, Test/dafny0/Extern.dfy.expect, Test/dafny0/Extern2.cs
Compilation of methods to C# support a 2-argument `:extern`, which gives
both a method name and a full qualification to that method. Previously, this
was not supported for functions, which had just ignored the qualification
argument. This commit fixes that.
Fixes #423.
=> Support two-argument extern for functions

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler.cs, Source/DafnyRuntime/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/BigRational.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/UByte.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/UInt.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/ULong.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/UShort.java, Test/comp/NativeNumbers.dfy, Test/comp/NativeNumbers.dfy.expect, Test/comp/Numbers.dfy, Test/comp/Numbers.dfy.expect
As a C# example, x < BigInteger.Zero is slower than x.Sign < 0, possibly
because of the access of BigInteger.Zero (or perhaps just because
BigInteger.Sign is cheap).
Currently only implemented for C#, Java, and Go; the JavaScript BigInteger class we're using doesn't have a sign() method.  (We could use .isZero(), .isPositive(), and isNegative() in that case.)
=> Optimize comparisons to zero

Source/Dafny/DafnyAst.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/LitTriggers.dfy.expect, Test/dafny0/LitTriggers.dfy, Test/dafny0/LitTriggers.dfy.expect, Test/hofs/TreeMapSimple.dfy, Test/hofs/TreeMapSimple.dfy.expect
Previously, `this` was not treated like other parameters in the "lit axioms"
that allow function definitions to be expanded without consuming fuel in
the verifier. Perhaps that was okay before, we `this` was usually the same
in a recursive call. With type members for other types, like `datatype`,
a recursive function is likely to be called on something other than `this`.
In effect, this meant that the verifier could get stuck in infinite matching,
especially when faced with a false proof obligation (and in at least one
observed true proof obligation). The assertion in LitTriggers.dfy would
cause the verifier to never come back, but with this fix, the assertion is
quickly reported as an error.
This fix required `ThisExpr` nodes to be translated into Boogie AST nodes
with a filled-in type. …
=> Treat receiver like other parameters in lit axioms

Binaries/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.cs
Recovers the optimization lost when the argument type was generalized to `IEnumerable`.
=> Initialize capacity in Map.FromCollection when possible

Source/Dafny/Rewriter.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/Termination.dfy.expect, Test/dafny0/AutoContracts.dfy.expect, Test/dafny0/PrefixTypeSubst.dfy.expect, Test/dafny0/Termination.dfy, Test/dafny0/Termination.dfy.expect
`this` can be used explicitly in `:induction` attribute, and is also being considered
for automatic inclusion.
=> Allow "this" among quantified induction variables

Source/Dafny/Translator.cs, Test/allocated1/dafny0/TypeParameters.dfy.expect, Test/dafny0/TypeParameters.dfy, Test/dafny0/TypeParameters.dfy.expect
Previously, the translation to Boogie used the formal type parameters of the
callee when checking the frame in callers.
=> Substitute actual type args in modifies clause of callee

Source/Dafny/Compiler-Csharp.cs
This allows Dafny codebases to specify tests in a convenient and natural way. It currently assumes that actually running the tests is left up to a tool in the target language (in this case Xunit), which (at least initially) relieves Dafny from having to implement discovery, test runners, reports, etc. 
This is an early PR for initial feedback. I'm working on adding explicit lit "testing tests" to show examples of Dafny tests and Xunit output for them.
Known TODOs and open questions to address before merging:
- Reject programs that use {:test} incorrectly before attempting to compile them (must be "static", must return a "result type", etc.)
- Explicitly report the lack of support in the other target languages
- Add lit tests (once I work out a clean way of having them depend on Xunit)
- …
=> Add support for {:test} attribute (C# only for now)

Source/Dafny/Translator.cs, Test/git-issues/git-issue-443.dfy, Test/git-issues/git-issue-443.dfy.expect
Previously, the `Substitute` routines in `Translator.cs` did not produce resolved `LocalVariable` nodes.
Now, their `.type` field is filled in from the `.OptionalType` field. Moreover, the resulting local variable
is added to the substitution map.
Fixes #443
=> Copy local-variable type in Substitute routine

buildspec.yml
Recent changes broke the git-issue223.transcript test case. To work around this and make builds more reproducible, make the build clone a specific release. We can’t depend on the existing nuget Boogie artifact because it only exposes a CLI tool interface.
Fixes #476
=> Lock down Boogie release, avoid recent regression

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Parser.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/Comprehensions.dfy.expect, Test/dafny0/Comprehensions.dfy, Test/dafny0/Comprehensions.dfy.expect
Previously, `seq(n, init)` would always infer the element type of the constructed sequence.
Now, it can also be given explicitly by `seq<T>(n, init)`.
=> Allow explicit type argument to seq comprehension

Source/Dafny/Reporting.cs, Test/git-issues/git-issue-484.dfy, Test/git-issues/git-issue-484.dfy.expect
Previously, any error/warning/info message for the two kinds of source-location tokens
AutoGeneratedToken and ForceCheckToken were suppressed.
Fixes #484.
=> Report errors for all WrappedToken locations

Source/Dafny/Resolver.cs, Test/dafny0/AutoContracts.dfy.expect, Test/dafny0/Bitvectors.dfy.expect, Test/dafny0/BitvectorsMore.dfy.expect, Test/dafny0/ModuleInsertion.dfy.expect, Test/dafny0/PrefixTypeSubst.dfy.expect, Test/dafny0/TypeConstraints.dfy.expect, Test/dafny0/TypeConversions.dfy.expect, Test/dafny0/TypeConversionsCompile.dfy.expect, Test/dafny2/CalcDefaultMainOperator.dfy.expect, Test/dafny4/Regression20.dfy, Test/dafny4/Regression20.dfy.expect, Test/dafny4/git-issue228.dfy.expect
The name "bv" was used internally in a lookup table with built-in types.
This caused a crash if the identifier was actually used in a program.
=> Fix crash when using `bv` as type in top-level module

Source/Dafny/DafnyPipeline.csproj
nuget seems to download versions of dlls into directories named after what the nuspec supports and not what the packages.config file requests.
Verified on Rustan’s machine :)
=> fix: Mono.Cecil path needs to be net40, not net45

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/DirtyLoops.dfy.expect, Test/dafny0/DirtyLoops.dfy, Test/dafny0/DirtyLoops.dfy.expect
Syntactically, Dafny has allowed `while` loops without bodies. This PR
adds verification support for such loops. Specifically:
Compute loop targets as those free mutable variables (including the
heap) that occur in the guard, invariant, or decreases clause. If the
loop has a modifies clause--whatever the modifies clause says--then
the heap is counted as a free loop target.
Verify context of body-less loop based on loop specification and
the computed loop targets.
Change loop-target hovertext to be part of the "no body" warning.
fix: body-less loops are not always ghost.
fix: `unchanged` expressions use the current heap.
=> feat: Body-less loops

Binaries/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.cs
Although C# 7.0 has been out for a year, something goes wrong on some machines when
Dafny calls the C# compiler to compile the C# code it generates. The problem has been
detected on a Windows machine running Visual Studio 2019 Community. The simple fix
is to remove the one use of a C# 7 feature, which appeared in DafnyRuntime.cs. We'll have
to find a better fix when we want to start using more new C# features, but for now, this is
an improvement.
=> fix: Don't rely on C# 7.0 feature in Dafny run time

Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler.cs
Fix a compile-time warning where a method override mentioned a CodeContracts precondition.
Fix two run-time errors caused by failing CodeContracts, where bad parameter values were supplied.
This shows CodeContracts is beneficial. Alas, the only CodeContracts support we have these days
is on Windows.
=> fix: CodeContract failures

.gitignore, Directory.Build.props
There is a known issue with using both old and new build systems in the same intermediate output directory: https://github.com/NuGet/Home/issues/5126
Note if you are affected by this and getting the “Your project is not referencing the ".NETFramework,Version=v4.0" framework.” error, you need to not only apply this patch but also manually delete the affected obj/ directory. MSBuild/dotnet does not clean the file at fault automatically (project.json).
=> fix: Relocate NetCore build files to obj_core

Source/Dafny/Compiler.cs, Test/DafnyTests/TestAttribute.dfy, Test/DafnyTests/TestAttribute.dfy.expect, Test/exceptions/TestAttributeErrors.dfy, Test/exceptions/TestAttributeErrors.dfy.expect
Without these errors, it’s easy to define test functions that are never run.
Also refactored TestAttribute.dfy to use the existing shared outcome datatype.
=> fix: Non-method functions can’t use {:test}

Source/Dafny/Compiler-java.cs
Compiling the sources all at once is far more efficient than one at a time (the
unit tests now run noticeably faster).
=> Java: Use a single javac command line; support spaces in dir name

Source/Dafny/Translator.cs, Test/git-issues/git-issue-384.dfy, Test/git-issues/git-issue-384.dfy.expect
This fix is for /allocated:2.
Fixes #384
=> fix: Don't add alloc assumption for constructor's receiver

Test/VerifyThis2015/Problem1.dfy
Recently, a change in Boogie and a change in Dafny both caused a proof in Test/VerifyThis2015/Problem1.dfy to fail.
The more detailed proof here made it more robust for the change in Boogie, and perhaps the same holds for the
change in Dafny.
=> Add details to proof in Problem1 test

Source/Dafny/Compiler-java.cs, Test/comp/NativeNumbers.dfy
Casting a literal to a native type is optimized to simply output the literal
differently, but the logic to output the cast literal wasn't shared with the
logic that normally outputs a literal, so corner cases were neglected.
In particular, the expression `0xffff_ffff_ffff_ffff as uint64` (given the
obvious definition of `uint64`) caused a Java syntax error because it's above
Java's maximum long (which is always signed).
=> Java: Fix explicit cast of literal to native type

Source/Dafny/Translator.cs, Test/allocated1/dafny0/LetExpr.dfy.expect, Test/dafny0/LetExpr.dfy, Test/dafny0/LetExpr.dfy.expect
If the translation of `R` in the let expression `var x := R; Body` has the form `Lit(...)`, then
for the purpose of lit-lifting, occurrences of `x` in `Body` are now treated as if they had
the form `Lit(...)`.
=> Treat let-var as Lit if its RHS is Lit

Test/allocated1/dafny0/fun-with-slices.dfy, Test/dafny0/fun-with-slices.dfy
Make the fun-with-slices test look the same in Test/dafny0 and Test/allocated1/dafny0.dfy.
Hopefully improve the stability of this test, on which the verifier has been a bit flakey.
=> fix: Stabilize test cases

Source/Dafny/Resolver.cs, Test/exceptions/GenericOutcomeDt.dfy, Test/exceptions/GenericOutcomeDt.dfy.expect, Test/expectations/ExpectAndExceptions.dfy
See Test/expect/ExceptAndExceptions.dfy for details.
=> fix: Don’t call PropagateFailure() in assign-or-halt

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/DafnyOptions.cs, Source/Dafny/Resolver.cs, Test/comp/Numbers.dfy, Test/dafny0/NativeTypeResolution.dfy, Test/dafny0/NativeTypeResolution.dfy.expect
Support `{:nativeType XX}` where `XX` is a list of native types. The first of
these that the target compiler supports is picked. For additional details,
see the `/attrHelp` message.
Don't pretend to support `number` outside JavaScript. Previously,
`{:nativeType "number"}` worked for a multi-target compilation, but it
does not any more. Instead, use the new attribute
`{:nativeType "number", "long"}`, which does what the previous one
did.
=> feat: Allow list of nativeType choices

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Parser.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs
`reveal` expressions had their own AST node, which was redundant and buggy
(in particular, the parser previously alllowed a `reveal` expression that wasn't followed
by an actual expression, and this caused the resolver to keel over).
This has been fixed to instead use a RevealStmt inside a StmtExpr.
=> fix: Remove RevealExpr

Source/Dafny/Resolver.cs
A recent PR fixed this for methods. This one fixes it also for functions.
=> fix: Introduce tail-call structure only when needed

Test/comp/GoModule.dfy.expect
Go's url module changed the format of its output from Go version 1.11 to 1.14.
This PR reflects that change in the Dafny test suite.
=> chore: Update test output in accordance with latest Go version

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/exports/DatatypeExport.dfy.expect, Test/exports/ExportErrorLocations.dfy, Test/exports/ExportErrorLocations.dfy.expect, Test/exports/ExportResolve.dfy, Test/exports/ExportResolve.dfy.expect
Previously, only members of traits and classes could be mentioned in export declarations
=> fix: Allow exports of members of general types

Source/Dafny/Resolver.cs, Test/exports/ExportResolve.dfy
Previously, prefix predicates and prefix lemmas could be exported only be export-revealing the extreme predicate/lemma.
=> fix: Export-provide prefix predicates/lemmas

.github/workflows/msbuild.yml, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyDriver/app.config, Source/DafnyRuntime/DafnyRuntime.csproj, Source/DafnyRuntime/packages.config, Source/DafnyServer/App.config, Source/DafnyServer/DafnyServer.csproj
Attempting to fix the SSL handshake issues that are experienced by mono is msbuild.
The following changes were attempted...
1. I updated the system certs per fsprojects Paket issues 3009 This adds a few more certs and also updates mono certs. Mono has it’s own certs, I believe
2. Per https://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync I re-synced mono certs with system certs
3. Per  fsprojects Paket issues 3009 and others, I tried using ENV MONO_TLS_PROVIDER=legacy Eventually, I realized I *was* passing the env var correctly (tried a few variations) but mono removed legacy support in  https://github.com/mono/mono/pull/17391 and made legacy = default = boring tls (so that solution won’t work anymore)
4. Tried getting msbuild via action (this didn’t make sense anyways, …
=> Fix: mono SSL handshake issues

Binaries/DafnyPrelude.bpl, Source/Dafny/Translator.cs, Test/git-issues/git-issue-580.dfy, Test/git-issues/git-issue-580.dfy.expect
Like the previous TraitParent, the new relation IsTraitParent isn't actually used for anything, so it's more of a placeholder for some future use.
Fixes #580
=> fix: Make TraitParent a relation, not a function

Source/Dafny/Compiler.cs, Source/Dafny/Resolver.cs, Test/comp/TailRecursion.dfy, Test/comp/TailRecursion.dfy.expect, Test/dafny0/TailCalls.dfy, Test/dafny0/TailCalls.dfy.expect
This fix required fixing 3 things:
Previously, a ghost statement caused a statement list to be considered not-tail-recursive,
even without inspecting the subsequent statements.
Previously, the VarDeclStmt.IsGhost field was set to false whenever the was some initializing
assignments, even if ghost assignments were all ghost statements.
Previously, ghost statements would compile to empty `{ }` blocks, which could cause the Java
compiler to complain about unreachable code.
=> fix: Accept more methods as tail recursive

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Compiler.cs, Source/Dafny/DafnyOptions.cs, Source/DafnyDriver/DafnyDriver.cs, Test/comp/BranchCoverage.dfy, Test/comp/BranchCoverage.dfy.expect, Test/comp/BranchCoverage2.cs, Test/comp/BranchCoverage3.js, Test/comp/BranchCoverage4.go, Test/comp/CodeCoverage.java
Add new command-line option `/coverage:<file>`.
It identifies a set of source locations and gives these distinct numeric identifiers.
The corresponding numbers and source-location descriptions are written to `<file>`.
As for similar command-line options, `<file>` can be `-`, which writes to standard output.
The option also emits into the target compiled code three calls.
* `DafnyProfiling.CodeCoverage.Setup(n)` is called before calling `Main`, where `n` is the number of identified source locations.
* `DafnyProfiling.CodeCoverage.TearDown()` is called upon return from `Main`.
* `DafnyProfiling.CodeCoverage.Record(x)` is called when when the source location numbered `x` is reached, where `0 <= x < n`. This method must always return `true`.
The compiled program should be linked with …
=> feat: Branch-coverage profiling

Test/DafnyTests/DafnyTests.csproj
As a follow up to https://github.com/dafny-lang/dafny/pull/579 another file was found to use the old framework.
=> fix: mono SSL handshake issue, DafnyTests

Source/Dafny/Translator.cs, Test/allocated1/dafny0/DirtyLoops.dfy, Test/allocated1/dafny0/DirtyLoops.dfy.expect, Test/dafny0/DirtyLoops.dfy, Test/dafny0/DirtyLoops.dfy.expect
Without a loop body, we want the effect that the loop specification--that
is, the loop guard, the loop invariant, and the loop frame--says all there
is to say about the loop. Dafny supplies three 3 pieces to Boogie and then
lets Boogie's loop usual processing do the rest. If the guard necessarily
holds initially and this gets noticed by Boogie, then Boogie treats this as
no loop at all. That kind of cleverness is sound, but when demonstrating
the concepts of loop reasoning, it just looks confusing. Therefore, by
this PR, Dafny counteracts this in its Boogie encoding of body-less loop
When the Dafny program supplies a loop body, then Dafny allows Boogie to
be as clever as it wishes, as before PR.
=> fix: Always respect loop spec for body-less loops

Source/Dafny/Compiler.cs, Test/allocated1/dafny0/CompilationErrors.dfy.expect, Test/dafny0/CompilationErrors.dfy, Test/dafny0/CompilationErrors.dfy.expect
Previously, only ghost body-less loops emitted an error. Now, both
compiled and ghost body-less loops do.
=> fix: Emit compile error for body-less loops

Source/Dafny/DafnyOptions.cs, Source/DafnyDriver/DafnyDriver.cs
This PR exposes the Dafny version number via a CLI flag:
```bash
$ ./Binaries/dafny /version
Dafny 2.3.0.10506
```
Resolves #624.
=> feat: add /version CLI flag

Source/DafnyDriver/DafnyDriver.cs
Before:
```bash
$ ./Binaries/dafny /version; echo $?
Dafny 2.3.0.10506
5
$ ./Binaries/dafny /help; echo $?
---- Dafny options ---------------------------------------------------------
Multiple .dfy files supplied on the command line are concatenated into one
Dafny program.
<snip>
Yices2 specific options:
/yices2exe:<path>
path to Yices2 executable
*** Error: No input files were specified.
1
```
After:
```bash
$ ./Binaries/dafny /version; echo $?
Dafny 2.3.0.10506
0
$ ./Binaries/dafny /help; echo $?
---- Dafny options ---------------------------------------------------------
Multiple .dfy files supplied on the command line are concatenated into one
Dafny program.
<snip>
Yices2 specific options:
/yices2exe:<path>
path to Yices2 executable
0
```
To accomplish the above, this PR refactors …
=> fix: exit early with exit status 0 on /version and on /help

Source/Dafny/Dafny.atg, Source/Dafny/Parser.cs, Test/dafny0/AndOrAmbiguity.dfy, Test/dafny0/AndOrAmbiguity.dfy.expect, Test/traits/TraitOverride2.dfy.expect
The operators && and || have the same binding power, but do not associate with other.
The same goes for ==> and <==, and also for &, |, and ^.
Parsing-error messages for these have now been improved.
=> Improve errors for parsing ambiguities of non-associating operators

Source/DafnyDriver/DafnyDriver.cs, Test/git-issues/git-issue-590.dfy, Test/git-issues/git-issue-590.dfy.expect
In several places there are Contracts or code that presume that some dafny file is on the command-line. The simplest fix is to have an early check that this is indeed the case.
=> Fix for issue #590

Test/git-issues/git-issue-343.dfy, Test/git-issues/git-issue-343.dfy.expect
Issue #343 no longer demonstrates a crash. It gives error messages -- added a test for current behavior.
=> Fixes #343: added tests

Test/git-issues/git-issue-351.dfy, Test/git-issues/git-issue-351.dfy.expect
Fixes #351. Fixed in Boogie 2.4.17, likely by https://github.com/boogie-org/boogie/commit/fd500e1acd56ee390a880f859783c2a7a164d9d2
=> Fixes #351. Already fixed in Boogie 2.4.17. Adding test cases.

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/git-issues/git-issue-356-errors.dfy, Test/git-issues/git-issue-356-errors.dfy.expect, Test/git-issues/git-issue-356-errors2.dfy, Test/git-issues/git-issue-356-errors2.dfy.expect, Test/git-issues/git-issue-356.dfy, Test/git-issues/git-issue-356.dfy.expect
Fixes #356. Implemented all combinations of 'as' conversions among { int, char, bv, real, ordinal} in verification and all four compilers, with corresponding verification and run-time tests.
=> #356: Implemented all combinations of 'as' conversions among { int, char, bv, real, ordinal}

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/git-issues/git-issue-289.dfy, Test/git-issues/git-issue-289.dfy.expect, Test/git-issues/git-issue-289b.dfy, Test/git-issues/git-issue-356-errors.dfy, Test/git-issues/git-issue-356-errors.dfy.expect, Test/git-issues/git-issue-356-errors2.dfy, Test/git-issues/git-issue-356-errors2.dfy.expect, Test/git-issues/git-issue-356.dfy, Test/git-issues/git-issue-356.dfy.expect, Test/git-issues/git-issue-505.dfy, Test/git-issues/git-issue-505.dfy.expect
Fixes #505. Not changes to dafny. Current dafny correctly reports timeouts, with a non-zero exit code. Added a test. If the test is found to be non-deterministic, it can be disabled.
=> #505: Timeouts correctly reported

Binaries/DafnyRuntime.go, Binaries/DafnyRuntime.js, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Test/comp/Collections.dfy, Test/comp/Collections.dfy.expect, Test/comp/GoModule.dfy.expect, Test/git-issues/git-issue-258.dfy, Test/git-issues/git-issue-258.dfy.expect
Fixes #258. One remaining infelicity: when Dafny sequences are passed through a generic interface as in method pr<T>(s: seq<T>), then JS and GO cannot tell the element type of an empty string, so empty sequences passed through such an interface will print as [] instead of just nothing, as C# and Java will do.
=> #258: Fixes the printing of strings through Dafny print statements

Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler.cs, Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/comp/CovariantCollections.dfy.expect, Test/traits/TraitCompile.dfy, Test/traits/TraitCompile.dfy.expect, docs/Compilation/Go.md, docs/Compilation/ReferenceTypes.md
Traits were previously encoded in Go as a combination of a `struct` plus an `interface`. This led to several complications (see `docs/Compilation/ReferenceTypes.md`). This PR changes the encoding to use just an `interface`. This removes the complications. This change was made easy since the previous PR #694 had already moved fields from the `struct` to become getters/setters in the `interface`.
This change made the `CovarianceCollections.dfy` tests work for Go. They also corrected some issues with equality tests in Go (the new tests for these revealed a problem in Java compilation, which this PR also fixes).
=> Go traits as just interfaces

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/allocated1/dafny0/Basics.dfy.expect, Test/dafny0/Basics.dfy.expect, Test/git-issues/git-issue-664.dfy, Test/git-issues/git-issue-664.dfy.expect
=> #664: perform wellformedness checks on expressions that are static receivers

Source/version.cs, package.py
Change version to 3.0.0.20817.
Remove DafnyLanguageService.vsix (which had been the Dafny extension for Microsoft Visual Studio).
Bundle Mono.Cecil (also under MIT License).
=> Set up Dafny 3.0.0 pre-release 0

Source/DafnyRuntime/DafnyRuntime.cs
On some machines, when Dafny calls the C# compiler to compile the generated
C# code, the C# compiler only allows C# from several language versions ago.
This commit fixes that by only using C# code that was understood even by that
old version.
=> fix: Revert to generating only old-style C#

Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler.cs, Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/SccGraph.cs, Source/Dafny/Translator.cs
The full run-time CodeContract checking works only on Windows machines, and only if one goes through some steps to install the CodeContract tools. These checks and the code had drift apart. This PR mends that in most places.
Note, CodeContract.Assert and CodeContract.Assume are available on all platforms, but Requires, Ensures, Invariant, and some well-formedness checks are not engaged unless the CodeContract tool is run.
=> fix: Fix Code Contracts

Source/Dafny/Cloner.cs, Test/git-issues/git-issue-425.dfy, Test/git-issues/git-issue-425.dfy.expect
Auto detection of ghost was missing because Cloner.CloneExpr was missing a case for AutoGhostIdentifierExpr.
Fixes #425.
=> #425: adding AutoGhostIdentifierExpr branch in Cloner.CloneExpr

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Translator.cs, Test/dafny0/OpaqueTypeWithMembers.dfy, Test/dafny0/OpaqueTypeWithMembers.dfy.expect, Test/dafny0/ParseErrors.dfy, Test/dafny0/ParseErrors.dfy.expect
Previously, the translation to Boogie of opaque-type members was broken. This PR fixes that.
This address the malformed Boogie shown as an example in #858. However, the main bug reported in that issue (namely, printing "Dafny internal error" when a bug in Dafny causes it to generate malformed Boogie) still needs to be fixed.
=> fix: Verify type members of opaque types

docs/OnlineTutorial/Modules.md
The tutorial previously gave an example that was missing the `abstract` keyword in some module declarations.
=> documentation: Fix missing abstract declarations

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Source/Dafny/Rewriter.cs, Source/Dafny/Translator.cs
Internally, `inductive predicate` and `copredicate` were called "fixpoint predicates",
and `inductive lemma` and `colemma` were called "fixpoint lemmas". This terminology
was inconsistent (sometimes called "extreme predicate/lemma") and can be confusing.
This PR consistently renames all occurrences of such "fixpoint" names to "extreme".
All of the changes in this PR are renamings. There are no logical changes.
=> refactor: Rename "fixpoint" to "extreme" for -predicate and -lemma

Source/Dafny/Dafny.atg
It's been years since Dafny started requiring parentheses in predicate definition, so this old warning is more confusing than helpful to anyone.
=> Remove parser warning

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/exceptions/VerificationErrors.dfy, Test/exceptions/VerificationErrors.dfy.expect, Test/git-issues/git-issue-936.dfy, Test/git-issues/git-issue-936.dfy.expect, docs/_includes/Statements.md
Implemented assert and assume along with expect in :-.
If any of these keywords are present, PropagateFailure is not required and not used.
Instead the desugaring inserts assert !tmp.IsFailure(); etc.
=> #936: Implementing assert and assume in :-

Source/Dafny/Dafny.atg, Source/Dafny/DafnyOptions.cs, Source/Dafny/Resolver.cs, Test/dafny0/RestrictedBoundedPools.dfy, Test/dafny2/MajorityVote.dfy, Test/dafny4/RollYourOwnArrowType.dfy, Test/git-issues/git-issue-181.dfy, Test/git-issues/git-issue-181.dfy.expect, Test/refman/Example-TP.dfy, Test/refman/Example-TP.dfy.expect, docs/_includes/Example-TP.dfy, docs/_includes/Topics.md, docs/_includes/Types.md
Fixes #181. 
Also it appeared that there was no compiler check for !new uses, so added that.
=> #181: Documenting type parameter modes and fixing the check of !new

Binaries/DafnyRuntime.js, Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Compiler-cpp.cs, Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler-js.cs, Source/Dafny/Compiler.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/Tuple2.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/Tuple3.java, Test/comp/AutoInit.dfy, Test/comp/AutoInit.dfy.expect, docs/Compilation/AutoInitialization.md
Previously, the `Default` method in the C# target code for a `datatype` took default (sub-)values as parameters, whereas the other compilers took type descriptors as parameters. This PR changes the other compilers to also pass default values, like the C# compiler had done. This PR also introduces `create_Ctor` methods for `datatype` constructors in Java, which previously had been omitted. All in all, this PR thus makes the compilation of defaults and auto-initialization more uniform across the compilers.
=> Datatype default via values

Source/Dafny/Compiler-java.cs, Test/git-issues/git-issue-953.dfy, Test/git-issues/git-issue-953.dfy.expect
This PR confirms that Issue 953 has been fixed. In doing so, some bugs in the generation of filenames and qualified names in the Java compiler were detected; this PR fixes them.
Closes #953
=> Confirm cyclic-dependency fix and correct Java name issues

Binaries/DafnyPrelude.bpl, Source/Dafny/Dafny.atg, Source/Dafny/Translator.cs, Test/git-issues/git-issue-952.dfy, Test/git-issues/git-issue-952.dfy.expect, docs/_includes/Modules.md
Fixes #952 
A reference type `X.C` obtained via an abstract import `import X : A` is different from a reference type with a name different than `C`, but it may refer to the a type `C` in some other module. Previously, the verifier treated `X.C` as definitely being different than other reference types, which this PR fixes. Interestingly, the verifier has since the introduction of abstract imports (~9 years ago) had proper verification support for the analogous problem of aliasing field names.
=> fix: Distinguish abstractly imported types only via their type family

Source/Dafny/Rewriter.cs, Test/VSComp2010/Problem3-FindZero.dfy, Test/VSComp2010/Problem5-DoubleEndedQueue.dfy, Test/VSI-Benchmarks/b4.dfy, Test/allocated1/dafny0/Twostate-Verification.dfy, Test/allocated1/dafny0/Twostate-Verification.dfy.expect, Test/dafny0/AutoContracts.dfy.expect, Test/dafny0/Twostate-Verification.dfy, Test/dafny1/BinaryTree.dfy, Test/dafny1/ExtensibleArray.dfy, Test/dafny1/ListContents.dfy, Test/dafny1/SeparationLogicList.dfy, Test/dafny2/COST-verif-comp-2011-2-MaxTree-class.dfy, Test/dafny2/MonotonicHeapstate.dfy, Test/dafny2/SnapshotableTrees.dfy, Test/dafny3/Iter.dfy, Test/dafny4/Bug140.dfy, Test/dafny4/FlyingRobots.dfy, Test/traits/TraitExample.dfy, Test/vstte2012/RingBuffer.dfy
The standard dynamic-frames idiom has evolved over the last few years. This PR reflects these changes.
* Many moons ago, a class `constructor` in Dafny started considering `this` as being allocated by the constructor, not the caller. One consequence of this is that the dynamic-frames postcondition
``` dafny
ensures fresh(Repr - {this})
```
on a constructor can be simplified to
``` dafny
ensures fresh(Repr)
```
* It is often useful, especially when modules and hiding are relevant, to include the following postcondition of the `Valid()` predicate:
``` dafny
ensures Valid() ==> this in Repr
```
rather than clients having to get this information from the (possibly inaccessible) body of the `Valid()` predicate.
This PR makes these changes throughout the test suite (except, in some places where …
=> Update dynamic frames idiom

Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/exports/ExportImport.dfy, Test/exports/ExportImport.dfy.expect, Test/git-issues/git-issue-327.dfy, Test/git-issues/git-issue-327.dfy.expect, Test/git-issues/git-issue-327a.dfy, Test/git-issues/git-issue-327a.dfy.expect, Test/git-issues/git-issue-327cir.dfy, Test/git-issues/git-issue-327cir.dfy.expect, Test/git-issues/git-issue-327cir1.dfy, Test/git-issues/git-issue-327cir1.dfy.expect, Test/git-issues/git-issue-327cir2.dfy, Test/git-issues/git-issue-327cir2.dfy.expect, Test/git-issues/git-issue-327cir3.dfy, Test/git-issues/git-issue-327cir3.dfy.expect, Test/git-issues/git-issue-327err.dfy, Test/git-issues/git-issue-327err.dfy.expect, Test/git-issues/git-issue-371-errors2.dfy, Test/git-issues/git-issue-371-errors2.dfy.expect, Test/git-issues/git-issue-659.dfy, Test/git-issues/git-issue-659.dfy.expect, Test/git-issues/git-issue-659b.dfy, Test/git-issues/git-issue-659b.dfy.expect, Test/git-issues/git-issue-659e.dfy, Test/git-issues/git-issue-659e.dfy.expect, package.py
Fixes #327, #659
Fixes the logic for resolving a qualified name for a module.
Does not requires 'import A' before 'import A.B'
Implements export sets for qualified names: import Z = A.B.C`{X,Y}
=> #327, #659: Fixing module name lookup in refines parent

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/exports/OpenImportRefined.dfy, Test/exports/OpenImportRefined.dfy.expect, Test/git-issues/git-issue-151.dfy, Test/git-issues/git-issue-151.dfy.expect, Test/git-issues/git-issue-151b.dfy, Test/git-issues/git-issue-151b.dfy.expect, Test/git-issues/git-issue-328.dfy, Test/git-issues/git-issue-328.dfy.expect
Allows use of imported types that are imported through multiple paths if they are the "same" type; also gives locally defined types preference over imports.
Fixes #151, #328.
=> #151, #328: Fixes to ambiguity of imported types

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-151.dfy, Test/git-issues/git-issue-151.dfy.expect, Test/git-issues/git-issue-151b.dfy, Test/git-issues/git-issue-151b.dfy.expect, Test/git-issues/git-issue-328.dfy, Test/git-issues/git-issue-328.dfy.expect, Test/git-issues/git-issue-864z1.dfy.expect
Types, modules or other entities imported through more than one import statement from a common ancestor are no longer considered ambiguous.
Fixes #151 
Fixes #328
This reverts commit d627cbcded9ba759d85386efafb7c3658724c532.
=> #151, #328: Matching declarations are not considered ambiguous

Source/Dafny/Dafny.atg
The reference manual contained TODO notes recommending
a) more uniform permitting { Attribute } in specification clauses
b) reducing the number of non-terminals accordingly.
This small PR implements those changes. The effect is that attributes are now allowed in places where they were not before, and will be, at present, ignored there.
=> Simplifying the grammar, per TODO notes in the reference manual

Test/lit.site.cfg
Currently we have one test that exercises the Dafny option to configure a custom solver. The test uses the same solver as Dafny is using to run the tests, but to find the path of this solver we're forced to do some guesswork.
I think this PR solves the issue, but I'm not very happy with the solution since it's fragile. For example, if we would bundle the solver Dafny uses inside the Dafny release executable, then `git-issue-401` would fail again. More robust alternatives I see are:
- Let the test download a solver. This seems wasteful since package.py is also downloading a solver, but I think that's OK. The biggest problem I see is that the test then becomes dependent on having an internet connection. We could have a single solver download script that both the test and package.py use …
=> Correctly set the z3 lit variable so git-issue-401 passes locally

Source/Dafny/Resolver.cs, Test/dafny0/TypeInstantiations.dfy.expect, Test/dafny0/UserSpecifiedTypeParameters.dfy.expect, Test/git-issues/git-issue-968.dfy, Test/git-issues/git-issue-968.dfy.expect, Test/git-issues/git-issue-968a.dfy, Test/git-issues/git-issue-968a.dfy.expect
The problem was detecting underspecified RHS when the underspecification did not affect the LHS.
Fixes #968.
=> #968: Fixes a missing error message

Source/Dafny/Translator.cs, Test/allocated1/dafny0/Termination.dfy.expect, Test/dafny0/Termination.dfy, Test/dafny0/Termination.dfy.expect
This PR fixes some problems with termination checking where the type involved is one that has no non-trivial well-founded relation.
For an expression `E` occurring in a `decreases` clause, the Dafny implementation defines 3 relations: equals (`==)`, less (`<`), and at most (`<=`). The first of these is equality for the type. The last of these is the disjunction of the first two, but is represented differently in the implementation, because some types have a more efficient representation of "at most" than combining "equals" and "less" with an "or".
Dafny pre-defines a well-founded relation for every type. It corresponds to the "less" relation I just mentioned. For some cases, like infinite sets, Dafny only defines a trivial well-founded relation, namely `false`. But even in those cases, it …
=> Fix termination check for infinite/unknown types

Source/Dafny/Compiler-java.cs, Source/DafnyRuntime/DafnyRuntimeJava/build.gradle, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/DafnyMap.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/DafnyMultiset.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/DafnySequence.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/DafnySet.java, Source/DafnyRuntime/DafnyRuntimeJava/src/test/java/dafny/MapTest.java, Source/DafnyRuntime/DafnyRuntimeJava/src/test/java/dafny/SetTest.java, Source/DafnyRuntime/DafnyRuntimeJava/src/test/java/dafny/TupleTest.java
* The previous `DafnyMap` class in the runtime for Java implemented Java’s `Map` interface. However, the mutable methods of the `Map` interface don’t go with the immutable nature of `DafnyMap`. Therefore, the ties with `Map` are hereby severed.
* The names of some methods in `DafnyMap` had the prefix `dafny` (to avoid confusion with the inherited methods from `Map`). These have now been renamed.
* Suppress warnings about unchecked casts.
* Fix some deprecated syntax.
* Leave `-Xlint:unchecked` on in `gradle.build`.
=> Java runtime clean-up

Source/Dafny/Translator.cs, Test/dafny0/GhostAutoInit.dfy, Test/dafny0/GhostAutoInit.dfy.expect
Whether or not a variable is subject to definite-assignment checking depends on the type of the variable as well as on whether the variable compiled or ghost. This was previously not done correctly for out-parameters of ghost methods. This PR fixes that. It also adds tests for other kinds of variables that are to be considered ghosts.
=> Treat ghost-method out-parameters as ghosts

Source/Dafny/Compiler-Csharp.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Printer.cs, Source/Dafny/Translator.cs, Test/dafny0/GhostAutoInit.dfy, Test/dafny0/GhostAutoInit.dfy.expect
Depends on PR https://github.com/dafny-lang/dafny/pull/1065
A subset type or `newtype` now supports the following witness clauses:
* `witness E` says that `E` is a compiled expression that is a value of the type
* the absence of a `witness` defaults to
- `witness 0` for types based on integers or bitvectors,
- `witness 0.0` for real-based types,
- `witness {}` for set-based types,
- etc.
* `ghost witness E` says that `E` is a ghost expression that is a value of the type
* `witness *` opts out of witness checking; instead, the type is treated as being possibly empty
=> feat: Opt-out witness for possibly empty types

Source/Dafny/Resolver.cs, Test/allocated1/dafny0/TypeSynonyms.dfy.expect, Test/dafny0/EqualityTypesModuleExports.dfy, Test/dafny0/EqualityTypesModuleExports.dfy.expect, Test/dafny0/TypeSynonyms.dfy, Test/dafny0/TypeSynonyms.dfy.expect
Previously, any explicit type characteristics (except equality-support) of a type synonym or opaque type was not being checked. For example,
``` dafny
type Empty = x: int | false witness *
type Synonym(0) = Empty  // error
```
should result in an error, because `Synonym` claims to support auto-initialization, but its RHS type does not. This PR adds this checking.
=> fix: Check type-synonym type-characteristics to be accurate

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-623.dfy, Test/git-issues/git-issue-623.dfy.expect
This PR fixes a type inference issue reported in #150 and #623. The PR is a replacement for PR #971.
Fixes #150 
Fixes #623 
Closes #971 
A module with an export set is resolved twice. The first time (call it the _yardstick resolution_) considers all declarations in the module. The second time (call it the _export-set resolution_) considers only those declarations that are exported. Suppose the module declares a type synonym
``` dafny
type Public = Internal
```
where the name `Public` is exported and the name `Internal` is not, and suppose that the export-set resolution infers the type of a variable `x` to be `Public`. Then, the yardstick resolution may infer either type `Public` or type `Internal` for `x` -- either will work, since one of the types is a synonym for the other.
A client …
=> fix: Keep type synonyms in some special cases

Test/dafny0/IteratorResolution.dfy, Test/dafny0/IteratorResolution.dfy.expect, Test/dafny0/ResolutionErrors.dfy
Internally, the name of an anonymous class (or iterator) constructor is `_ctor`. Although this name can be used, it is not intended to be used in programs (not only is it uglier and more cryptic in the program text, but this internal name may also change to something else in the future). Thus, it also seems appropriate not to use this name in the test suite.
=> Remove use of _ctor

Source/Directory.Build.props, Test/server/counterexample.transcript, Test/server/counterexample.transcript.expect, Test/server/git-issue223.transcript, Test/server/git-issue223.transcript.expect
This fixes model generation.
Note, previously (before the period of time when Boogie model generation was broken for DafnyServer), when the SMT solver didn't associate any value with a variable `x`, the model coming back from Boogie would record the symbolic value `**x` for `x`. This has changed in Boogie. Now, if the SMT solver doesn't associate a value with `x`, the model coming back will not have any mapping for `x`. So, a tool (like the VS Code plug-in for Dafny) that uses the model should be prepared for the case when a Dafny program variable is not part of the mapping in the model.
=> Use Boogie v2.8.26

Scripts/allow_on_mac.sh
`$SOURCE` doesn't actually work for me on macOS 11.1, but `$BASH_SOURCE[0]` should be cross-platform. I also fixed a couple warnings flagged by shellcheck to make the script more robust.
`./*.dylib` might look a bit funny; it's to prevent a file that starts with `-` from becoming an option for `xattr`.
=> fix: Use correct env var in allow_on_mac.sh

Source/Dafny/Compiler-java.cs, Test/comp/Collections.dfy, Test/git-issues/git-issue-1105.dfy, Test/git-issues/git-issue-1105.dfy.expect
This PR fixes two bugs in the compilation of datatypes to Java. Both problems manifested when a datatype has a constructor with 1 or more ghost parameters, but no compiled parameters. In this case, two Java constructors were generated for the class, and the `equals` method did a `return;` without a value.
Fixes #1105
=> fix: No second constructor, correct equals

Source/Dafny/Compiler-go.cs, Source/Dafny/Compiler-java.cs, Source/Dafny/Compiler.cs, Test/comp/Collections.dfy, Test/comp/Collections.dfy.expect
This PR fixes an issue in the compilation of map update for Go.
For a map `m: map<uint32, X>`, where `uint32` is a native integer type, the expression `m[1 as uint32 := x]` was previously compiled, essentially, as `m[1 as int := x]`. This caused the equality on keys to fail, since such a comparison would be between any existing key `1 as uint32` and the new key `1 as int`.
=> Fix map update go

Source/Dafny/Compiler-java.cs, Test/comp/Arrays.dfy, Test/comp/Arrays.dfy.expect
This PR fixes a crash in the Java compiler. The bug arose in the compilation of expression `b[..]` where the type of `b` is a type synonym that expands to an array type.
=> fix: Expand type synonym for arrays in Java

Scripts/dafny-server
If run from the base Dafny directory (e.g., as `dafny $ ./Scripts/dafny-server`), the current version of the script calculates the wrong location for the Dafny server executable.  In particular, it thinks that `DAFNY_ROOT` is `dafny/Scripts`, and so it looks for the executable in the `Scripts` directory, which fails.  This patch emulates the calculation done in the `dafny/Scripts/dafny` bash script, so that the server is located correctly.
=> Fix directory calculations in dafny-server bash script

Source/Dafny/Compiler-cpp.cs
The `-Wno-deprecated-copy` flag is apparently not recognized by `g++` on the Mac. Adding `-Wno-unknown-warning-option` suppresses the warning about the unknown warning.
This PR attempts to fix the test-suite break introduced in PR https://github.com/dafny-lang/dafny/pull/1115, which I merged too hastily.
=> Add -Wno-unknown-warning-option

Source/Dafny/Resolver.cs, Test/dafny0/Deprecation.dfy, Test/dafny0/Deprecation.dfy.expect
Previously, the deprecated syntax `int(expr)` was removed. The deprecated syntax `NT(expr)`, where `NT` is the name of a `newtype`, should have been removed as well. This PR removes support for that old syntax.
The supported way to convert a value from one type to another uses `as`. The two expressions mentioned above are written `expr as int` and `expr as NT`.
=> Remove code for deprecated type-conversion feature

.github/workflows/msbuild.yml, .github/workflows/release-downloads.yml, Scripts/package.py
The purpose of this change is to reduce the number of github API requests done with each Pull Request. Since github throttles such API requests, Dafny CI builds often fail. The `release-downloads.yml` tests call the github API and don’t seem necessary unless there’s a new release. Therefore, this seems like a simple fix to an annoying problem. (This change can, of course, be reverted if we authenticate the API requests—which does not count against the throttling limit—or see the need to have more frequent release tests again.)
Co-authored-by: @keyboardDrummer
=> Trigger release-downloads only on releases

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs, Test/dafny0/Constant.dfy, Test/dafny0/ResolutionErrors.dfy, Test/dafny0/ResolutionErrors.dfy.expect, Test/git-issues/git-issue-1148.dfy, Test/git-issues/git-issue-1148.dfy.expect, Test/git-issues/git-issue-615.dfy, Test/git-issues/git-issue-615.dfy.expect, Test/traits/TraitResolution1.dfy
Previously, only non-ghost fields in classes and traits were checked to have proper initialization. Now, all (ghost and non-ghost) const/var fields (in all types that can have members) are checked.
Fixes #1148
=> Check all var/const fields to have initial values

Source/Dafny/Translator.cs, Source/DafnyRuntime/DafnyRuntime.cs, Test/git-issues/git-issue-1143.dfy, Test/git-issues/git-issue-1143.dfy.expect
This PR removes some unintended differences between receiver parameters and ordinary parameters. In particular:
* Emit `IsAlloc` assumption for receivers
* Consider receivers when `Lit`-wrapping
* Don't let non-reference `this` affect the use of a heap argument
Fixes #1143
=> Member function fixes

Binaries/DafnyRuntime.h, Source/Dafny/Compiler-cpp.cs, Test/c++/maps.dfy.expect, docs/Compilation/Cpp.md
Replace the explicitly specified TupleN classes with a templated class. This makes it possible to support tuples of arbitrary arity in exported C++ code, and reduces the size of the trusted library.
=> Support tuples with arbitrary arity in C++

Source/Dafny/Compiler-Csharp.cs, Test/git-issues/git-issue-1151-concrete.cs, Test/git-issues/git-issue-1151.dfy, Test/git-issues/git-issue-1151.dfy.expect
Emit `default(T)` in C# when needing a placebo value for an `:extern` opaque type `T`. If that placebo value is also an actual value of the type to be represented, then the opaque type can safely be marked with the `(0)` type characteristic.
This solution is specific to C# (which may not be too surprising, since `:extern` tries to connect code in Dafny with code written in some other language). The solution has limitations--it only works for opaque types declared in the same module that needs the default value, and it works only for opaque types that don't take type parameters.
Note, if the extern type is known to be a C# class type, then it would be better for the Dafny program to declare it as an extern class.
Fixes #1151
=> Compile placebo value for extern opaque type in C#

Binaries/DafnyPrelude.bpl, Source/Dafny/Translator.cs, Test/git-issues/git-issue-1158.dfy, Test/git-issues/git-issue-1158.dfy.expect
The previous axiom for `$Is(Map#Glue(…` was unsound, because the third parameter of `Map#Glue` was unconditionally taken to be the type of the constructed map.
Also, the previous version didn’t cause the right thing to happen with boxing/unboxing, which caused some set-equality proofs to not go through.
Fixes #1158
=> Fix Map#Glue encoding of map comprehensions

Source/Dafny/Translator.cs, Source/Dafny/Triggers/TriggersCollector.cs, Test/dafny1/UltraFilter.dfy.expect, Test/dafny4/Bug60.dfy, Test/dafny4/Primes.dfy, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy, Test/triggers/some-terms-do-not-look-like-the-triggers-they-match.dfy.expect
Allow operations like subset, set union, set intersection, and set difference as trigger candidates. This means fewer "no trigger" warnings, which in turn means more stable verifier performance.
It is in principle possible that the new triggers will _cause_ performance problems. This could happen if triggers were indeed selected before and those triggers were sufficient. The new triggers could then cause additional instantiations, which could slow down performance. No such case was detected in the test suite.
=> Add more auto-triggers for collections

docs/Gemfile.lock
To fix vulnerabilities in older versions of kramdown
=> Upgrade to kramdown 2.3.1

Source/Dafny/Dafny.atg, Test/git-issues/git-issue-1172.dfy, Test/git-issues/git-issue-1172.dfy.expect, docs/DafnyRef/Specifications.md
Disallow `decreases *` on ghost methods.
Disallow duplicate `*`s in `decreases` and `reads` clauses.
Fix crash in parsing disallowed `decreases`.
Fixes #1172
=> fix: Tighten up errors around decreases/reads *

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/RefinementTransformer.cs, Test/dafny0/EqualityTypes.dfy.expect, Test/dafny0/Modules0.dfy.expect, Test/dafny0/RefinementErrors.dfy, Test/dafny0/RefinementErrors.dfy.expect, Test/dafny0/TypeInstantiations.dfy, Test/dafny0/TypeInstantiations.dfy.expect, Test/git-issues/git-issue-1180a.dfy, Test/git-issues/git-issue-1180a.dfy.expect, Test/git-issues/git-issue-1180b.dfy, Test/git-issues/git-issue-1180b.dfy.expect, Test/git-issues/git-issue-288.dfy.expect, Test/git-issues/git-issue-852.dfy, Test/git-issues/git-issue-852.dfy.expect, Test/git-issues/git-issue-864.dfy.expect, Test/git-issues/git-issue-981.dfy.expect
Also:
* Add many (but surely not yet all) missing refinement checks.
* Allow refining indication (`...`) for opaque types.
* Check for superfluous refining indications.
* Don’t allow type parameters to be renamed, not even for opaque types.
* Reword some error messages, trying to make them clearer.
Fixes #1180
=> feat: Let any type with member refine its members

Source/Dafny/Compiler.cs, Source/Dafny/Resolver.cs, Test/dafny0/ResolutionErrors.dfy, Test/dafny0/ResolutionErrors.dfy.expect, Test/git-issues/git-issue-1185.dfy, Test/git-issues/git-issue-1185.dfy.expect
Additionally:
fix: computation of ghost determination for let-such-that expressions
Fixes #1185
=> fix: Initialize bound variable of let-such-that with placebo

Source/Dafny/Compiler-cpp.cs, Source/Dafny/Compiler-java.cs, Test/git-issues/git-issue-1129.dfy, Test/git-issues/git-issue-1129.dfy.expect
When Dafny is asked to compile a program, it generates target code and calls an underlying compiler. That underlying compiler may fail, e.g., if there's a bug in Dafny and Dafny ends up generating malformed code, or if the user Dafny program contains `:extern` declarations that don't lead to provided code. In those situations, it seems polite to output any errors generated by the underlying compiler and then exit the Dafny tool.
Previously, Dafny had in some such cases thrown an exception, which caused the Dafny tool to crash. This is not so polite. This PR replaces such exception throwing with the printing of an error message and exiting (without crashing).
Fixes #1129
=> Exit, don't crash, upon underlying compiler failure

Source/Dafny/Compiler-go.cs, Test/comp/manualcompile/lit.local.cfg
The current version of Go (version 1.16 or later) has a module system. The Dafny compiler for Go still produces code in the old Go packages. To make this work, the environment variable `GO111MODULE` has to be set (to `auto` or to `off`). This PR sets it to `auto`.
Fixes #1156
=> Set flag to use Go pre modules

Source/DafnyLanguageServer/nlog.config
The language server uses NLog as its logging provider. During the repository merger, the required *nlog.config* file got lost making the language server unable to start. 
As a workaround, the VSCode extension automatically creates an empty file if it's missing. I prefer to remove this workaround for later releases.
=> Add the missing nlog.config for the Language Server

Source/Dafny/Rewriter.cs, Source/Dafny/Translator.cs, Test/git-issues/git-issue-1224.dfy, Test/git-issues/git-issue-1224.dfy.expect
The internal annotations are used instead of overwriting the original timeLimitMultiplier annotation.  Closes #1224.
I added a test file, but it doesn't directly check for the issue in #1224.  One way to do so would be to diff the result of `/rprint`, but that will make this test very sensitive to any changes to the pretty printer.  I'm open to other suggestions.
=> Fix timeLimitMultiplier by having it generate internal annotations

.github/workflows/msbuild.yml
See https://github.com/dafny-lang/dafny/issues/1238 (which should still be fixed properly)
=> chore(ci): Lock previous version of dotnet 

.github/workflows/msbuild.yml, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyServer/DafnyServer.csproj
This PR attempts to work with new build error [NETSDK1150](https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/5.0/referencing-executable-generates-error) introduced in .NET 5.0.300.
The PR undoes the temporary fix provided in PR #1237 
Fixes #1238
=> Fix build dotnet 5.0.300

Source/Dafny/Translator.cs, Test/git-issues/git-issue-1250.dfy, Test/git-issues/git-issue-1250.dfy.expect, Test/hofs/Naked.dfy, Test/hofs/Naked.dfy.expect
This PR fixes a problem that had caused confusing behavior when trying to work with functions as values. In particular, the problem caused various different occurrences of the same function name to be unequal in the eyes of the verifier.
Fixes #1250
=> fix: Add synonym axiom for function handles

Source/Dafny/Compiler-java.cs
This PR fixes  #1257 by modifying the Java compiler to remove a deprecation warning that breaks some tests when using recent Java versions. I tested it on my system with openjdk version "1.8.0_282".
=> Fix: Build Java integer types using valueOf

Source/Dafny/Translator.cs, Test/allocated1/dafny0/DirtyLoops.dfy.expect, Test/dafny0/DirtyLoops.dfy.expect, Test/git-issues/git-issue-1252.dfy, Test/git-issues/git-issue-1252.dfy.expect
Some well-formedness checks for loop `modifies` clauses and `modify` statements were missing. This PR adds them.
Fixes #1252
=> fix: Check well-formedness of modifies and modify

Binaries/DafnyRuntime.h, Source/Dafny/Compiler-cpp.cs, Test/c++/maps.dfy.expect, Test/lit.site.cfg
I'd like to suggest we re-enable the tests in `Test/c++` as part of the CI, assuming the CI run for this PR succeeds.  That would help catch issues like those fixed in #1233.
=> Proposal to re-enable C++ tests

Source/Dafny/Translator.cs, Test/git-issues/git-issue-1256.dfy, Test/git-issues/git-issue-1256.dfy.expect
=> fix: Account for types of bound variables in let-such-that translation

Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Test/dafny0/ParameterResolution.dfy, Test/dafny0/ParameterResolution.dfy.expect, Test/dafny0/ParseErrors.dfy, Test/dafny0/ParseErrors.dfy.expect, docs/DafnyRef/Expressions.md, docs/DafnyRef/Grammar.md, docs/DafnyRef/Types.md
This PR introduces parameters that must be passed via a name binding, as requested by https://github.com/dafny-lang/dafny/issues/1243. That is, these parameters are not allowed to be passed positionally.
To indicate that a formal parameter is of this form, declare it with the new `nameonly` modifier. This is a new keyword, which makes this PR a breaking change. (But other than the new keyword, this PR is backward compatible.)
=> feat!: Named-only parameters

Source/Dafny/DafnyAst.cs, Source/Dafny/Resolver.cs
Swap the names Join and Meet so joining two types returns a type that contains at least as many elements as the maximum of the elements in each separate type, and meeting two types returns a type that contains at most the minimum of the elements in each separate type.
Consistently swapped the names Join and Meet by finding references with the regex `(\Wjoin[s]?\W)|(\Wmeet[s]?\W)`
=> Swap the names Join and Meet

Source/Dafny/Cloner.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyAst.cs, Source/Dafny/DafnyMain.cs, Source/Dafny/Printer.cs, Source/Dafny/Resolver.cs, Test/dafny0/PrettyPrinting.dfy, Test/dafny0/PrettyPrinting.dfy.expect
Fixes #1280
- Add missing ghost modifier when printing VarDeclStmt
- Rename the property `IsAutoGhost` to `HasGhostModifier` and flip the boolean value. LMK if anyone has concerns.
=> Add missing ghost modifier when printing VarDeclStmt

Source/Dafny/Compiler-java.cs, Test/comp/Arrays.dfy, Test/comp/Arrays.dfy.expect
This specialization of ILvalue represents an lvalue of the form `a[i]` where a is an array of unknown (that is, parameterized) type. The implementation was missing a call to `EndStmt(wr)` and had an unnecessary call to `intValue()`, and the test suite somehow managed to miss exercising this case.
This is a good case study for being able to measure the code coverage of the regression suite, which will be possible to tackle once we a) move to xUnit to drive the tests and b) stop creating separate `dafny` subprocesses for each test.
=> fix: typos in Compiler-java.GenericArrayElementLvalue

Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/Directory.Build.props
Boogie 2.9.3 has corrected support for `:split_here` and support for `:focus`. With this PR, these can be used directly from Dafny. A Dafny PR that makes use of these automatically is coming soon.
=> Use Boogie 2.9.3

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1347.dfy, Test/git-issues/git-issue-1347.dfy.expect
=> fix: Do ambiguity-resolving type-equality test only on visible types

Source/Dafny/Verifier/Translator.cs, Test/dafny0/BitvectorSynonyms.dfy, Test/dafny0/BitvectorSynonyms.dfy.expect
This PR adds synonym functions for the bitvector functions. This means that for every Dafny bitvector operation, like `&` for `bv6`, there will be two Boogie functions and an axiom connecting them:
```
function and_bv6(bv6, bv6) : bv6;
function {:bvbuiltin "bvand"} smt_and_bv6(bv6, bv6) : bv6;
axiom (forall a: bv6, b: bv6 :: { and_bv6(a, b) } and_bv6(a, b) == smt_and_bv6(a, b));
```
Because of the `:bvbuiltin` attribute, Boogie converts the `smt_and_bv6` function into the SMT solver's interpreted `bvand` operation. That can sometimes cause SMT behavior that is unexpected in the eyes of the Dafny user. By having the `and_bv6` as a synonym function, the SMT solver continues treating it as an uninterpreted symbol. Thus, the symbol stays in the SMT solver's e-graph and is at the same time …
=> synonyms for bit vector operations

Source/Dafny/Resolver.cs, Test/git-issues/git-issue-1377.dfy, Test/git-issues/git-issue-1377.dfy.expect
Previously, the type-equality checks for overriding methods/functions ignored type constraints. With this PR, the proper type equality is used.
Note, one can imagine allowing some co-/contra-variance among the parameters in an override. That would indeed be sound, but it may cause complications in compilation, since target languages may have different rules. Therefore, I suggest we continue to insist on type equality in Dafny. If a strong need for co-/contra-variance comes up, we can consider changing the language.
Fixes #1377
=> fix: Check type equality in override signatures

Test/lit.site.cfg
This is a guard against cases where verification of test cases still succeeds but takes far longer, such as the recent reverted #1351. Ideally it can be tightened and made more precise over time, perhaps on a per-file basis.
=> Set default time limit of five minutes per procedure

Source/DafnyDriver/DafnyDriver.cs, Source/DafnyLanguageServer.Test/Various/VerificationNotificationTest.cs, Source/DafnyLanguageServer/DafnyLanguageServer.cs, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs, Source/DafnyLanguageServer/Language/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Language/VerificationResult.cs, Source/DafnyLanguageServer/Language/VerifierOptions.cs, Source/DafnyLanguageServer/README.md
Fix for #1426. I've created the public method `DafnyDriver.IsBoogieVerified` to ensure that the language server and compiler tread verifier results equally.
Additionally, I've added the possibility to set the default verification timeout using the `--verifier:timeout=n` CLI argument. While applying this change I've observed that *DafnyServer* uses a [default timeout of 10](https://github.com/dafny-lang/dafny/blob/a01e754d10ba06f397f35dc87f48ca1e7be1c4a2/Source/DafnyServer/Utilities.cs#L51). Does it make sense to use this default as well within the Language Server?
=> Language Server: Support verification timeouts

Source/DafnyLanguageServer.Test/Various/CounterExampleTest.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs, Source/DafnyLanguageServer/Language/VerifierOptions.cs, Source/DafnyLanguageServer/README.md
This PR enables users to set the number of cores the verifier may use. The implementation deals the value 0 the same as *DafnyServer*: Use half of the available virtual cores.
The new option is `--verifier:cores=0`.
Furthermore, I've revised the documentation for better readability of the available options.
=> Language Server: Add option to set the number of verifier cores

Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Cloner.cs, Source/Dafny/Compilers/Compiler-go.cs, Source/Dafny/Compilers/Compiler-java.cs, Source/Dafny/Compilers/Compiler-js.cs, Source/Dafny/Compilers/Compiler.cs, Source/Dafny/Dafny.atg, Source/Dafny/Resolver.cs, Test/dafny0/NestedPatternsA.dfy, Test/dafny0/NestedPatternsA.dfy.expect, Test/ghost/Comp.dfy, Test/ghost/Comp.dfy.expect
This PR fixes the compilation of ghost-tuple destructors, some other compilation issues for Java, and the parsing/resolution of 1-tuple patterns.
=> fix: Compilation of ghost tuple destructors

Source/DafnyLanguageServer.Test/Various/StabilityTest.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs, Source/DafnyLanguageServer/Language/IDafnyParser.cs, Source/DafnyLanguageServer/Language/IProgramVerifier.cs, Source/DafnyLanguageServer/Language/Symbols/DafnyLangSymbolResolver.cs, Source/DafnyLanguageServer/Language/Symbols/ISymbolResolver.cs, Source/DafnyLanguageServer/Workspace/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
The language server crashes in cases where sources have strongly nested statements with a stack overflow. The Dafny compiler fixed the issue by launching a thread with a sufficiently large stack. This PR adapts the language server to make use of the same mechanism as proposed in #1447.
This issue solves the following issues: #1447, #1213, and https://github.com/dafny-lang/ide-vscode/issues/40
Since we now have a thread that is responsible for document loading, I removed the asynchronous code that is no longer needed.
=> Language Server: Load documents on a dedicated thread

Source/Dafny/DafnyOptions.cs, Source/Dafny/Reporting.cs, Test/dafny0/warnings-as-errors.dfy, Test/dafny0/warnings-as-errors.dfy.expect
It's sometimes useful to be able to fail a CI pipeline on warnings. While there are not many warnings in Dafny, we have a particular use case for failing on `/warnShadowing`.
When trying to create the commit, I ran into an error where pre-commit/dotnet-format asked for .NET 6.0. I now have changed the pre-commit hook to use the local installation of `dotnet-format` as defined in the manifest at https://github.com/dafny-lang/dafny/blob/master/Source/dotnet-tools.json.
Using the local version of `dotnet-format` is suggested in https://github.com/dotnet/format/pull/1352/commits/2d9ee97f1e9723c7b2227d808fd6f367d34f4c51
To run the version from the manifest I had to change the working directory in the pre-commit hook, which I did via `bash -c`. I assume that that doesn't work on Windows.
=> Add /warningsAsErrors

Source/Dafny/Resolver.cs, Test/git-issues/git-issue1495.dfy, Test/git-issues/git-issue1495.dfy.expect
This PR fixes the issue of mentioned in #1495.
The problem came from
this.arg :- assert X
that was translated to 
var tmpObj = this;
....
tmpObj.arg := ...
This translation might make sense if instead of "this" we had another field which might point to another object after X executes (i.e. if X is a method with side effects). However, in the `this` case (or this in parentheses), the object is guaranteed to be the same, so we don't need and should not do this temporary assignment, so that there is no alias of this during initialization of constants.
This PR reproduces the bug for #1495 as well as adds a case that would fail if we did not do the temporary assignment.
=> Fix for issue #1495

docs/OnlineTutorial/guide.md
Fix the duplication in comparison operators (In the document, the `<=` is written twice, instead of an `<=` and an `>=`).
=> Fix what seems to be a typo in getting started guide

Source/Dafny/Compilers/Compiler-cpp.cs, Test/comp/compile1quiet/CompileRunQuietly.dfy, Test/comp/compile1verbose/CompileAndThenRun.dfy, Test/comp/manualcompile/ManualCompile.dfy, Test/comp/manualcompile/lit.local.cfg
PR #680 uncovers some problems with file locations, but fails to address them entirely. Those changes break some tests when run directly with `lit`. This change should provide a more general solution.
=> fix: Location of generated files in C++

Source/DafnyDriver/DafnyDriver.cs, Test/comp/compile1quiet/CompileRunQuietly.dfy, Test/comp/compile1verbose/CompileAndThenRun.dfy
In certain situations (e.g. compiling C# with `/spillTargetCode:0`), no `targetFilename` is generated. Failure to provide one, leads to all artefact being placed in the working directory, not the input file's.
=> fix: missing targetFilename leads to wrong location of generated files

docs/DafnyRef/README.md, docs/OnlineTutorial/guide.md
2 small changes:
1. Removing "</div>" text from the [Dafny online guide](https://dafny-lang.github.io/dafny/OnlineTutorial/guide) (ctrl+F "One caveat of functions is that" to find the errant text.)
2. Correct a typo from "pother" to "other" in the docs/DafnyRef/README.md
**_Before change:_**
**_After change:_**
=> docs: remove HTML text & correct typo

Source/DafnyDriver/DafnyDriver.cs, Source/DafnyPipeline.Test/DafnyPipeline.Test.csproj, Source/DafnyPipeline.Test/RelativePaths.cs
My recent PR #1598 breaks relative paths under certain conditions (e.g. `/spillTargetCode:3`). This one fixes them. Testing this with a lit file is hard, because xUnit and lit have different working directories, so we do it directly in xUnit.
=> fix: relative paths in filename

.github/workflows/msbuild.yml, customBoogie.patch
Change the `customBoogie.patch` file so it expects Boogie in the root of the Dafny repository folder, instead of adjacent to the Dafny repository folder. This makes it simpler to reference to a Boogie submodule, which makes it easier to run the Dafny build server against a custom version of Boogie.
If you still want to let Dafny point to a Boogie folder that's outside of the Dafny repository, then you can use a symlink.
=> Move customBoogie references one level higher

Source/Dafny/Resolver.cs, Test/dafny0/BitvectorResolution.dfy.expect, Test/dafny0/Coinductive.dfy.expect, Test/dafny0/IteratorResolution.dfy.expect, Test/dafny0/ResolutionErrors.dfy.expect, Test/dafny0/TypeTests.dfy.expect, Test/dafny0/UserSpecifiedTypeParameters.dfy.expect, Test/exceptions/TypecheckErrors.dfy.expect, Test/git-issues/git-issue-283g.dfy.expect, Test/git-issues/git-issue-484.dfy.expect, Test/git-issues/git-issue-750.dfy.expect, Test/hofs/ResolveError.dfy.expect
Fixes issue #1648
Before:
```cs
datatype Foo = Foo(nat, x: nat)
function Bar(baz: string): Foo {
Foo(baz, baz) // incorrect type of datatype constructor argument 0 (expected nat, found string)
// incorrect type of datatype constructor argument 1 (expected nat, found string)
}
datatype Foo3 = Foo3(x: nat)
function Bar3(baz: string): Foo3 {
Foo3(baz) // incorrect type of datatype constructor argument (expected nat, found string)
}
```
After:
```cs
datatype Foo = Foo(nat, x: nat)
function Bar(baz: string): Foo {
Foo(baz, baz) // incorrect type of datatype constructor argument 0 (expected nat, found string)
// incorrect type of datatype constructor argument 1 named 'x' (expected nat, found string)
}
datatype Foo3 = Foo3(x: nat)
function Bar3(baz: string): Foo3 {
Foo3(baz) // incorrect type of …
```
=> fix: Better error reporting for type mismatch

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Synchronization/OpenDocumentTest.cs, Source/DafnyLanguageServer.Test/Synchronization/SaveDocumentTest.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs, Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs, Source/DafnyLanguageServer/Workspace/DiagnosticPublisher.cs
Sending a didOpen message to the server produces roughly the following call tree:
└┬─DocumentDatabase.OpenDocumentAsync
└┬─DocumentDatabase.OpenAndVerifyAsync
└┬─DocumentDatabase.LoadAndVerifyAsync
└┬─TextDocumentLoader.VerifyAsync
└┬─TextDocumentLoader.VerifyInternal
└┬─DafnyProgramVerifier.Verify
├┬─DafnyProgramVerifier.VerifyWithBoogie
│└┬─ExecutionEngine.InferAndVerify
│ └┬─ExecutionEngine.VerifyImplementation
│  └─ ExecutionEngine.ProcessErrors
└┬─(Callback) ModelCapturingOutputPrinter.WriteErrorInformation
└┬─DiagnosticErrorReporter.ReportBoogieError
└─ DiagnosticErrorReporter.AddDiagnosticForFile
There can be multiple concurrent calls to `AddDiagnosticForFile`, but the code doesn't protect the datastructures that this function touches from concurrent modifications.  Hence we can …
=> fix(lsp): Fix a concurrency bug in `AddDiagnosticForFile` (Fixes #1651)

Scripts/package.py, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyServer/DafnyServer.csproj, Source/XUnitExtensions/Lit/OutputCheckCommand.cs
Likely a side effects of moving to `net6.0`. The CI build warnings are caused by the fact that `SelfContained` is no longer implied by specifying a runtime. Making it explicit triggers a problem where the `RuntimeIdentifier` is no longer handed down to included projects. Setting the new environment variable works around that.
=> chore: fix warnings

Source/DafnyServer/DafnyServer.csproj
On multiple other branches we're getting the following build errors:
```
/home/runner/.dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.IO.IOException: The process cannot access the file '/home/runner/work/dafny/dafny/dafny/Binaries/net6.0/linux-x64/DafnyServer.deps.json' because it is being used by another process. 
```
and
```
Error: /Users/runner/.dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(550,5): error NETSDK1177: Failed to sign apphost with error code 0: /Users/runner/work/dafny/dafny/dafny/Source/DafnyServer/obj/Release/net6.0/osx-x64/apphost: No such file or directory [/Users/runner/work/dafny/dafny/dafny/Source/DafnyServer/DafnyServer.csproj]
```
Both relate to DafnyServer, and DafnyServer is …
=> Use default output directory for DafnyServer

.github/workflows/release-downloads.yml, .github/workflows/test-report.yml
There are error notifications about failures in the CI. The reports of parse errors `on` should go away.
=> chore: fix test reports

Test/lit.site.cfg
Fixes a regression in the raw `lit` tests introduced in #1540. Not tested on Windows.
=> fix: `lit` has no `%sed`

docs/DafnyRef/Types.md
The documentation previously, and incorrectly, said that subset types can have type members. This PR fixes that.
Fixes #1719
=> fix: docs: Remove TypeMembers from subset types

Source/Dafny/DafnyOptions.cs, Source/DafnyDriver/BoogieXmlConvertor.cs, Source/DafnyDriver/CSVTestLogger.cs, Source/DafnyDriver/DafnyDriver.cs, Test/logger/CSVLogger.dfy
Adds the ability to log proof goal results and timing in CSV format.
Cherry-picked from robin-aws and slightly tweaked.
=> Add CSV logger for test results and timing

Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
I couldn't figure out from the history of the repo why we were passing a no-op resolver instead of null, but passing `errors => { }` instead of `null` hits this code in Boogie: https://github.com/boogie-org/boogie/blob/6251cd8ae3a87866f31d705fe8c30ed57c053dab/Source/ExecutionEngine/ExecutionEngine.cs#L1594-L1609 and hence we don't get a diagnostic.
=> Report timeouts in IDE to fix #1710

Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyLanguageServer.Test/Unit/NewtonsoftConfiguration.cs, Source/DafnyLanguageServer/DafnyLanguageServer.csproj
This will fix #1722  by expliciting the version of Newtonsoft.json in both DafnyDriver and DafnyLanguageServer.
I added a test in DafnyLanguageServer to ensure the two versions are in sync, to prevent further synchronization problems.
=> Fix version of Newtonsoft.Json

Scripts/package.py
The `dotnet publish` command is somewhat flaky for us, which becomes a problem when it's part of 20 required tasks. To avoid a single failure blocking our builds, we will now retry a failed invocation up to two times.
=> chore: Retry failed `dotnet publish`

Source/IntegrationTests/IntegrationTests.csproj
=> chore: Exclude emacs temporary files from tests

RELEASE_NOTES.md, Scripts/package.py
**Problem**
In one fo my last PR, the CI was not able to download Z3 in only 1 of the 15 instances.
This happens regularly (like, 1 time over 5) over an entire CI. Assuming that there are 10 runs every day, I don't want this problem to happen more than once a year.
**Solution**
With 5 tries, this problem will happen only 1 time every 3125, so that should get us covered.
**Original exception**
```
The date in version.cs does not agree with today's date: 40216 vs. 40215
12
The version number in version.cs does not agree with the given version: 0.0.0 vs. 3.4.1
13
Creating release files for release "0.0.0-CI" and internal version information: 3.4.1.40215
14
* Finding and downloading Z3 releases
15
- Getting information about latest release
16
+ Selecting z3-4.8.5-x64-debian-8.11.zip (35.66MB, …
```
=> chore: Try to download Z3 5 times instead of just once

third_party/Coco/src/Coco.csproj
`net5.0` is a "Target Framework Moniker": it can be used in `TargetFramework` but
not `TargetFrameworkVersion`.  This caused errors with some versions of MSBuild
and Omnisharp:
c:\Users\user\git\dafny\third_party\Coco\src\Coco.csproj: Microsoft.Build.Exceptions.InvalidProjectFileException: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NETFramework, net5.0, '', AnyCPU, '', '')" cannot be evaluated. Input string was not in a correct format.  c:\Users\user\.emacs.d\.cache\lsp\omnisharp-roslyn\latest\omnisharp-roslyn\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] …
=> fix: Use correct property to specify target framework in Coco.csproj

RELEASE_NOTES.md, Source/DafnyRuntime/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.csproj
This PR enforces the runtime c# version to be 7.3 for now.
Fixes #1873
I added an explicit versioning for the c# language in the DafnyRuntime.csproj, which detected advanced features and led me to revert those to usual features. That way, we can stay backward compatible longer.
=> Fix: Lower C# runtime version to 7.3

RELEASE_NOTES.md, Source/Dafny/Compilers/Compiler-Csharp.cs, Test/git-issues/git-issue-1714.dfy, Test/git-issues/git-issue-1714.dfy.expect
=> fix(compiler): Add parentheses around C# casts to fix #1714

RELEASE_NOTES.md, Source/DafnyDriver/BoogieXmlConvertor.cs, Source/XUnitExtensions/Lit/OutputCheckCommand.cs, Test/logger/CSVLogger.dfy
Also add support for CHECK-NOT[-L] OutputCheck directives, and use them to add a regression test.
Also address the fact that CHECK-NEXT[-L] directives were never implemented, so their use was silently doing nothing. :(
=> fix: Populate TestResult.ResourceCount for assertion batches

docs/DafnyRef/Expressions.md, docs/DafnyRef/Specifications.md, docs/DafnyRef/Statements.md, docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md
After reviewing carefully #1915 , I figured out we ought to add more descriptions of common assertions that Dafny verifies, especially those that most programmers are used to (i.e. division by zero, object not null) in first position.
This will increase the understanding about what Dafny will check, and can also serve as an entry point to visit relevant sections in the manual.
=> Chore: More assertions explained

Source/Dafny/DafnyOptions.cs
This is a prelude to updating the manual to describe each option. That section is easier to divide into comprehensible sections if the `/help` text is also organized that way.
(Replaces #1806.)
=> Categorize options in /help

Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Resolver.cs, Source/Dafny/Util.cs, Source/Dafny/Verifier/Translator.cs, Source/DafnyServer/SymbolTable.cs, Test/git-issues/git-issue-1984.dfy, Test/git-issues/git-issue-1984.dfy.expect
* Source/Dafny/AST/DafnyAst.cs:
(Declaration.SanitizedName, TypeParameter.SanitizedName,
TupleTypeDecl.SanitizedName, NonglobalVariable.SanitizedName,
LocalVariable.SanitizedName, Formal.SanitizedName):
New property
(ModuleDefinition.SanitizedName):
New property (created by splitting off the non-extern parts of CompileName)
(Declaration.CompileName, ModuleDefinition.CompileName):
Use SanitizedName
(TypeParameter.CompileName, TupleTypeDecl.CompileName,
NonglobalVariable.CompileName, LocalVariable.CompileName):
Alias to SanitizedName
(ModuleExportDecl, ModuleDefinition.VisibilityScope):
Use SanitizedName when creating the VisibilityScope
(ModuleDefinition.FullSanitizedName, DataTypeDecl.FullSanitizedName):
Use SanitizedName, not CompileName
(NonglobalVariable.CompilerizeName):
Rename to …
=> fix: Don't use CompileName outside of the compilers

RELEASE_NOTES.md, Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Verifier/Translator.ExpressionTranslator.cs, Source/Dafny/Verifier/Translator.TrStatement.cs, Source/Dafny/Verifier/Translator.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs
Before (possibly failing assertions are barely visible):
After (assertions are clearly visible)
Although it cannot be seen yet, related positions on postconditions also now cover an entire expression instead of just a token.
This PR:
- Adds a way for expression to expose their start token and their end token
- Offers a way to create a "RangeToken" from any expression that represents the entire range of an expression
- Also changes the tokens we use for Boogie so that they use `RangeToken` if an translator option ``ReportRange` is activated
- activates this option for the language server only for now.
In the translator, the method `GetTok` replaces `.tok` to perform the switch.
After searching for 30 minutes, I didn't find what else to change to get an entire function or method call to be …
=> Feat: Added ranges to expression

RELEASE_NOTES.md, Source/Dafny/Resolver.cs, Source/Dafny/Verifier/Translator.ClassMembers.cs, Source/Dafny/Verifier/Translator.TrStatement.cs, Source/Dafny/Verifier/Translator.cs, Test/dafny1/Induction.dfy, Test/dafny1/Induction.dfy.expect, Test/dafny2/COST-verif-comp-2011-4-FloydCycleDetect.dfy
A lemma like
``` dafny
class C {
lemma MyLemma(x: X)
requires Pre(x)
ensures Post(x)
decreases D(x)
{
}
}
```
should give rise to an induction hypothesis (which is provided by the verifier as an assumption on entry to the lemma's body) of the form
``` dafny
forall this': C, x': X | this'.Pre(x') && this'.D(x') < this.D(x) :: this'.Post(x')
```
Previously, this was generated incorrectly. In particular, the formula `this'.Post(x')` was previously generated as `this.P(x')`. This PR corrects the generated formula.
Fixes #2001
The example given in issue #2001 is included in `Test/dafny1/Induction.dfy`.
=> fix: Substitute for receiver in automatically generated induction hypothesis

.github/workflows/msbuild.yml, Source/Dafny/DafnyPipeline.csproj, Source/Directory.Build.props, customBoogie.patch
Move the Boogie reference from `Directory.Build.props` to `DafnyPipeline.csproj`. 
This reference was picked up by the C# code generated by `tutorial/Simple_compiler/Compiler.dfy`, which would cause build failures after applying `customBoogie.patch` (example failure: https://github.com/dafny-lang/dafny/runs/5990731332?check_suite_focus=true).
=> Move boogie reference

Scripts/package.py, docs/DafnyRef/Types.md
To avoid leaking the compile-time locations of the source files in stack traces, we stop distributing the program database (PDB).
Before:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Dafny.SkeletonStatement.get_SubStatements()+MoveNext() in /Users/fmadge/Documents/dafny/Source/Dafny/AST/DafnyAst.cs:line 8850
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Microsoft.Dafny.ProgramTraverser.Traverse(Statement stmt, String field, Object parent) in /Users/fmadge/Documents/dafny/Source/Dafny/Util.cs:line 747
at …
```
=> chore: Exclude `*.pdb` files from release package

Source/Dafny/DafnyOptions.cs
Per https://github.com/dafny-lang/dafny/issues/2026 :
Previously, the help string for /extractCounterexample would make
mention of certain proverOpt flags that have seemingly since been
removed.  This patch removes mention of them from the help string
(and makes explicit that /mv takes a file path argument).
Fixes #
=> Remove mention of deprecated flags in /extractCounterexample help text

Source/DafnyRuntime/DafnyRuntime.cs
This method calculates the result of a tree of lazily concatenated sequences. Not providing a capacity was functionally correct, but meant the `ImmutableArray<T>.Builder` had to reallocate its internal array and copy values repeatedly as more ranges were added. Since `ConcatSequence` already tracks the total length of the concatenation, we can provide it as the initial capacity for the builder and avoid all these reallocations and copies.
=> fix(performance): Provide capacity for the immutable array builder in ConcatSequence.ComputeElements()

Source/Dafny/Compilers/Compiler-cpp.cs
=> Use the same C++ warning flags on all platforms

RELEASE_NOTES.md, Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Dafny.atg, Source/Dafny/DafnyMain.cs, Source/Dafny/RefinementTransformer.cs, Test/dafny0/Modules0.dfy, Test/git-issues/git-issue-1180a.dfy, Test/git-issues/git-issue-1180a.dfy.expect, Test/git-issues/git-issue-1180b.dfy, Test/git-issues/git-issue-1963a.dfy, Test/git-issues/git-issue-1963a.dfy.expect, Test/git-issues/git-issue-1963b.dfy, Test/git-issues/git-issue-1963b.dfy.expect, Test/git-issues/git-issue-1963c.dfy, Test/git-issues/git-issue-1963c.dfy.expect, Test/git-issues/git-issue-852.dfy
Closes GH-1363, GH-1963.
Here's my understanding of the current refinement situation (trying to prevent similar bugs.  I have put 🆗 for places that I'm decently confident make sense, ❓ when I don't know, 🐛 for known issues, and an additional ✔️ when we checked further with @RustanLeino.
- `ModuleExport`: ellipsis comes before exports 🆗
- `ClassDecl`, `TraitDecl`: ellipsis replaces `extends` 🆗 
- `DatatypeDecl`: ellipsis comes before "|" (`DatatypeMemberDecl`) 🐛
**FIXED, now comes instead of `|` and constructors**
- `ConstantFieldDecl`: ellipsis comes before `:=`  ❓  ✔️ 
- `NewtypeDecl`: ellipsis comes after `=`, before type and subset constraint 🐛
**FIXED, now comes instead of `=`, type, and constraints**
- `SynonymTypeDecl`: ellipsis replaces `=` and definition 🆗 
- `MethodDecl`, …
=> fix: Protect newtypes and datatypes from refinement

docs/OnlineTutorial/guide.md
Changed "one of" to "among" because two things are discussed. Also tried to reword it so that it is clearer
=> docs: Minor wording change

docs/DafnyRef/Expressions.md, docs/DafnyRef/README.md, docs/DafnyRef/Specifications.md
This PR adds a list of ghost expressions that are typically used in "ensures" clause.
I could also put it on "requires" but I have a little belief it's mostly useful on "ensures" clauses, so I put it there.
=> chore: List of ghost expressions

RELEASE_NOTES.md, Source/Dafny/Dafny.atg, Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs, Test/git-issues/git-issue-1682.dfy.expect
Fixes #2078 
`calc{multiset}`  triggers a while loop that will try to get all inner statements, but the while loop is guarded by something that checks if the next element is the start of an expression, which it is (`multiset` can be the start of an expression). However, since it is not a valid expression, it will emit an error, store a dummy expression, and continue without changing the scanner's position.
The problem does not arise with `iset` because that keyword can be used both for set display and set comprehension, so the scanner can continue in any case.
Since there is no multiset comprehension for now, I removed the lookahead code so that now multiset always expects a `(` or a `{` after it, and the scanner can move on in any case.
<small>By submitting this pull request, I confirm …
=> fix: calc of multiset crashes

.github/workflows/msbuild.yml, RELEASE.md
* Replace `skip-deep-tests-check` label with `run-deep-tests` label on PRs. Rather than skip this check and wait to see if you've fixed master, better to run them directly on the PR first.
* Updated `RELEASE.md` to indicate you need to manually trigger `deep-tests.yml` after merging the update to the version. The automation is strict and looks for a run on exactly the commit being tagged, and there isn't a way to trigger a workflow on a past commit, only the tip of a branch. It's possible to make the commit to download different from the one defining the workflow, but `check-deep-tests` would need to be refactored to understand that. …
=> chore: Quick CI refactoring followups

.github/workflows/msbuild.yml
The problem is, that not running `check-deep-tests`, as we do in case of  `run-deep-tests`, keeps us from running the `integration-tests` at all.
=> chore: Enable `run-deep-tests`

Source/Dafny/Verifier/Translator.ClassMembers.cs, Source/Dafny/Verifier/Translator.cs, Test/git-issues/git-issue-2100.dfy, Test/git-issues/git-issue-2100.dfy.expect
Don’t generate functions/axioms about types that are opaque in the scope.
Fixes #2100
=> fix: Treat provided types as opaque

Source/Dafny/DafnyConsolePrinter.cs
I recently got a CI issue in this PR:
https://github.com/dafny-lang/dafny/runs/6355961286?check_suite_focus=true
The error was the following
>Unhandled exception. System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/ShowSnippets.dfy)
---> System.ArgumentException: An item with the same key has already been added. Key: /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/ShowSnippets.dfy
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
at …
=> chore: Fixed a concurrency issue

Source/Dafny/DafnyOptions.cs
Adds documentation for the `{:autoReq}` attribute to the output of `/attrHelp` .
=> Add `/attrHelp` entry for `{:autoReq}`

Source/DafnyDriver/TextLogger.cs
The order of elements in the lists that `/verificationLogger:text` iterates over can vary when using multiple cores. This PR sorts those lists before printing their contents to ensure deterministic output.
=> Sort output of `/verificationLogger:text`

Source/DafnyLanguageServer/Workspace/DiagnosticPublisher.cs, Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs
This small refactoring clarifies what is actually stored in VerificationGutterStatus and what is needed to build it.
=> chore: Better design for building verification gutter status icons

Source/Dafny/DafnyOptions.cs, Source/DafnyTestGeneration/ProgramModification.cs, Test/allocated1/Allocated1.dfy, Test/allocated1/Allocated2.dfy, Test/dafny0/ShowSnippets.dfy, Test/dafny0/snapshots/Snapshots6.run.dfy.expect, Test/dafny0/snapshots/Snapshots7.run.dfy.expect, Test/dafny0/snapshots/Snapshots8.run.dfy, Test/dafny4/git-issue143.transcript.expect, Test/server/counterexample.transcript.expect, Test/server/counterexample_commandline.dfy, Test/server/git-issue223.transcript.expect, Test/server/minimal.transcript.expect, Test/server/simple-session.transcript.expect
Error traces can be a nuisance to customers so it's better to turn them off by default.
=> Change default for errorTrace option so it's off

Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs, Source/DafnyLanguageServer.Test/Various/DiagnosticMigrationTest.cs, Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs
Fixes #2147  which was an untested regression issue (it was working previously)
Added a test that recognized URI scheme used by VSCode.
=> fix: Untitled documents get their verification diagnostics

Source/Dafny/Compilers/Compiler-java.cs
=> fix: Don't deadlock when reading `javac`'s output (fixes #2156)

Source/Dafny/Resolver.cs, Source/Dafny/Verifier/Translator.cs, Test/dafny0/ResolutionErrors.dfy, Test/dafny0/ResolutionErrors.dfy.expect, Test/hofs/ReadsReads.dfy, Test/hofs/ReadsReads.dfy.expect, Test/hofs/Types.dfy, Test/hofs/Types.dfy.expect
This PR fixes two issues with advanced `reads` clauses.
One issue was with `reads F`, where `F` is an expression of type `... ~> seq<object>` or `... ~> multiset<object>`. Previously, these generated malformed Boogie. This is now fixed.
The other issue was with `reads F` where `F` is an expression of type `... ~> object`. Previously, the resolver allowed this, but the translator generated malformed Boogie. There's no strong use case for allowing such a type, so this PR fixes the issue by making the resolver forbid this case.
=> fix: reads function of seq/multiset

Source/Dafny/DafnyPipeline.csproj
If building on Windows with space in the enclosing directory, the -frames option won't work unless the path is in double quotes. This tiny PR fixes that.
=> Support for spaces in the Dafny path

Source/Dafny/MergeOrdered.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyPipeline.Test/MergeOrderedTest.cs
Fixes a bug that would ignore subsequent inner observables after MergeOrdered received an empty inner observable, which in Dafny would cause notifications to stop occurring after saving a file that did not have verify on save turned on.
=> Fix MergeOrdered and empty observable

Source/DafnyLanguageServer/DafnyLanguageServer.csproj
With [this merge](https://github.com/dafny-lang/dafny/commit/51b6885390ed292b479d430a0d1d363e12dbcc0c), `DafnyLanguageServer.dll` was no longer copied to the `Binaries` folder, which resulted in no updates taken into account when testing a custom version of Dafny in VSCode.
This PR fixes this.
=> Hotfix: Copy the DafnyLanguageServer.dll

docs/DafnyRef/Attributes.md, docs/DafnyRef/Types.md, docs/DafnyRef/UserGuide.md
Adds a section to the User's Guide under Compilation, documenting known cases of specific backends not supporting given Dafny features. See dry run on my fork here to verify that the links and footnotes work correctly: https://robin-aws.github.io/dafny/DafnyRef/DafnyRef#2498-supported-features-by-target-language
Partially addresses #1770 - I generated the data for this table by implementing the mechanism described there (or at least a simpler version of it) on [this branch](https://github.com/robin-aws/dafny/tree/compiler-feature-support-matrix), but that implementation is not yet ready, especially since it involves changing the way many if not all integration tests are run. In the meantime, having this information documented is very useful!
<small>By submitting this pull request, I …
=> docs: Add matrix of supported features by target language

RELEASE_NOTES.md, Source/DafnyRuntime/DafnyRuntime.cs, Source/DafnyRuntime/DafnyRuntime.csproj
Fixes #2276
Existing tests should provide good evidence for the functional correctness of this fix. Testing for compatibility with .NET Standard 2.1 should exist, as well, but could arguably come as part of a separate PR that adds similar compatibility tests for the other runtime libraries.
=> Update `BigRational` to be compatible with .NET 2.1

RELEASE_NOTES.md, Source/Dafny/Verifier/Translator.cs, Test/dafny0/LabelsOldAt.dfy, Test/dafny0/LabelsOldAt.dfy.expect, Test/git-issues/git-issue-2301.dfy, Test/git-issues/git-issue-2301.dfy.expect
This PR adds checks that the state of arguments given to `unchanged` are allowed to be read.
Fixes #2301
=> fix: Add reads checks for 'unchanged' arguments

RELEASE_NOTES.md, Source/Dafny/AST/FreeVariablesUtil.cs, Source/Dafny/Substituter.cs, Source/Dafny/Verifier/Translator.cs, Test/git-issues/git-issue-2299.dfy, Test/git-issues/git-issue-2299.dfy.expect
This PR fixes two things related to heap labels. One gave rise to unsound verification, and the other to malformed Boogie code.
Fixes #2299
=> fix: Substitute for heap labels in TrSplitExpr

Source/Dafny/Cloner.cs, Source/Dafny/Resolver.cs, Source/DafnyLanguageServer.Test/Lookup/HoverTest.cs
Fixes #2333
This is a very substantial problem.
The body of a NestedMatchStmt was cloned when resolved, resulting in variables not being resolved in the original tree, which caused the LSP to crash when asking about their hovering information.
I added a test.
=> Fix: No more crashing on hovering bodies of nested match statements 

Source/DafnyRuntime/DafnyRuntime.cs
This patch is needed in Dafny-in-Dafny to print bignums; we could decide to leave it there, too.
=> Expose BigRational.{num,den} in the C# runtime

docs/DafnyRef/UserGuide.md
There's a branch in the dafny-mode repo, but it doesn't support any of our custom additions to the protocol.  I can update it, but I need docs for that.
=> doc: Clarify that our LSP server isn't supported by dafny-mode

.github/workflows/publish-release-reusable.yml
Currently the nightly run is failing because automatically publishing to NuGet is failing because `secrets.NUGET_API_KEY` seems to be empty: https://github.com/dafny-lang/dafny/runs/7228527386?check_suite_focus=true
Note that a secret `NUGET_API_KEY` has been configured for `dafny-lang/dafny`.
Automatically publishing to NuGet has not worked before, so let's comment it out until we get it working
=> Turn off NuGet publish until secrets.NUGET_API_KEY works

.github/workflows/deep-tests.yml
The `publish-release-reusable.yml` workflow isn't careful enough about only building prerelease `*.nupkg` files, and is currently trying to re-publish actuall release packages and failing.
The API key secret issue should still be fixed so I'm only disabling it from the nightly build this time.
=> chore: Disable nuget publishing from nightly build

Source/Dafny/DafnyConsolePrinter.cs, Source/DafnyDriver/BoogieXmlConvertor.cs
The previous implementation was not thread safe, and could occasionally lead to failures during addition. We don’t have a reliable way to reproduce one of these failures, however, so this commit doesn’t add any new tests.
=> Use a concurrent bag for verification results

.github/workflows/publish-release-reusable.yml, .github/workflows/publish-release.yml, docs/dev/RELEASE.md
* Fix documentation for pushing tags
* Have `publish-release` depend on `get-version` so it has a version
* Additional debugging of version numbers during release
=> Release process fixes

RELEASE_NOTES.md, Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Unit/ParserExceptionTest.cs, Source/DafnyLanguageServer/Handlers/DafnyHoverHandler.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Language/DiagnosticErrorReporter.cs, Source/DafnyLanguageServer/Util/PathExtensions.cs, Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs, Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Improvement: instead of "Related location", explicit what these related locations are about:
Fixes https://github.com/dafny-lang/ide-vscode/issues/211
On hovering a postcondition, the main message is now "This postcondition might not hold on a return path". https://github.com/dafny-lang/dafny/pull/2433 takes cares of changing "related location" to "return path".
Fixes https://github.com/dafny-lang/ide-vscode/issues/197 by changing all Uri to string conversion to the standard `Uri.toString() / DocumentUri.Parse()` so that there is no loss of conversion, and we don't assume a valid file name. Except for includes.
Fixes  https://github.com/dafny-lang/ide-vscode/issues/193 by providing which postconditions are failing explicitely
<small>By submitting this pull request, I confirm that my …
=> feat: Better LSP related location error messages

.github/workflows/publish-release-reusable.yml, .github/workflows/publish-release.yml
Works around #2423 for now. We can manually upload NuGet packages until we've figured out why this is happening.
Also fixes one small, non-fatal issue that occurred during the 3.7.2 release.
=> Disable NuGet uploading of releases for now

.github/workflows/publish-release-reusable.yml, .github/workflows/xunit-tests.yml, Source/Dafny/DafnyPipeline.csproj, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyRuntime/DafnyRuntime.csproj, docs/dev/RELEASE.md
* Update release process documentation
* Include license expressions in packages for NuGet, to avoid warnings
* Always upload `.nupkg` files as artifacts, for debugging
=> ci: Build and release process cleanups after 3.7.3

Source/XUnitExtensions/Lit/ILitCommand.cs, Source/XUnitExtensions/Lit/SedCommand.cs, Test/cli/diagnosticsFormats.dfy, Test/cli/diagnosticsFormats.dfy.expect, Test/lit.site.cfg
The Windows build checks out the repo with`\r\n` line endings, which changes the `"pos"` field by 1 unit per line.
=> fix: Strip "pos" field from diagnosticsFormat test

Source/Dafny/Verifier/ProofObligationDescription.cs, Source/Dafny/Verifier/Translator.ClassMembers.cs, Source/Dafny/Verifier/Translator.cs, Test/git-issues/git-issue-2384.dfy, Test/git-issues/git-issue-2384.dfy.expect
The bug was introduced by a typo in 53765c537.  This PR further improves the
message by not mentioning "expressions".
=> fix: Incorrect error message for modifies clause (closes #2384)

Source/Dafny/Dafny.atg, Test/patterns/OrPatterns.dfy, docs/DafnyRef/Expressions.md
=> feat: Allow leading `|` in disjunctive patterns

.github/workflows/publish-release-reusable.yml
My hypothesis is that `dotnet publish` is adding a too-strict runtime version dependency that is then inherited by the created `.nupkg` files.
Attempts to fix #2423, but we won't know for sure until the next nightly build runs.
=> Run `dotnet pack` before `dotnet publish`

.github/workflows/publish-release-reusable.yml, RELEASE_NOTES.md
This reverts commit 1837d64ff4b5fb3d1a3fbcffefd794ae27c48b57.
_Hopefully_ fixes broken nightly publish step: https://github.com/dafny-lang/dafny/runs/7554903871?check_suite_focus=true
=> Revert "Run `dotnet pack` before `dotnet publish` (#2501)"

RELEASE_NOTES.md, Source/Dafny/Verifier/Translator.cs, Test/git-issues/git-issue-2511.dfy, Test/git-issues/git-issue-2511.dfy.expect
Dafny adds a free invariant on each loop that states that the loop variable is
smaller than or equal to its initial value.  For bitvectors, Dafny produced ≥
instead of ≤, possibly due to a typo?
Specifically, the issue was:
- In `Translator.TrStatement.cs` (`TrLoop`):
```
// include a free invariant that says that all completed iterations so far have only decreased the termination metric
…
Bpl.Expr decrCheck = DecreasesCheck(toks, types, types, decrs, initDecr, null, null, true, false);
```
- In `Translator.cs` (`DecreasesCheck`):
```
Bpl.Expr less, atmost, eq;
ComputeLessEq(toks[i], types0[i], types1[i], ee0[i], ee1[i], out less, out atmost, out eq, includeLowerBound);
```
- In `Translator.cs` (`ComputeLessEq`):
```
} else if (ty0 is BitvectorType) {
BitvectorType bv = …
```
=> fix: Use the right bitvector comparison in `ComputeLessEq`

RELEASE_NOTES.md, Source/Dafny/Resolver.cs, Test/git-issues/git-issue-2506.dfy, Test/git-issues/git-issue-2506.dfy.expect
The bug was latent in 923f8120 (for datatypes), but the issue with `const` only
became exploitable in c5562f28 (previous to that Boogie's own cyclicity checks
replaced the missing ones in Dafny).
* `Source/Dafny/Resolver.cs` (`ResolveTopLevelDecls_Core`):
Run member checks on all declarations with members — not just on classes.
Closes #2506.
We were running none of the extreme lemma checks for datatypes, newtypes, and abstract type members.  I added tests, but for casual readers, here are four examples:
```
datatype T = A {
static const a := 1 + b;
static const b := 2 + a;
static predicate F() decreases 0 { !L() }
static least predicate L() { F() }
static least predicate Negative() { !Negative() }
static least predicate Ensures() ensures false { Ensures() }
}
method Oops0() ensures false …
```
=> fix: Check extreme predicates and constants in all types, not just classes

.github/workflows/publish-release-reusable.yml, .github/workflows/publish-release.yml, Source/DafnyRuntime/DafnyRuntime.csproj
The `dotnet publish` process that runs as part of `package.py` adds a too-strict runtime version dependency that is then inherited by the created `.nupkg` files. By building the `.nupkg` files first, we avoid this problem.
I've run the nightly build process manually on this branch, and confirmed that it succeeded and produced `.nupkg` files with the appropriate version constraints.
Fixes #2423
=> Another attempt at building NuGet package first

Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Dafny.atg, Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs, Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Fixes #2533 
For that, I also added EndToken for top-level declarations, and split the Range of VerificationTree into a Range and a token. The token is the one that is used for finding the place of a tree and is included in the range, but it is not its start anymore.
It seems that some tests have changed because of this refactoring but I have no idea why. Their results seem better than before though.
=> Fixed bodyless methods gutter icons

Source/Dafny/AST/DafnyAst.cs, Source/Dafny/Dafny.atg, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Test/git-issues/git-issue-845.dfy.expect, Test/wishlist/we-should-always-print-tooltips.dfy.expect
Don't publish a diagnostics with a negative line and column number when a file is empty
Fixes #2529
=> Don't publish a diagnostics with a negative line and column number

Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Synchronization/VerificationStatusTest.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer/Workspace/CompilationManager.cs, Source/DafnyLanguageServer/Workspace/DocumentObserver.cs, Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
Fix: prevents the LSP client from thinking things are verified when really they're not even resolving.
=> Do not publish verification symbol status for unresolved documents

Source/Dafny/Dafny.atg, Source/Dafny/Resolver.cs, Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs, Source/DafnyLanguageServer.Test/Lookup/DocumentSymbolTest.cs, Source/DafnyLanguageServer.Test/Synchronization/VerificationStatusTest.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer/Workspace/DafnyDocument.cs
1. Consider a function by method as a single verifiable
1. Stop sending duplicate verification status notifications
1. Fix a warning producing piece of code in Dafny.atg
Added tests for 1 and 2.
=> Fix verification status for function by methods, and two other small issues

Source/DafnyLanguageServer.Test/Synchronization/VerificationStatusTest.cs, Source/DafnyLanguageServer/Handlers/Custom/VerificationHandler.cs
Fix document/verifySymbol handler so it works when symbols have multiple tasks
Added test
=> Fix document/verifySymbol handler so it works when symbols have multiple tasks

RELEASE_NOTES.md, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/version.cs, docs/dev/RELEASE.md
Adds a NuGet package for `DafnyLanguageServer`, to make it easier use an IDE with a version of the language server known to match a `dafny` CLI executable installed with NuGet.
=> Build DafnyLanguageServer as a NuGet package

Source/Dafny/DafnyOptions.cs, Source/DafnyDriver/BoogieXmlConvertor.cs, Source/DafnyDriver/CSVTestLogger.cs, Source/DafnyDriver/DafnyDriver.cs, Source/DafnyDriver/VerificationResultConvertor.cs, Source/DafnyDriver/VerificationResultLogger.cs
Now that verification results are aggregated into a data structure returned to Dafny, using Boogie's XML output is no longer necessary.
Fixes #1950
This is a refactoring that should still pass existing tests.
=> Remove the use of Boogie's XML output

RELEASE_NOTES.md, Source/Dafny/Verifier/Translator.BoogieFactory.cs, Test/git-issues/git-issue-2651.dfy, Test/git-issues/git-issue-2651.dfy.expect
Fixes #2651 by adding the token on the converted and expression. Added a test for that.
=> fix: Missing token in translation of proper prefix

RELEASE_NOTES.md, Source/DafnyServer/CounterExampleGeneration/DafnyModel.cs, Test/git-issues/git-issue-2026.dfy, Test/git-issues/git-issue-2026.dfy.expect
=> Fixed error reporting counter example + avoid null pointer exceptions

Source/DafnyLanguageServer/Handlers/Custom/DafnyCounterExampleHandler.cs, Source/DafnyLanguageServer/Workspace/Document.cs, Source/DafnyLanguageServer/Workspace/DocumentManager.cs, Source/DafnyLanguageServer/Workspace/DocumentManagerDatabase.cs, Source/DafnyLanguageServer/Workspace/IdeState.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs, Source/DafnyLanguageServer/Workspace/VerificationProgressReporter.cs
Make the counterExample handler robust against race conditions such as https://github.com/dafny-lang/dafny/runs/8099783944?check_suite_focus=true
=> Make the counterExample handler robust against race conditions

.github/workflows/msbuild.yml, .github/workflows/publish-release-reusable.yml, Source/DafnyRuntime/DafnyRuntime.csproj
This reverts commit 709ed5a2669233195a488dceebda2594ee5eb5e5. (PR #2604)
Resolving the issue that Rider no longer builds:
```
Build started 09/08/2022 10:58:29.
Logging verbosity is set to: Normal.     1>Project "/Users/rwillems/Documents/SourceCode/dafny/Source/DafnyRuntime/DafnyRuntime.csproj" on node 1 (build target(s)).
1>BuildDafnyRuntimeJar:
Compiling DafnyRuntimeJava to DafnyRuntimeJava/build/libs/DafnyRuntime.jar...
./gradlew -q build
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
_CopyOutOfDateSourceItemsToOutputDirectory:
Skipping target …
```
=> Revert "Let `DafnyRuntime` target more frameworks (#2604)"

Source/Dafny/Compilers/Compiler-Csharp.cs, Source/Dafny/Compilers/Compiler-cpp.cs, Source/Dafny/Compilers/Compiler-go.cs, Source/Dafny/Compilers/Compiler-java.cs, Source/Dafny/Compilers/Compiler-js.cs, Source/Dafny/Compilers/Compiler-python.cs, Source/Dafny/Compilers/SinglePassCompiler.cs, Source/Dafny/Feature.cs, Test/comp/Various.dfy, Test/comp/Various.dfy.expect, docs/DafnyRef/Features.md
Removes dead code for compiling constant member variables (not supported) and adds support for named functions for sequence construction.
=> Remove `UnsupportedFeatureException`s in Python

RELEASE_NOTES.md, Source/DafnyCore/Cloner.cs, Test/git-issues/git-issue-1639.dfy, Test/git-issues/git-issue-1639.dfy.expect
Fixes #1639 by changing `AbstractSignatureCloner` to specifically delete only method bodies, instead of all block statements. This avoid breaking AST invariants of  other block statements (e.g. that hints of a `calc` statement are non-null).
=> fix: retain non-method-body block statements when cloning abstract signatures

.github/workflows/xunit-tests.yml, Source/Dafny.sln, customBoogie.patch
The tests for the DafnyRuntime package were inadvertently left out of the top level Dafny.sln, and therefore weren't being run in CI. This adds the test package so that it will run along with all other tests.
=> Add DafnyRuntime.Tests to Dafny.sln

Source/DafnyCore/AST/TopLevelDeclarations.cs
The `FullName` and `FullSanitizedName` properties are now safe to access when the `EnclosingModuleDefinition` property is null.
This will be necessary in order for the [auditor](https://github.com/dafny-lang/compiler-bootstrap/tree/main/src/Tools/Auditor) to run as a plugin inside a released version of Dafny.
=> Allow accessing full name of top-level declaration

Source/DafnyCore/Compilers/Compiler-Csharp.cs
This reverts commit ecd825e5dfcc97a7dd8f8342a014a0c8ed4954de.
The `#nullable enable` annotation is a recent C# feature, so that commit broke compatibility with some client code.
Fixes #2781
=> Revert "feat: Add #nullable disable to generated C# code to avoid warnings (#2444)"

Source/DafnyCore/Compilers/Compiler-Csharp.cs, Source/DafnyCore/Compilers/Compiler-go.cs, Source/DafnyCore/Compilers/Compiler-java.cs, Source/DafnyCore/Compilers/Compiler-js.cs, Source/DafnyCore/Compilers/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Test/git-issues/git-issue-2792.dfy, Test/git-issues/git-issue-2792.dfy.expect
fix #2792
To fix the issue, I added a cast from the type descriptor to the desired type descriptor.
While this does not work in other languages, it might be ok in Java because the only thing we do with this type constructor is to generate an array of size zero with it, and array's generics are erased.
One problem is that this PR, although it fixes a root problem, makes it possible for the compiler to fail if we add the line `xs := xs.(s := xs.s + [1]);`
However, it seems a totally unrelated error so I think this PR is safe to accept.
```
_0_xs = dafny.Helpers.<Wrapper<java.math.BigInteger>, Wrapper<java.math.BigInteger>>Let(_0_xs, _pat_let0_0 -> dafny.Helpers.<Wrapper<java.math.BigIn
teger>, Wrapper<java.math.BigInteger>>Let(_pat_let0_0, _1_dt__update__tmp_h0 -> …
```
=> Fix: Java compiler cannot instantiate generic datatype with seq<T>

RELEASE_NOTES.md, Source/DafnyLanguageServer/Workspace/DocumentManagerDatabase.cs, Source/DafnyLanguageServer/Workspace/DocumentOptions.cs
Fixes https://github.com/dafny-lang/ide-vscode/issues/272
There was a weird totally useless conversion from `List<String>` to `String` and vice-versa, that would split on spaces. I removed the conversion used only in this place and this works as expected.
=> Fix: Support for Z3 solver path with spaces

Source/DafnyCore/DafnyCore.csproj, Source/DafnyServer/DafnyServer.csproj, Test/git-issues/git-issue-2813.dfy
Fixes #2813
`Assembly.GetExecutingAssembly()` returns the assembly containing the current code, NOT the top-level entry point assembly/tool, so `DafnyCore.dll` needs to have the relevant info rather than `Dafny.dll`.
=> fix: GenerateAssemblyInfo in DafnyCore

RELEASE_NOTES.md, Source/DafnyRuntime/DafnyRuntime.js, Test/git-issues/git-issue-2581.dfy, Test/git-issues/git-issue-2581.dfy.expect
=> fix: string-seq equality in JS runtime

Source/DafnyCore/DafnyCore.csproj, Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer/Workspace/TextBuffer.cs, docs/dev/news/2890.fix
This PR removes an optimization to compute the lines based on previous lines, because this transformation has bugs.
Will add tests later
Fixes #2890 
=> Fix: crash in language server optimization

.github/workflows/xunit-tests.yml, Source/DafnyDriver/Commands/CommandRegistry.cs, Source/DafnyDriver/DafnyDriver.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyTestGeneration/BlockBasedModification.cs, Source/DafnyTestGeneration/DafnyTestGeneration.csproj, Source/Directory.Build.props
Let's get rid of those annoying warnings that clutter CI and our build logs.
- Turn off the warning '"Async" suffix required for Task methods' in all projects
- Add some one time warning disable pragma's at sync/async boundaries.
- Turn on treat warnings as errors in CI
=> Turn off Async suffix warning, and treat warnings as errors in CI build

Source/DafnyCore/Compilers/Compiler-java.cs, Test/git-issues/git-issue-2903.dfy, Test/git-issues/git-issue-2903.dfy.expect, docs/dev/news/2904.fix
=> fix(java): unqualified type cast in pattern dtor

.github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml, Scripts/prepare_release.py, docs/dev/RELEASE.md
Clean up a few issues identified in the 3.9.1 release.
* Update release process documentation
* Correct name of release script
* Remove VS Code section since it’s now handled by one bullet in the main section.
* Use `python3` instead of `python`
* Install `bignumber.js` earlier in quick tests
* Allow prerelease dependencies when testing NuGet
=> Post 3.9.1 cleanup

.github/workflows/integration-tests-reusable.yml, Test/README.md
Our CI logs are often over 5000 lines long; do we actually need all that output?  Most of it is `Copying … to …`
=> Reduce verbosity of test logs

Source/DafnyCore/Compilers/SinglePassCompiler.cs, Test/git-issues/git-issue-2608.dfy, Test/git-issues/git-issue-2608.dfy.expect, docs/dev/news/2608.fix
This PR fixes #2608 and fixes #2576
Here is the story. Whenever there is a label `L1` to a statement `S`, the JavaScript compiler wraps the statement with curly braces `{}` and put the label in front of it, like this:
```
L1 {
[[S]] // Translate S to JavaScript
}
```
The problem was that, if there are labelled variable declarations, they are compiled to `let` and not available after `}`.
Looking carefully at it, we don't have goto in Dafny so labels are used only to break out of loops. But these are no loops, only variable declarations. Hence, I claim it make sense to just remove the labels when compiling variable declarations.
The test now passes. …
=> Fix: Labels are no longer compiled in the case of variable declarations

Source/DafnyCore/Verifier/Translator.cs, Test/allocated1/dafny0/OpaqueFunctions.dfy.expect, Test/dafny0/OpaqueFunctions.dfy.expect, Test/dafny2/StoreAndRetrieve.dfy.expect, Test/dafny3/CachedContainer.dfy.expect, Test/dafny4/git-issue98.dfy.expect, Test/git-issues/git-issue-2703.dfy, Test/git-issues/git-issue-2703.dfy.expect, docs/dev/news/2703.fix
This PR fixes #2703
The story is the following. When abstract importing a module using
`import A: B`
it effectively duplicates the module `B` and creates an inside module named `B.Abs` as a child module.
This module is marked `IsFacade = true`.
The code effectively duplicated all its methods and functions, and they were not filtered out during verification.
In the translator, this PR ensures in the boolean guard `InVerificationScope` that members obtains from facade aren't verified twice.
=> Fix: Verification of abstract modules not duplicated when imported

Source/DafnyLanguageServer/CounterExampleGeneration/DafnyModel.cs, Source/DafnyLanguageServer/CounterExampleGeneration/DafnyModelState.cs, docs/dev/news/2975.feat
I'm working on debugging a particular counterexample involving a sequence (at least in theory - hence the debugging!) of contiguous intervals, like `[(0, 4), (5, 9), (10, 20)]`.  In this case, figuring out where I'm going wrong really means needing to look at sequence elements in the order that they appear.  This is the counterexample I'm given (extracted to the clipboard with [this IDE patch](https://github.com/dafny-lang/ide-vscode/pull/290)):
```
At "{" (file:///Users/ntaylor/school/smrt/src/Disks/ZonedDisk.dfy:131):
...
@1:seq<_System.Tuple2<NativeTypes.uint64, NativeTypes.uint64>> = (Length := 6286, [0] := @3, [6285] := @4, [6283] := @5, [6284] := @6)
@3:_System.Tuple2<NativeTypes.uint64, NativeTypes.uint64> = _#Make2(_0 := 0, _1 := 2448)
@4:_System.Tuple2<NativeTypes.uint64, …
```
=> Counterexamples involving seqs should present elements ordered by index

Source/DafnyCore/Compilers/SinglePassCompiler.cs, Test/git-issues/git-issue-2726.dfy, Test/git-issues/git-issue-2726.dfy.expect, Test/git-issues/git-issue-2726a.dfy, Test/git-issues/git-issue-2726a.dfy.expect, docs/dev/news/2726.fix
This PR fixes #2726 and fixes #2706
I converted contracts to if-conditions, since the next case is the default non-recursive case.
=> Fix: Tail recursion not activated if cannot

Source/DafnyCore/Resolver.cs, Test/git-issues/git-issue-2496.dfy, Test/git-issues/git-issue-2496.dfy.expect, docs/dev/news/2496.fix
This PR fixes #2496
The problem was, after reporting the error that the LHS variable of `b1 :| true` was not defined, its `.Resolved` was set to `null`, but immediately afterwards there was a check about this `.Resolved` which failed, and reported an error on the `.Resolved`, which was null, so it did not have a `.tok` property...
The fix was to ensure we don't call this check if `Resolved` is null. To ensure that I am not introducing any soundness issue, I added an `else` that verifies that the number of errors is > 0 if `Resolved` is null.
=> Fix: No more crash when unresolved LHS of :|

Source/DafnyCore/Resolver.cs, Test/git-issues/git-issue-2139.dfy, Test/git-issues/git-issue-2139.dfy.expect, docs/dev/news/2139.fix
This PR fixes #2139
Basically, there were two places where we would raise an error if a pattern was not of the right type, but immediately afterwards, we were casting it to that type. I added two return statements.
=> Fix: No more resolver crash on pattern match with incompatible types

Source/DafnyCore/AST/TopLevelDeclarations.cs, Test/git-issues/git-issue-2108.dfy, Test/git-issues/git-issue-2108.dfy.expect, docs/dev/news/2108.fix
This PR fixes #2108
Basically, we were trying to call ModuleQualifiedId.Set() on something else than a LiteralModuleDecl, and it happened it was an AliasModuleDecl. Since we were only interested by the underlying ModuleDefinition, I added a case to ensure it does not crash for AliasModuleDecl
=> Fix: Support for aliases in module resolution without crashing on imports

Source/XUnitExtensions/Lit/ShellLitCommand.cs, Test/metatests/OutputEncoding.dfy, Test/metatests/OutputEncoding.dfy.expect
This is intended to make it possible to test Unicode output.  I skipped Java because Java needs a separate patch (since it doesn't respect the current encoding / codepage, see https://github.com/dafny-lang/dafny/issues/2976)
=> fix: Force UTF-8 encoding in C# lit runner

Source/DafnyCore/Resolver.cs, Test/git-issues/git-issue-2111.dfy, Test/git-issues/git-issue-2111.dfy.expect, docs/dev/news/2111.fix
This PR fixes #2111
Basically, after the error on the expr.Lhs was reported, we tried to access the `.Resolved` property, which threw an exception because of failed contracts.
So I added the test to verify that `.WasResolved()` before, so that we don't continue if the LHS is not resolved.
=> Fix: Added missing check to prevent crash during resolution

Source/DafnyCore/Resolver.cs, Test/git-issues/git-issue-2019.dfy, Test/git-issues/git-issue-2019.dfy.expect, docs/dev/news/2019.fix
This PR fixes #2019
The story was that, if a function by method and a method had the same name, the function by method's resolved method was null. However, there were two places in the resolver, before it gives up, that were asserting that the function by method's method was not null, so I added a conditional instead and ensured that the number of reported errors was greater than zero.
=> Fix: Function by method with the same name as a method won't crash resolver

Source/DafnyCore/AST/Expressions.cs, Source/DafnyCore/Cloner.cs, Source/DafnyCore/Substituter.cs, Source/DafnyCore/Triggers/QuantifiersCollection.cs, Source/DafnyCore/Triggers/TriggersCollector.cs, Source/DafnyCore/UselessOldLinter.cs, Test/allocated1/dafny0/SmallTests.dfy.expect, Test/dafny0/SmallTests.dfy.expect, Test/git-issues/git-issue-2593.dfy, Test/git-issues/git-issue-2593.dfy.expect, Test/triggers/old-is-a-special-case-for-triggers.dfy.expect, docs/dev/news/2593.fix
This PR fixes #2593
I added the corresponding test. Basically, previously, old(...) was considered as a potential trigger. However, the translation of Boogie of old(...) expressions is not a function, but a previous variable... so this had no meaning
I removed old(...) from the list of potential triggers.
Side notes: 
* Removing old() as a trigger altogether does not work. Even ensuring it's not a trigger killer won't do it. The test dafny1/MatrixFun.dfy fails in both of these cases, because it misses one important trigger
* If there is something like `old(f(y)+1)`, even though `old()` is marked as useless, the trigger `old(f(y))` and `f(y)` will still be created due to special traversal of the tree. This is expected. This traversal will never wrap a variable with `old()` anyway. …
=> Fix: old() cannot be inferred as a trigger alone

Source/DafnyCore/AST/TopLevelDeclarations.cs, Source/DafnyCore/Resolver.cs, Test/git-issues/git-issue-2068.dfy, Test/git-issues/git-issue-2068.dfy.expect, docs/dev/news/2068.fix
This PR fixes #2068
I added the corresponding test. The case of a "this" inside a subset type is not allowed, but there was no error mechanism to detect it. This PR solves that problem.
=> Fix: Better reporting if 'this' used in a subset type - and no crash

Source/DafnyLanguageServer.Test/DafnyLanguageServer.Test.csproj, Source/DafnyLanguageServer.Test/Various/CounterExampleTest.cs, Source/DafnyLanguageServer.Test/Various/TestFiles/3048.dfy, Source/DafnyLanguageServer/CounterExampleGeneration/DafnyModel.cs, docs/dev/news/3048.fix
Occasionally the language server is passed a seq index that is not parseable as an integer.  While the root cause has not yet been determined, it's still causing an LSP crash.  This patch ensures that non-parseable indices are handled separately from those that are parseable.
After this patch, any non-integral indices are appended to the end of the sorted output: [the crashing test](https://gist.github.com/dijkstracula/b2863891f53650fcf4607abd2b35991f) in #3048 now produces,
```
@4:seq<seq<seq<_module.uint8>>> = (Length := 9899, [0] := @14, [8100] := @15, [9898] := @16, [(- 1)] := @17)
```
Fixes #3048
=> Ensure non-parseable SeqIndexs do not throw on parse failure

Source/DafnyCore/Compilers/Compiler-js.cs
=> fix: Revert old buffer workaround for calling `node`

Source/DafnyCore/Compilers/Compiler-java.cs, Source/DafnyCore/Feature.cs, docs/DafnyRef/Features.md, docs/dev/news/2795.feat, docs/dev/news/3016.feat
Ideally the feature would have been removed in the PR that implemented it in Java (https://github.com/dafny-lang/dafny/pull/3072), but unfortunately the `Feature` mechanism only allows a compiler to cleanly opt-out of supporting a feature, and we don't yet have a complementary mechanism to test that a compiler that claims to not support a feature does not in fact support that feature!
=> chore: Add missing release notes, remove feature all compilers support now

Source/DafnyDriver/Commands/VerifyCommand.cs
Enables checking only if a Dafny project resolves, without also verifying it.
=> Allow --no-verify when using the verify command

Test/lit.site.cfg
This way the lit tests work by default on my machine. Curious if anyone has concerns.
=> Explicitly use python3 in lit tests

Source/DafnyDriver/Commands/VerifyCommand.cs, Test/cli/resolve.dfy, Test/cli/resolve.dfy.expect
Fix resolve command so that it does not verify.
Added a test for the resolve command
=> No verify on resolve

Source/DafnyCore/AST/Expressions/Expressions.cs
Fixes `02-DoubleRead.dfy` and other tests from failing in DEBUG build by reverting an unintentional change made here: https://github.com/dafny-lang/dafny/pull/3117/files#diff-99ac3ad316fe9cac2a05db0a8db42d2b1fe665fb21403fb25b02e50916005c3fR2762
=> Fix construction of FrameExpression

Source/DafnyRuntime/DafnyRuntimeJava/gradlew, Source/DafnyRuntime/DafnyRuntimeJava/gradlew.bat
Attempt to fix issues such as this one: https://github.com/dafny-lang/dafny/issues/3247 and this failure: https://github.com/dafny-lang/dafny/actions/runs/3757266491/jobs/6384280545
Works both in Unix systems as well as Windows systems
=> Retry running gradle wrapper

Source/DafnyCore/DafnyOptions.cs, Source/DafnyCore/Options/BoogieOptionBag.cs, Source/DafnyCore/Options/DeveloperOptionBag.cs, Source/DafnyDriver/DafnyDriver.cs, Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs, Source/DafnyLanguageServer.Test/GutterStatus/CachedLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Synchronization/VerificationStatusTest.cs, Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs, Source/DafnyLanguageServer/StandaloneServerCli.cs, Test/cli/zeroCores.dfy, Test/cli/zeroCores.dfy.expect, Test/lit.site.cfg, docs/check-examples
Setting cores to 0 will use half of the available cores.
=> Setting cores to 0 will use half of the available cores

Source/DafnyCore/Compilers/Compiler-Csharp.cs, Source/DafnyCore/Options/DeveloperOptionBag.cs, Source/DafnyCore/Options/ICommandSpec.cs, docs/check-examples
Fixes #3260
Also adds a hidden `--spill-translation` attribute for the `run`,`build` and `test` commands.
=> Allow the :test attribute when using run and build

Source/DafnyCore/AST/Expressions/NestedMatchExpr.cs, Test/git-issues/git-issue-3333.dfy, Test/git-issues/git-issue-3333.dfy.expect, docs/dev/news/3333.fix
Fixes #3333
The actual fix was already accidentally made in https://github.com/dafny-lang/dafny/pull/2734, this PR is just adding a test case and a release note, and removing some obsolete code.
=> Add test case and release notes for 3333 fix

Source/DafnyCore/AST/Statements/Statements.cs, Test/git-issues/github-issue-3343.dfy, Test/git-issues/github-issue-3343.dfy.expect
During PR #2734, a refactoring of the cloner mistakenly omitted a clone call for one sub-expression of TypeRHS, leading to issue #3343.
This PR reinstates that clone.
Fixes #3343.
=> Add a missing expression clone

Test/auditor/TestAuditor.dfy
Hopefully this fixes nightly tests on Windows
=> Use %diff instead of diff for test

docs/dev/news/2734.feat, docs/dev/news/3061.feat, docs/dev/news/3184.feat, docs/dev/news/3185.feat, docs/dev/news/3239.feat, docs/dev/news/3252.fix, docs/dev/news/3274.fix, docs/dev/news/3275.fix, docs/dev/news/3276.fix, docs/dev/news/3311.feat
=> Add missing release notes

Source/DafnyCore/DafnyMain.cs, Source/DafnyDriver/DafnyDriver.cs, Test/git-issues/git-issue-2719.dfy, Test/git-issues/git-issue-2719.dfy.expect, Test/git-issues/git-issue-590.dfy.expect, docs/dev/news/2719.fix
=> Fix: Other CLI files that are not found do not trigger exceptions

Source/IntegrationTests/LitTests.cs
I see nightly is failing again: https://github.com/dafny-lang/dafny/actions/runs/3909011490/jobs/6679674161
I'm guessing it's because of the following commit, since that's what caused the exact same issue, namely the win-4 run timing out, so I'll revert that: 790bf7824a66d6ae7ff97faffe7addefbb0de995.
=> Revert "Cok retry induction tests (#3307)"

Source/DafnyCore/Dafny.atg, Source/XUnitExtensions/Lit/ExitCommand.cs, Test/git-issues/git-issue-3366.dfy, Test/git-issues/git-issue-3366.dfy.expect, docs/dev/news/3366.fix
This PR fixes #3366
It does not remove the parse error as it was expected, but it does add an explanation of it.
=> Fix: Proper warning that 'new' cannot be used in expressions, instead of a parse error

Source/DafnyCore/DafnyPrelude.bpl, Test/git-issues/git-issue-3411.dfy, Test/git-issues/git-issue-3411.dfy.expect, docs/dev/news/3411.fix
This PR fixes #3411 
Seems like one of Boogie's axiom was wrong, but it was unnoticed because another application axiom was ignoring the wrong argument.
I added the test case of the issue.
=> Test if this is a typo in prelude

Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Options/ICommandSpec.cs, Source/XUnitExtensions/Lit/ExitCommand.cs, Source/XUnitExtensions/Lit/LitCommandWithRedirection.cs, Source/XUnitExtensions/Lit/RunCommand.cs, Source/XUnitExtensions/Lit/StdInCommand.cs, Test/dafny0/Stdin.dfy, Test/dafny0/Stdin.dfy.expect
In preparation for the `dafny format` command to support `--stdin`, I re-added this option that was previously not ported.
=> Chore: re-added the --stdin option

Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs, Source/DafnyCore/Verifier/Translator.cs, Test/dafny0/Modules0.dfy.expect, Test/dafny0/Modules2.dfy.expect, Test/dafny0/ResolutionErrors.dfy.expect, Test/exports/ExportResolve.dfy.expect, Test/git-issues/git-issue-3449.dfy, Test/git-issues/git-issue-3449.dfy.expect, Test/traits/TraitBasix.dfy.expect, Test/traits/TraitResolution1.dfy.expect, Test/traits/TraitResolution2.dfy.expect, docs/dev/news/3450.fix
Fixes #3449
This PR fixes the verifier so that it does not assume any specific dynamic type of the object allocated by `new object`. This is a special allocation that is supposed to allocate an object of an arbitrary type. (See section 14.1 of the reference manual.)
The PR also improves the source location reported when a program attempts `new X` where `X` is a non-`class`, non-`object` type.
=> fix: Exclude type information for “new object” allocations

Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs
Fixes a CI issue where a test was sometimes failing randomly.
The reason was, there was a shared variable that was mutated by three different threads. I converted it to a concurrent dictionary, and everything works smoothly for even 10 threads.
=> Chore: Fixed flacky test that had concurrent issues

Source/DafnyCore/DafnyMain.cs, Source/DafnyPipeline.Test/RelativePaths.cs
After testing today's version of Dafny in VSCode, I realized that a path with name triggered an error when attempting to resolve includes. Hence, I added a unit test to catch this regression for next time and fixed the method that transforms file paths (which can be gross URI) to actual file locations
=> Fix canonical paths for paths with spaces

Source/DafnyCore/AST/Expressions/Expressions.cs, Source/DafnyCore/AST/MemberDecls.cs, Source/DafnyCore/AST/TokenNewIndentCollector.cs, Source/DafnyPipeline.Test/FormatterForMembers.cs
This PR fixes a formatting regression by actually implementing a missing formatting support for DatatypeValue.
Fixes #3563
=> Fix formatting regression

docs/dev/RELEASE.md
(The `a.` and `b.` aren't permitted by GitHub's Markdown flavor; instead writing `1.` and `2.` results in `i.` and `ii.` being rendered.)
=> small fixes in doc snapshot instructions

.github/workflows/doc-tests.yml, .github/workflows/msbuild.yml, .github/workflows/refman.yml, .github/workflows/runtime-tests.yml, .github/workflows/xunit-tests.yml
Our model is to have branch protection for all important branches, and therefore there isn't any need to run CI on pushes (especially since we have a nightly build to test these branches directly anyway). This should save a fair bit of CI capacity.
Also adds concurrency control for unit tests too (since they are also getting expensive).
This does NOT yet enable the nightly build for `main-*` unfortunately, as scheduled builds only run on the default branch, so that will take some more thinking (plus ensuring that different branches produce distinct prerelease version identifiers).
=> chore: Enable all CI for main-* as well, disable push triggers

.github/workflows/doc-tests.yml, .github/workflows/integration-tests-reusable.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml, .github/workflows/xunit-tests.yml, Makefile, Source/DafnyCore/DafnyOptions.cs, Source/DafnyLanguageServer.Test/Various/ResourceUsageTest.cs, Source/DafnyLanguageServer/DafnyLanguageServer.cs, Source/IntegrationTests/LitTests.cs, Test/git-issues/BoundedInts.dfy, Test/git-issues/Wrappers.dfy, Test/git-issues/git-issue-1514.dfy, Test/git-issues/git-issue-1514b.dfy, Test/git-issues/git-issue-1514c.dfy, Test/git-issues/git-issue-2927.dfy, Test/git-issues/git-issue1495.dfy, Test/lit.site.cfg
This reverts commit a9a65ebce4e40bfe19be3fd8e200a3b6c9e52a7a, to unblock CI.
It turns out that there was also an incompatibility between a) PR #3609, b) the use of new-style CLI commands in the libraries, and c) the reorganization of the modules in the libraries repo. To resolve that, this PR also (temporarily) removes the libraries from the test suite.
=> Revert "Update build to use both Z3 4.8.5 and 4.12.1 (#3622)"

Scripts/prepare_release.py, docs/dev/RELEASE.md, docs/dev/news/3641.feat, docs/dev/news/3641.fix
Also split up a compound release note file that the script wouldn’t understand.
Tested with `--dry-run`.
=> Update release process to work on non-master branches

Scripts/allow_on_mac.sh, Source/DafnyLanguageServer/DafnyLanguageServer.csproj
Other nuget packages depend on the language server, so we have to break those dependencies before we can stop publishing it.
Also patched allow_on_mac.sh to account for the change in Z3 packaging (and be more robust/idempotent in general)
=> chore: Restore publishing language server to nuget, fix allow_on_mac.sh for z3 paths

Source/DafnyCore/DafnyMain.cs, Test/name with space/run.dfy, Test/name with space/run.dfy.expect, docs/dev/news/3683.fix
This reverts commit 3c8be1eb797c3969a55c8e3b31fbfddb2892086f.
Nightly fails on Windows with a path related error, so reverting this recent path related PR should fix nightly: https://github.com/dafny-lang/dafny/actions/runs/4340642872/jobs/7579382488
=> Revert "Tested support for paths with spaces (#3684)"

Source/XUnitExtensions/Lit/LitCommandWithRedirection.cs, Source/XUnitExtensions/Lit/RunCommand.cs
Fix LitCommandWithRedirection.ExpandGlob for Windows
=> Fix LitCommandWithRedirection.ExpandGlob for Windows

Source/DafnyCore/Verifier/FunctionCallSubstituter.cs, Test/git-issues/git-issue-3691.dfy, Test/git-issues/git-issue-3691.dfy.expect, docs/dev/news/3692.fix
=> fix: Crash related to the override check for generic functions

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/CSharp/CsharpBackend.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/ExecutableBackend.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/Java/JavaBackend.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/Python/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/DafnyOptions.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyDriver/Commands/TranslateCommand.cs, Source/DafnyPipeline/DafnyPipeline.csproj, Source/XUnitExtensions/Lit/ILitCommand.cs, Source/XUnitExtensions/Lit/LitCommandWithRedirection.cs, Source/XUnitExtensions/Lit/RunCommand.cs, Test/comp/compile1verbose/CompileAndThenRun.dfy.expect, Test/comp/compile3/JustRun.dfy.expect, Test/comp/manualcompile/ManualCompile.dfy, Test/comp/manualcompile/ManualCompile.dfy.expect, Test/dafny0/JavaUseRuntimeLib.dfy, Test/dafny0/JavaUseRuntimeLib.dfy.expect, Test/verification/relaxAssignmentEnforceDeterminism.dfy, docs/dev/news/3611.fix
Revert of a revert of #3619, that includes a fix for Windows in [this commit](https://github.com/dafny-lang/dafny/commit/25959d7b637d68d3d78ab56033dd31cca3998f51)
Added the run-deep-tests and will inspect all Windows runs before merging.
=> Include runtime for java - revert of a revert

.github/workflows/release-brew.yml, Source/DafnyCore/Auditor/Auditor.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs
The auditor was using code that replaced Unix newlines to create tests, so it did not work on Windows.
This PR fixes that.
Moreover, the release brew seemed to be broken for quite some time (tested 10 commits behind master, still the same issue) The smoke script, in go, prints '\n' literally instead of a newline. I wrapped it to make it a string so that it's printed normally.
I'll file this issue later.
=> Fix deep tests (Windows)

Source/DafnyCore/Options/CommonOptionBag.cs, docs/dev/news/solverLog.fix
=> Hide --solver-log option

Source/DafnyCore/AST/Expressions/Expressions.cs, Source/DafnyCore/AST/Grammar/TokenNewIndentCollector.cs, Source/DafnyCore/AST/Statements/AssignSuchThatStmt.cs, Source/DafnyCore/AST/TopLevelDeclarations.cs, Source/DafnyCore/AST/Types/Types.cs, Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs, Source/DafnyCore/Resolver/Resolver.cs, Source/DafnyPipeline.Test/FormatterBaseTest.cs, Source/DafnyPipeline.Test/FormatterIssues.cs, docs/dev/news/3790.fix
This PR fixes #3790
Besides that bug, it looks like there was discrepancies between the formatter on the command-line and the formatter in VSCode. So I took the chance to fix it all at once because that bug was concerned as well.
I also modified the tests so that they also test the formatting post-resolution. It enabled me to find 13 failing tests that I all fixed as well.
=> Fix: Formatter consistent between command-line and VSCode

Source/DafnyCore/Options/CommonOptionBag.cs
Updated description reads:
```
--solver-plugin <solver-plugin>              Dafny uses Boogie as part of its verification process. This 
option allows customising that part using a Boogie plugin. 
More information about Boogie can be found at 
https://github.com/boogie-org/boogie. Information on how to 
construct Boogie plugins can be found by looking at the code 
in 
https://github.com/boogie-org/boogie/blob/58ab09236f41894ee9a7
93d30eb17617b0fce797/Source/Provers/SMTLib/ProverUtil.cs
```
=> Update description of --solver-plugin

Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/LinearRenderingTest.cs, Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs, docs/dev/news/3821.fix
This PR fixes #3821
Now, the screenshot is strictly better than before (assertions that are inconclusive are highlighted as errors in the gutter)
However, there is one problem remaining:
Indeed, inconclusiveness happens for an entire batch, and its token is determined by Boogie to be the method's name no matter what.  This is why in the screenshot "Test" is underlined in red (that's the diagnostic token), whereas the gutter icons are chosen based on the individual assertion's tokens.
We should change this at the boogie level, but for now this PR is an improvement over the existing state of the art.
=> Fix: Highlight "inconclusive" as errors in the gutter icons

Source/DafnyCore/DafnyCore.csproj, customBoogie.patch
Update to Boogie 2.16.4, which contains this stack overflow fix: https://github.com/boogie-org/boogie/pull/710
Fixes #3819, fixes #3803
=> Update to Boogie 2.16.4

Source/DafnyCore/Resolver/Resolver.cs, Test/git-issues/github-issue-3860.dfy, Test/git-issues/github-issue-3860.dfy.expect, docs/dev/news/3860.fix
=> Add tests for issue 3860 and resolve it

docs/DafnyRef/Statements.md
Fixes a small typo where a statement ended with `'` rather than `;`.
=> doc: fix a typo in a Dafny example

Source/DafnyCore/Verifier/Translator.cs, Test/git-issues/git-issue-3955.dfy, Test/git-issues/git-issue-3955.dfy.expect, docs/dev/news/3955.fix
=> Fix: Opaque functions with frame condition supported as follow-up of #3779

Source/DafnyCore/AST/Expressions/Expressions.cs, Test/git-issues/github-issue-4017.dfy, Test/git-issues/github-issue-4017.dfy.expect
Fixes #4017
At some point we should generate more code, such as the `Children` properties of AST nodes, to prevent bugs like this.
=> Add test and fix for issue 4017

Source/DafnyCore/Dafny.atg, docs/DafnyRef/Grammar.md, docs/dev/3755.feat
Fixes #3755
The documentation has long stated that only ACSII symbols are allowed in Dafny source text (outside of strings. characters and comments). This PR removes the representations of math symbols from the input parser.
=> Removing unicode representations of mathematical symbols from the parser

Source/DafnyCore/DafnyFile.cs, Source/DafnyDriver/Commands/CommandRegistry.cs, Test/dafny0/formatting2.dfy.expect
Fixes Test/dafny0/formatting2.dfy on Windows
=> Consistently respect --use-basename-for-filename

Source/DafnyCore/AST/Cloner.cs, Source/DafnyCore/AST/Modules/LiteralModuleDecl.cs, Source/DafnyCore/AST/Modules/ModuleDefinition.cs, Source/DafnyCore/Auditor/Auditor.cs, Source/DafnyCore/Resolver/InferDecreasesClause.cs, Source/DafnyCore/Resolver/Resolver.cs, Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/IntegrationTests/LitTests.cs, Source/XUnitExtensions/Lit/LitCommandWithRedirection.cs, Test/dafny0/TypeConstraints.dfy.expect, Test/dafny4/Bug170.dfy.expect, Test/dafny4/UnionFind.dfy, Test/dafny4/set-compr.dfy.expect, Test/git-issues/git-issue-977.dfy.expect
Combine the different loops over modules that occur in resolution. There is now a method `LiteralModuleDecl.Resolve` that can be used for basing caching module resolution on.
=> Combine module resolution loops

Source/DafnyCore/TestGenerationOptions.cs, Source/DafnyTestGeneration/DafnyInfo.cs, Source/DafnyTestGeneration/DeadCodeCommand.cs, Source/DafnyTestGeneration/GenerateTestsCommand.cs, Source/DafnyTestGeneration/ProgramModification.cs, Source/DafnyTestGeneration/ProgramModifier.cs, Source/DafnyTestGeneration/TestMethod.cs, docs/DafnyRef/Options.txt, docs/dev/4146.fix
This PR removes ugly code that is no longer necessary thanks to #4044 and #4097
=> [Test Generation] Remove redundant code

Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs, Test/dafny0/ResolutionErrors.dfy.expect, docs/dev/news/3835.fix
=> Fix: Better error message when incorrect number of out parameters

.github/workflows/xunit-tests-reusable.yml, Source/DafnyRuntime/DafnyRuntimeJava/build.gradle
Without this fix, every other PR cannot be merged.
=> Chore: Fix Gradle build flagging Java 8 compatibility as "obsolete"

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer.Test/Synchronization/TestFiles/semanticError.dfy, Source/DafnyLanguageServer/Workspace/Compilation.cs
In the language server, do not run translation if there are resolution errors
Add XUnit test
=> Do not run translation if there are resolution errors

Source/DafnyCore/Verifier/Translator.cs, Test/git-issues/git-issue-4202.dfy, Test/git-issues/git-issue-4202.dfy.expect, docs/dev/news/4202.fix
=> Fix: Support for opaque function handles

Source/DafnyCore/DafnyConsolePrinter.cs, Source/DafnyTestGeneration/DeadCodeCommand.cs, Source/DafnyTestGeneration/GenerateTestsCommand.cs, docs/DafnyRef/UserGuide.md, docs/dev/news/4216.fix
The `--show-snippets` breaks test generation because it relies on casting of `Boogie.IToken` to `Dafny.IToken` [here](https://github.com/dafny-lang/dafny/blob/d72dc7a85ae5d662dda78f927463d1e56b4a0696/Source/DafnyCore/DafnyConsolePrinter.cs#L54) and test generation makes changes to the Boogie AST that may introduce new tokens that cannot be cast. This PR disables the option, recently enabled by default, during test generation. An alternative would be to surround the cast with try-catch, but it seems that outside test generation purposes it is probably safe to assume that the cast succeeds. @atomb, @robin-aws would it be possible to merge this before the next release to make sure test generation stays stable? 
<small>By submitting this pull request, I confirm that my contribution is made …
=> Disable ShowSnippets during Test Generation

Test/lit.site.cfg
A recent change (#4087) explicitly turned on snippets in `lit`-based testing. The change causes many tests to fail, when run using `lit`. This PR turns them back off.
=> Turn off snippets for lit testing

Source/DafnyRuntime/DafnyRuntimeJava/gradlew.bat
Adds back the gradle install retry logic that was removed here: https://github.com/dafny-lang/dafny/pull/4177#
=> Retry running gradle wrapper five times on Windows

Source/DafnyCore/Dafny.atg, Source/DafnyCore/DafnyFile.cs, Test/dafny0/Input/IncludesTuples.dfy, Test/dafny0/Stdin.dfy, Test/dafny0/Stdin.dfy.expect
Fixes #4045
Fixes #4135
Two different regressions both related to refactoring `DafnyFile` to identify the source using Uris. When the source is from standard in, we now use `stdin:///` as the URL. The `LocalPath` for that URL is `/`, but `Path.GetDirectoryName` of `/` is `null` and hence causes trouble without special handling.
=> fix: --stdin regressions

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyRuntime/DafnyRuntimeJava/gradlew
Resolves failures such as this one: https://github.com/dafny-lang/dafny/actions/runs/5465422274/jobs/9949112242?pr=4237
=> Retry gradle command when not on windows, like we did before

.github/workflows/msbuild.yml
Multiple class filters must be passed in as a [single argument](https://github.com/danielpalme/ReportGenerator#usage--command-line-parameters), but previously they were passed as multiple `-classfilters:` of which only the first was actually applied.
=> Ensure that all code coverage class filters are applied

Source/DafnyDriver/DafnyDriver.cs, Source/DafnyPipeline.Test/ImplicitAssertionTest.cs, Source/DafnyServer/Server.cs, Source/DafnyTestGeneration/ProgramModification.cs, Source/DafnyTestGeneration/ProgramModifier.cs
Reduces memory usage by closing more Z3 processes and creating fewer
=> Dispose executionEngine where it is used, and don't use it when not needed

.github/workflows/integration-tests-reusable.yml, Source/DafnyBenchmarkingPlugin/JavaBenchmarkCompilationInstrumenter.cs, Source/DafnyPipeline/DafnyPipeline.csproj, Source/DafnyRuntime/DafnyRuntime.csproj, Source/DafnyRuntime/DafnyRuntimeJava/build.gradle, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/Array.java, Source/DafnyRuntime/DafnyRuntimeJava/src/main/java/dafny/DafnySequence.java, Test/benchmarks/sequence-race/SequenceRace.dfy, Test/benchmarks/sequence-race/SequenceRace.dfy.expect, Test/benchmarks/sequence-race/java/build.gradle.kts
Fixes #1454.
Uses the same technique as the C# runtime, the only wrinkle being finding the left-most node in order to call `newCopied(length)` on it. This allows us to actually assert success in the multithreaded benchmark for this case.
This required being able to install the Java runtime to Maven local, so I've also applied the same changes @alex-chew had queued up for publishing this package.
Also added support for a `{:benchmarkTearDown}` attribute in the plugin, for once-per-benchmark cleanup, statistics reporting, etc.
=> fix: Avoid race condition in Java runtime sequence concatenation optimization

Source/DafnyLanguageServer.Test/Extensions/LanguageClientExtensions.cs, Source/DafnyLanguageServer.Test/MultipleFiles.cs, Source/DafnyLanguageServer.Test/ProjectFiles/MultipleFilesTest.cs, Source/DafnyLanguageServer.Test/Synchronization/CloseDocumentTest.cs, Source/DafnyLanguageServer.Test/Synchronization/ProjectManagerDatabaseTest.cs, Source/DafnyLanguageServer.Test/Various/ConcurrentInteractionsTest.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Workspace/LanguageServerFilesystem.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs
- Make CI more reliable by fixing the stability of `CanLoadMultipleDocumentsConcurrently`
- Get rid of `CloseDocumentAndWaitAsync` since it doesn't make sense to hover over a closed document, which is what it was doing.
=> Fixes for tests among which CanLoadMultipleDocumentsConcurrently

Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs, Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Synchronization/CachingTest.cs, Source/DafnyLanguageServer.Test/Synchronization/CloseDocumentTest.cs, Source/DafnyLanguageServer.Test/Synchronization/OpenDocumentTest.cs, Source/DafnyLanguageServer.Test/Synchronization/SynchronizationTestBase.cs, Source/DafnyLanguageServer.Test/Unit/CompilationManagerTest.cs, Source/DafnyLanguageServer.Test/Unit/DafnyLangSymbolResolverTest.cs, Source/DafnyLanguageServer.Test/Unit/TextDocumentLoaderTest.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs, Source/DafnyLanguageServer.Test/Various/ConcurrentInteractionsTest.cs, Source/DafnyLanguageServer.Test/Various/ExceptionTests.cs, Source/DafnyLanguageServer.Test/Various/StabilityTest.cs, Source/DafnyLanguageServer/Handlers/DafnyTextDocumentHandler.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Language/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Language/Symbols/DafnyLangSymbolResolver.cs, Source/DafnyLanguageServer/Workspace/CompilationManager.cs, Source/DafnyLanguageServer/Workspace/IProjectDatabase.cs, Source/DafnyLanguageServer/Workspace/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs
1. Update `DafnyTextDocumentHandler.cs` so it properly awaits `ProjectManagerDatabase.OpenDocument`, so no new requests can be handled until the ProjectManager's constructor and `OpenDocument` method have been called. Without this change, a call to `CreateAndOpenTestDocument` could deadlock, because the hover request would come in while the OpenDocument request would still create a new compilation, causing the hover to wait for a dud compilation that would never be started. It's not clear why the hover wouldn't return as cancelled.
1. Update `CompilationManager` so it calls its ResolvedDocument and TranslatedDocument tasks when the `CompilationManager` is cancelled before being started.
1. Use `LanguageProtocolTestBase` instead of `LanguageServerTestBase`, which means more code re-use …
=> Prevent a race condition related to ProjectManagerDatabase.OpenDocument

Source/DafnyLanguageServer.Test/GutterStatus/CachedLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/GutterStatus/SimpleLinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer/Workspace/ChangeProcessors/Relocator.cs, Source/DafnyLanguageServer/Workspace/Notifications/VerificationDiagnosticsParams.cs, docs/dev/news/4287.fix, docs/dev/news/4308.fix
=> Fix 4287 gutter highlight before project pr

.github/workflows/release-brew.yml, docs/dev/RELEASE.md
Stop testing something installed by brew on our PR builds.
=> Turn off brew release workflow

Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyPipeline/DafnyPipeline.csproj
Fixes "GetTargetPath" target not found issue when building in Rider, and likely also the nightly build.
=> Fix MSBuild issues by removing the duplicate DafnyRuntime reference

Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs
Use reference counting when compiling datatypes to Rust
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4339).
* #4343
* #4341
* #4340
* __->__ #4339
=> Use reference counting when compiling datatypes to Rust

Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs
Support string type in the Rust backend
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4340).
* #4343
* #4341
* __->__ #4340
=> Support string type in the Rust backend

Source/DafnyCore/Compilers/Rust/Compiler-rust.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/Compilers/Rust/RustBackend.cs, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyPipeline/DafnyPipeline.csproj, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.lock, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.toml, Test/.gitignore
Use Cargo to build Rust sources, to support runtime dependencies
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4341).
* #4346
* #4343
* __->__ #4341
=> Use Cargo to build Rust sources, to support runtime dependencies

Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.lock, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.toml, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, docs/DafnyRef/Features.md
Support co-inductive datatypes in Rust backend
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4343).
* #4353
* #4352
* #4346
* __->__ #4343
=> Support co-inductive datatypes in Rust backend

Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/GeneratedFromDafnyRust.cs
Initial support for multi-assignments and class methods in the Rust backend
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4346).
* #4368
* #4363
* #4361
* #4353
* #4352
* __->__ #4346
=> Initial support for multi-assignments and class methods in the Rust backend

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/Python/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyRuntime/DafnyRuntimeGo/DafnyRuntimeFromDafny.go
Remove redundant `GenerateLhsDecl` from `SinglePassCompiler`
Its usage throughout all backends is subsumed by `DeclareLocalVar`.
=> Remove redundant `GenerateLhsDecl` from `SinglePassCompiler`

Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs
Support while, ite, and char in the Rust backend
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4352).
* #4369
* #4368
* #4363
* #4361
* #4353
* __->__ #4352
=> Support while, ite, and char in the Rust backend

Makefile, Scripts/package.py
Fixes the download URLs for Z3 in a couple of places.
=> Fix z3 download

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/DafnyGeneratedFromDafny.sh, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyRuntime/DafnyRuntime.cs, Test/git-issues/git-issue-4012.dfy, Test/git-issues/git-issue-4012.dfy.cs.check
Fixes #4125. We could also apply this to the other collection types, but the benefit would only lie in the simpler code generation.
=> fix: Return `BigInteger` when computing the `multiset` cardinality in C#

Source/DafnyCore/DafnyPrelude.bpl
An axiom in DafnyPrelude was incorrectly being pruned away with the `monomorphic` type encoding, because it was losing its (polymorphic) quantifier and trigger. This meant automatic edge inference from triggers was no longer applicable. Moved the axiom in question into a uses clause to prevent it from being pruned.
The change has no affect on other type encodings `arguments` (current default) and `predicates`.
There is more discussion related to the fix here in [Boogie PR 767](https://github.com/boogie-org/boogie/pull/767).
=> Fix: incorrect pruning of axiom with monomorphization.

Source/DafnyLanguageServer/ServerCommand.cs, Source/DafnyLanguageServer/StandaloneServerCli.cs, Source/DafnyLanguageServer/Workspace/ProjectManager.cs, Source/DafnyLanguageServer/Workspace/VerifyOnMode.cs
Rename CLI option back to its previous name, for backwards compatibility reasons.
=> Fix backwards compatibility with regards to the VerifyOnMode option

Source/DafnyLanguageServer.Test/Synchronization/DiagnosticsTest.cs, Source/DafnyLanguageServer/Workspace/CompilationManager.cs, docs/dev/news/4413.fix
Fixes https://github.com/dafny-lang/ide-vscode/issues/409
- Previously, due to a bug in `StatusFromBoogieStatus`, a BatchCompleted notification would cause the status bar to consider this verifiable to have finished verification, even if other batches were still running. This is the cause for the behavior "status bar flickers between Verification Succeeded" and "Could not prove the declaration"", because it will show the status of the last completed batch.
- Update diagnostics after each completed batch. This improves the behavior "whole lot of errors finally appear in the "problems" window"
- Add test `NoFlickeringWhenMixingCorrectAndErrorBatches`
- Add test `IncrementalBatchDiagnostics`
<small>By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Fix flickering and incorrect results in the verification status bar, and improve responsiveness of diagnostics

Source/DafnyCore/AST/Grammar/Printer.cs, Source/DafnyLanguageServer.Test/CodeActions/CodeActionsTest.cs, Source/DafnyLanguageServer/Language/ImplicitFailingAssertionCodeActionProvider.cs, docs/dev/news/4401.fix
Fixes #4401
Previously, implicit assertions were inserted at the wrong place in the presence of modules, and implicit existential assertions were printed with wrong variables. This PR fixes both.
=> Fix: Existential assertions are printed correctly

docs/DafnyRef/Types.md
This was accidentally partially uncommented when various `` directives were added, which unintentionally terminated an earlier `<!--`. The partial section is visible at the end of the Iterators section: http://dafny.org/dafny/DafnyRef/DafnyRef#sec-iterator-types
=> doc: Delete “Async-task types” section

docs/DafnyRef/integration-cs/IntegrationCS.md
Fixes type mapping table for C# Integration documentation here: [IntegrationCS](https://dafny.org/dafny/DafnyRef/integration-cs/IntegrationCS#types)
=> docs: remove erroneous syntax breaking table

Source/DafnyLanguageServer.Test/Synchronization/DeclarationLocationMigrationTest.cs, Source/DafnyLanguageServer.Test/Synchronization/LookupMigrationTest.cs, Source/DafnyLanguageServer.Test/Synchronization/SymbolMigrationTest.cs, Source/DafnyLanguageServer.Test/Unit/GhostStateDiagnosticCollectorTest.cs, Source/DafnyLanguageServer/Language/GhostStateDiagnosticCollector.cs, Source/DafnyLanguageServer/Language/IGhostStateDiagnosticCollector.cs, Source/DafnyLanguageServer/Language/Symbols/ISymbolTableFactory.cs, Source/DafnyLanguageServer/Language/Symbols/LegacySignatureAndCompletionTable.cs, Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs, Source/DafnyLanguageServer/Workspace/Documents/Compilation.cs, Source/DafnyLanguageServer/Workspace/Documents/CompilationAfterResolution.cs, Source/DafnyLanguageServer/Workspace/IdeState.cs, Source/DafnyLanguageServer/Workspace/LanguageServerExtensions.cs, Source/DafnyLanguageServer/Workspace/Migrator.cs, Source/DafnyLanguageServer/Workspace/SymbolGuesser.cs, Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyServer/SuperLegacySymbolTable.cs
1. Rename `LegacySymbolTable`, which is part of the non-LSP Dafny server, to `SuperLegacySymbolTable`
1. Rename `SignatureAndCompletionTable` to `LegacySignatureAndCompletionTable`
1. Let `SignatureAndCompletionTable` differentiate between positions in different files, so it doesn't get confused between symbols in different files when they have similar positions or ranges.
1. Only migrate state in `SignatureAndCompletionTable` that relates to the changed file
- There could be a test added for 3 but I didn't add it.
- Merging this PR into this other PR (https://github.com/dafny-lang/dafny/pull/4419), reduces the time of the test `ManyFastEditsUsingLargeFilesAndIncludes` from 47 seconds to 8 seconds
<small>By submitting this pull request, I confirm that my contribution is made under the …
=> Multi-file support for  legacy symbol table

.github/workflows/msbuild.yml, Makefile, Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.lock, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.toml, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, docs/DafnyRef/Features.md
Support subset types in the Rust backend
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4422).
* #4438
* #4429
* __->__ #4422
=> Support subset types in the Rust backend

.github/workflows/msbuild.yml, Source/DafnyCore/Compilers/Dafny/AST.dfy, Source/DafnyCore/Compilers/Dafny/ASTBuilder.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs
Support class fields in the Rust backend
Right now, we still use reference counted pointers, which means that cycles will result in memory leaks. I plan to address this with cycle collection in a later PR.
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4429).
* #4438
* __->__ #4429
=> Support class fields in the Rust backend

Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs, Source/DafnyLanguageServer.Test/Lookup/GoToDefinitionTest.cs, Source/DafnyLanguageServer.Test/Lookup/HoverTest.cs, Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs, Source/DafnyLanguageServer.Test/ProjectFiles/CompetingProjectFilesTest.cs, Source/DafnyLanguageServer.Test/ProjectFiles/MultipleFilesProjectTest.cs, Source/DafnyLanguageServer.Test/ProjectFiles/ProjectFilesTest.cs, Source/DafnyLanguageServer.Test/Refactoring/RenameTest.cs, Source/DafnyLanguageServer.Test/Synchronization/VerificationOrderTest.cs, Source/DafnyLanguageServer.Test/Synchronization/VerificationStatusTest.cs, Source/DafnyLanguageServer.Test/Various/CompilationStatusNotificationTest.cs, Source/DafnyLanguageServer/ServerCommand.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs
- The Dafny language server will now always run in project mode when it finds a `dfyconfig.toml` related to an open file
- Fixed test `ProjectFileOverridesOptions` since it had issues.
- Existing tests still pass with this change in default
=> Always have project mode on

Source/DafnyCore/AST/Grammar/ProgramParser.cs, Source/DafnyCore/Coco/Parser.frame, Source/DafnyCore/Dafny.atg, Source/DafnyCore/DafnyFile.cs, Source/DafnyDriver/DafnyDoc.cs, Source/DafnyDriver/DafnyDriver.cs, Source/DafnyLanguageServer/Language/CachingParser.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyTestGeneration/Utils.cs
- Enable cancelling of parsing at the token granularity level, instead of only at the file level
- Do not open file streams used for parsing until actually parsing
We don't have a good way of automatically testing such a performance change right now, but in one manual test run I saw runtime go down from 35 to 9s.
=> Parser cancellation

Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafnyRust.cs, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs
Fix Rust compilation errors for unused types and constant fields
Also fixes runtime crashes due to a buggy transmute for tuples.
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4450).
* #4452
* __->__ #4450
=> Fix Rust compilation errors for unused types and constant fields

.github/workflows/integration-tests-reusable.yml
Fixes the path for the Windows check in the nightly integration tests
=> Fixed Windows workflow path

Source/DafnyCore/Generic/Node.cs, Source/DafnyLanguageServer.Test/Lookup/DocumentSymbolTest.cs
Previously the IDE server would become completely unresponsive when a repeated comma occurred in a parameter, now it does not.
Added test to ensure the behavior does not occur
=> Prevent the IDE from locking up when certain parse error occur

Source/DafnyCore/AST/Members/Field.cs
Prevent NRE when accessing Field.Children
I think we should prevent bugs like this by turning on nullability checking in our codebase
=> Prevent NRE when accessing Field.Children

Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/GeneratedFromDafnyRust.cs
Fix Rust backend crashes due to match cases and static consts
license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/dafny-lang/dafny/pull/4458).
* #4518
* #4468
* #4459
* __->__ #4458
=> Fix Rust backend crashes due to match cases and static consts

Test/wishlist/FuelTriggers.dfy, Test/wishlist/FuelTriggers.dfy.expect
Evidently, this was fixed by https://github.com/dafny-lang/dafny/pull/4180
=> chore: Mark FuelTrigger wish as now passing

.github/workflows/refman.yml
- Fix refman build by adding apt-get update
- Use a static version of Ubuntu instead of `ubuntu-latest`
=> Fix refman build by adding apt-get update

.github/workflows/integration-tests-reusable.yml, Source/IntegrationTests/IntegrationTests.csproj, Source/IntegrationTests/coverlet.runsettings
Addresses https://github.com/xunit/xunit/issues/2549 to reduce our integration test shard execution time from almost 90 mins in the worst case to under 30 mins.
The TL;DR is that xUnit has an extension mechanism that attempts to load every class in every available DLL to see if it extends a given interface. This manifests in a huge delay on startup before any tests begin to run, e.g. 52 mins in this case: https://github.com/dafny-lang/dafny/actions/runs/6241813664/job/16944685069#step:22:146 (make sure you turn on Show Timestamps!) This was steadily getting worse as we added more classes, especially https://github.com/dafny-lang/dafny/pull/4438 as it added a bunch of Dafny-generated code.
Fortunately xUnit 2.5.1 added a knob to switch off this discovery, which we're definitely not using. …
=> ci: Disable test reporter auto-discovery to speed up integration tests

.github/workflows/doc-tests.yml, .github/workflows/integration-tests-reusable.yml, .github/workflows/msbuild.yml, .github/workflows/nightly-build-manual.yml, .github/workflows/nightly-build-reusable.yml, .github/workflows/nightly-build.yml, .github/workflows/publish-release-reusable.yml, .github/workflows/publish-release.yml, .github/workflows/refman.yml, .github/workflows/runtime-tests.yml
This addresses the fact that the nightly build only publishes prereleases out of `master`, even when we have a different branch containing the content of the next planned release. See comment on the top of `nightly-build.tml` for details.
Also addressed a couple of incidental issues, renaming `sha` to `ref` in a few places to clarify use, and passing the correct branch to `check-deep-tests-reusable.yml`.
Since these changes are notoriously difficult to test properly before merging, I'd recommend only merging this well ahead of the scheduled trigger time (14:30 UTC) and triggering it manually with the `nightly-build-manual.yml` workflow.
Feel free to update the target branch from `4.3` to `main-4.3` if that renaming happens before this is merged.
<small>By submitting this pull request, I …
=> ci: Split off reusable nightly build workflow, run it for master and 4.3

.github/workflows/nightly-build-manual.yml, .github/workflows/nightly-build-reusable.yml, .github/workflows/nightly-build.yml, .github/workflows/publish-release.yml
Broken by #4573. Tested on my fork this time (skipped because of the `if: github.repository_owner == 'dafny-lang'` guard, but at least verified the syntax is valid): https://github.com/robin-aws/dafny/actions/runs/6276358103/job/17045852984
=> fix: Fix reusable workflow secrets declarations

Source/DafnyCore/Compilers/Rust/RustBackend.cs, docs/DafnyRef/Features.md
This is still experimental and not meant to be advertised in any way just yet.
=> chore: Hide Rust backend in reference manual

.github/workflows/check-deep-tests-reusable.yml, .github/workflows/doc-tests.yml, .github/workflows/msbuild.yml, .github/workflows/publish-release.yml, .github/workflows/refman.yml, .github/workflows/runtime-tests.yml, docs/dev/RELEASE.md
Until this PR, for the last 5 days, check-deep-tests was checking a result that was 5 days old.
Releases are impossible because deep-tests.yml has been renamed.
This PR tweaks check-deep-tests to check the right workflow and not attempt to check on a per-branch basis (since `nightly-build.yml` checks the same branches no matter what branch it is launched on) - this means development on any protected branch will be blocked by failures on any such branch, but this is at least safe for now.
Also changed the `publish-release.yml` workflow to run the deep tests directly instead of checking for a previous run, since this avoids the issue above and is more efficient anyway. …
=> Chore: Updated check deep tests to account for workflow refactoring, run deep tests inline with release process

Source/DafnyCore/ProofDependencyWarnings.cs, Source/DafnyCore/Verifier/ProofDependency.cs, Source/DafnyCore/Verifier/Translator.cs, Source/DafnyDriver/DafnyDriver.cs, Test/logger/ProofDependencyLogging.dfy, Test/logger/ProofDependencyWarnings.dfy, Test/logger/ProofDependencyWarnings.dfy.expect
Some assertions are translated into assumptions in specific contexts.
Before this change, if those assertions were unused in the proof, Dafny
would warn that they may have been proved vacuously. Now it doesn’t.
Along the way, this also changes the behavior of proof dependency warnings
so that they're produced for any definition that successfully verifies, even
if some definitions in the program have errors.
By submitting this pull request, I confirm that my contribution is made under
the terms of the MIT license.
=> Fix spurious vacuity warnings when assertions converted to assumptions

Source/DafnyCore/AST/SystemModuleManager.cs, Source/DafnyCore/AST/TypeDeclarations/IteratorDecl.cs, Source/DafnyCore/Resolver/InferDecreasesClause.cs, Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs, Source/DafnyCore/Rewriters/AutoContractsRewriter.cs, Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs, Source/DafnyCore/Verifier/Translator.cs
This PR does 3 things. The primary thing is to change
``` c#
Expression e = fe.E;
```
to
``` c#
Expression e = new Cloner(false, true).CloneExpr(fe.E);
```
in `InferDecreasesExpr.cs`. This prevents the given `reads` expression AST nodes from being shared in the generated `decreases` clause. (This is good, because it lets the new type inference assume that it will come across each variable declaration just once.)
The PR also introduces a method `SystemModuleManager.ObjectSetType()`, which returns the type `set<object?>`. This type was constructed in many places in the Dafny implementation, including in the code surrounding the primary change of this PR.
Finally, the PR rewrites some code surrounding the primary change to use more modern C#.
<small>By submitting this pull request, I confirm …
=> Clone reads for decreases

Source/DafnyCore/ProofDependencyWarnings.cs, Source/DafnyCore/Verifier/ProofDependency.cs, Test/logger/ProofDependencyLogging.dfy, Test/logger/ProofDependencyWarnings.dfy.expect
Previously, `--warn-redundant-assumptions` would warn about instances of `assume true`. These are almost always intentionally included, and used as a place to hang attributes related to the proof process (like `{:split_here}`), so it doesn't make sense to warn about them.
=> Don't warn about `assume true` being unused

Source/DafnyCore/Resolver/PreType/AdjustableType.cs, Source/DafnyCore/Resolver/PreType/Flows.cs, Source/DafnyCore/Resolver/PreType/PreType2TypeUtil.cs, Source/DafnyCore/Resolver/PreType/PreTypeResolve.Expressions.cs, Source/DafnyCore/Resolver/PreType/PreTypeToType.cs, Source/DafnyCore/Resolver/PreType/TypeAdjustor.cs, Test/dafny0/Termination.dfy, Test/dafny0/Termination.dfy.refresh.expect
This PR makes some fixes and improvements to the new type system:
* Fix some of the pre-type to type conversions, including the building of flows for binary expressions
* Remove code that distinguished all 3 kinds of variance, where only co-variance mattered
* As part of the previous bullet, remove the `ExactTypePlaceholder` type that is not used
* Improve debug printing
* Remove a call-graph edge addition from type inference (this statement must have been oversight from when the migration of call-graph building was moved to a later phase of the Resolver pipeline)
* Adjust one affected test file
=> Add flows for binary operators

Source/DafnyCore/AST/Grammar/ParseErrors.cs, Source/DafnyCore/AST/Modules/ModuleDefinition.cs, Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs, Source/DafnyCore/Dafny.atg, Source/DafnyCore/DafnyOptions.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Resolver/NameResolutionAndTypeInference/CheckTypeInferenceVisitor.cs, Source/DafnyCore/Resolver/NameResolutionAndTypeInference/NameResolutionAndTypeInference.cs, Source/DafnyCore/Resolver/PreType/PreType2TypeUtil.cs, Source/DafnyCore/Verifier/Translator.cs, Test/traits/GeneralTraits.dfy, Test/traits/GeneralTraitsCompile.dfy, Test/traits/GeneralTraitsVerify.dfy, Test/traits/NonReferenceTraits.dfy, Test/traits/NonReferenceTraitsCompile.dfy, Test/traits/NonReferenceTraitsVerify.dfy, Test/traits/TraitVariance.dfy, docs/DafnyRef/Options.txt, docs/HowToFAQ/Errors-Parser.md, docs/HowToFAQ/Errors-Parser.template
The Dafny language is extending its `trait` types to make them available not just as abstract supertypes for `class` types, but also as abstract supertypes for other types. Over time (probably in Dafny 5), the new traits will be the default. This PR provides a command-line option that allows program to opt-in to using the new traits now:
```
--general-traits=<value>
legacy (default) - Every trait implicitly extends 'object', and thus is a reference type.
Only traits and reference types can extend traits.
datatype - A trait is a reference type only if it or one of its ancestor traits is 'object'.
Any non-'newtype' type with members can extend traits.
```
Under the `--general-traits=datatype` option, a `trait` is a reference type iff:
* the trait is declared to explicitly extend `object` …
=> feat: Non-reference traits

Source/DafnyCore/AST/Expressions/Expression.cs, Source/DafnyCore/Rewriters/RewriterCollection.cs, Source/DafnyCore/Rewriters/TriggerGeneratingRewriter.cs, Source/DafnyCore/Triggers/QuantifiersCollection.cs, Test/dafny0/PrefixTypeSubst.dfy, Test/dafny0/PrefixTypeSubst.dfy.expect, Test/dafny4/UnionFind.dfy
This PR makes sure that any automatically selected trigger expressions are of AST forms that can be resolved (by the new type system).
The AST nodes `FunctionCallExpr` and `MemberSelectExpr` (henceforth referred to as "those two cases") are never produced by the parser. Instead, these are created during resolution, from some `ConcreteSyntaxExpression` after such a `ConcreteSyntaxExpression` has been resolved. This means that name-resolution/type-inference doesn't need to handle those two cases. In the old type system, there is nevertheless code for resolving these two AST nodes, which seems like dead code or at best redundant. The new type-system implementation instead asserts out if it's asked to resolve one of those two expressions. So, the new type system expects to never be asked to …
=> Use resolved syntax expressions for triggers

Source/DafnyCore/Options/CommonOptionBag.cs
Hides the plugin option from the regular help. 
The plugin option was already marked experimental to indicate that the API is expected to change, and that without special circumstances, no system should depend on this option. Hiding the option means it won't show up when using `--help`, to make it extra clear that users should not depend on this option. Users who work with the Dafny maintainers to develop this feature can still use it, and the option is still shown when using `--help-internal`.
Manually
=> Hide the plugin option

Source/DafnyCore/Compilers/CSharp/CsharpBackend.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Plugins/IExecutableBackend.cs, Source/DafnyDriver/Commands/RunCommand.cs, Source/DafnyDriver/DafnyDriver.cs, Test/cli/projectFile/projectFileRun.dfy, Test/cli/projectFile/projectFileRun.dfy.expect, Test/cli/projectFile/src/input.dfy
Fixes #4622
- Enable passing project files to 'dafny run'
- Add a hidden `--build` option to configure where intermediate build files are placed when using `dafny run`
Added a littish test
=> Enable passing project files to 'dafny run'

.github/workflows/nightly-build.yml
Now that 4.3.0 has been released, we should revert to publishing pre-releases from the master branch instead of the 4.3.0 branch.
This also removes the nightly builds for the 4.3.0 branch entirely, to save CI resources and since it's no longer needed.
No manual test run, but can do so as described in https://github.com/dafny-lang/dafny/pull/4573.
=> chore: publish nightly prereleases from master instead of 4.3

Test/logger/VerificationCoverageReport.dfy
The different line endings on Windows mean that the coverage report positions are different. Everything should still work fine on Windows, but the static .expect file is only valid for systems that use Unix-style newlines.
=> Skip VerificationCoverageReport.dfy on Windows

Source/DafnyCore/CoverageReport/CoverageLabel.cs, Source/DafnyCore/CoverageReport/CoverageReport.cs, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Options/DafnyCommands.cs, Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs, Source/DafnyDriver/Commands/CoverageReportCommand.cs, Source/DafnyDriver/Commands/GenerateTestsCommand.cs, Source/DafnyDriver/CoverageReporter.cs, Source/DafnyTestGeneration/BlockBasedModifier.cs, Source/DafnyTestGeneration/Main.cs, Source/DafnyTestGeneration/ProgramModifier.cs, Source/DafnyTestGeneration/Utils.cs, Test/logger/CoverageReport.dfy, Test/logger/ProofDependencyLogging.dfy, Test/logger/ProofDependencyLogging.dfy_combined.html.expect, Test/logger/ProofDependencyLogging.dfy_tests_expected.html.expect, Test/logger/ProofDependencyLogging.dfy_verification.html.expect, Test/logger/VerificationCoverageReport.dfy
This PR makes changes to how coverage reports produced using test generation and proof dependency analysis can be merged together. In particular:
- Calling `dafny merge-coverage-reports` now produces a 'combined coverage' file that only labels code that is also labeled in all original coverage reports. So, for example, code labeled in red would have to not be covered both by the proof dependency analysis and by tests.
- Code is now labeled using line and column numbers. This should lead to identical outputs on Windows vs Unix.
- Test coverage reports now highlight more lines as opposed to only labeling the last line associated with a given basic block in Boogie. This is achieved by adding more `:captureState` assumptions in the translator (only in translation passes that happen as part of …
=> Parity for Test Coverage and Proof Dependency Coverage Reports

Source/DafnyDriver/Commands/CoverageReportCommand.cs, Source/DafnyDriver/CoverageReporter.cs, Test/logger/CoverageReport.dfy, Test/logger/ProofDependencyLogging.dfy_combined_limited.html.expect, docs/dev/news/4673.feat
Add a new `--only-label` option to `merge-coverage-reports` to include only one category of highlighting in the output. For example, merging coverage reports from test generation and verification using the option `--only-label NotCovered` will highlight only the regions not covered by either testing or verification.
=> Allow filtering of combined coverage reports

Source/DafnyCore/ProofDependencyWarnings.cs, Source/DafnyDriver/TextLogger.cs, Test/logger/NoProofDependenciesOnError.dfy, Test/logger/ProofDependencyLogging.dfy, Test/logger/ProofDependencyLogging.dfy_combined.html.expect, Test/logger/ProofDependencyLogging.dfy_combined_limited.html.expect, Test/logger/ProofDependencyLogging.dfy_tests_expected.html.expect, Test/logger/ProofDependencyLogging.dfy_verification.html.expect
Make `--log-format text` output program elements unused in a proof, in addition to the existing proof dependencies.
These can be useful for deep dives into understanding how a proof was completed. 
=> Add unused dependencies to text logger

Source/IntegrationTests/TestFiles/LitTests/LitTest/lit.site.cfg
Recently (https://github.com/dafny-lang/dafny/pull/4615), the Dafny test suite moved from `Test/` to `Source/IntegrationTests/TestFiles/LitTests/LitTest/`. This PR makes a corresponding change in the `respositoryRoot` definition in `lit.site.cfg`. This allows `lit` to be run in the new location.
=> Adjust repositoryRoot, now that lit tests have moved

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, Source/IntegrationTests/TestFiles/LitTests/LitTest/README.md
Fixups for things I should have spotted from #4615 :P
Manually checking markdown links in VS Code
=> chore: Restore lost README.md about integration tests, update references to Test directory

Source/DafnyLanguageServer.Test/Lookup/DocumentSymbolTest.cs, Source/DafnyLanguageServer/Handlers/DafnyDocumentSymbolHandler.cs
- Prevent a client side crash on our malformed document symbol results, that would occur when code has `function` with a name.
- Added a few XUnit tests
=> Fix client side crash for document symbol because of empty name 

Source/DafnyDriver/VerificationResultLogger.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/logger/MultipleLoggers.dfy
An extraneous `return` was preventing multiple verification loggers from running.
=> Allow text and csv loggers together

Source/DafnyCore/Verifier/BoogieGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/PR4715Test.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/PR4715Test.dfy.expect
There were two utility methods to translate the predicate associated with an assert statement. Both could translate it into an assumption in Boogie under certain circumstances. One avoided recording it as a proof obligation in this case, but the other didn’t. Now it does.
The new test case, `git-issues/PR4715Test.dfy`, generates no warnings. (It did generate a warning prior to this PR.)
=> Fix spurious warning about vacuous proof

Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4449.dfy.cs.check, Source/TestDafny/MultiBackendTest.cs
Recently there was a change in MultibackendTest which causes DafnyRuntime.dll to be passed to Dafny as an input argument for C# runs. This triggers a potential crash in the C# back-end, which occurs when it fails to copy any input .dlls for any reason: https://github.com/dafny-lang/dafny/actions/runs/6755446930/job/18363885807
This change redirects the output of `dafny run ...` when using `%testDafnyForEachCompiler` to a unique temporary directory, so that tests can't step on each other in this way.
Manually verified `--build` has the desired effect. Symptom only sometimes shows up in nightly builds unfortunately.
<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).< …
=> ci: Use —build:<temp dir> in MultiBackendTest

Source/DafnyLanguageServer.Test/Synchronization/GhostDiagnosticsTest.cs, Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs, docs/dev/news/4693.fix
Fixes #4693
I added a test that was previously failing.
=> Fix: Ghost diagnostics correctly updated when becoming empty

Source/DafnyCore/Generic/Reporting.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3304.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4787.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4787.dfy.expect, docs/dev/news/4787.fix
Fixes #4787.
Added `git-issue-4787.dfy` to test the reported case.
=> fix: print error context snippets after their messages

docs/OnlineTutorial/guide.md
Small typo fix `i` -> `index`.
=> typo: code sample uses the variable name `index`

.github/workflows/publish-release-reusable.yml
This removes the `--no-build` flag from `dotnet pack` commands in the `publish-release-reusable.yml` workflow file. This was causing a failure with the following message:
```
Error: /usr/share/dotnet/sdk/8.0.100/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file '/home/runner/work/dafny/dafny/dafny/Binaries/net6.0/DafnyDriver.runtimeconfig.json' to be packed was not found on disk. [/home/runner/work/dafny/dafny/dafny/Source/DafnyDriver/DafnyDriver.csproj]
...
Error: Process completed with exit code 1.
```
from this run: https://github.com/dafny-lang/dafny/actions/runs/6931560381/job/18866468076
This PR should unblock CI jobs for now, at the cost of a (maybe redundant?) rebuild of Dafny during each release job. I've left some notes below for …
=> ci: remove --no-build from `dotnet pack` commands

Source/DafnyCore/Verifier/FunctionCallSubstituter.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4812.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4812.dfy.expect, docs/dev/news/4812.fix
=> Fix: Override checks no longer crashing when substituting type parameters and equality

Source/DafnyLanguageServer/Workspace/ProjectManager.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs, docs/dev/news/4833.fix
Fixes #4833 
I replaced the openFileCount by openFiles so that closing a document, even if unexpected like VSCode does randomly, won't trigger the Compilation object to be disposed, which crashes the IDE every 3-4 minutes on projects with multiple files open.
I have been enjoying the IDE for 20 minutes straight without restarting it. It's a fantastic experience. I'm going to turn on "verification on change" again.
=> Fix: No more spurious restart needed in the IDE

Source/DafnyLanguageServer/Workspace/Compilation.cs
=> fix: Don’t add target-specific standard library doo files to root source URIs

Source/DafnyCore/Resolver/PreType/PreType.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4866.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4866.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4866.dfy.refresh.expect, docs/dev/news/4875.fix
Fixes a problem in PreType substitution that caused a null dereference later on.
Fixes #4866
=> fix: Fix initialization problem in PreType.Substitute

Source/DafnyCore/AST/Modules/ModuleDefinition.cs, Source/DafnyCore/AST/TypeDeclarations/Declaration.cs, Source/DafnyCore/Compilers/DafnyExecutableBackend.cs, Source/DafnyCore/Compilers/ExecutableBackend.cs, Source/DafnyCore/Compilers/ExternExtensions.cs, Source/DafnyCore/Compilers/Java/JavaBackend.cs, Source/DafnyCore/Resolver/ProgramResolver.cs, Source/DafnyDriver/CompilerDriver.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/complex/user.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/complex/user.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/externErrors.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/externErrors.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/replaceableExecutionErrors.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/replaceableExecutionErrors.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/resolveManyReplacement.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/replaceables/resolveManyReplacement.dfy.expect
- Make separate compilation work reliably for replaceable modules
- There is a still a check that should be added but is missing in this PR, which is to emit an error if an `{:extern}` attribute is used to overwrite the compiled name of a replaced definition. I would've added that check to this PR but I'm saving it for the future since I'm not yet sure what the best way is.
- This PR adds the restriction that you can't overwrite names using `{:extern}` inside modules that replace another module. This takes some of the fun out of using replaceable modules, since now users may have to create not one but two modules in their target specific code: 
- one that uses `{:extern}` with the desired name overrides
- another that replaces the replaceable module and delegates its implementation to the …
=> Replaceable module separate compilation

Source/DafnyRuntime/DafnyRuntimeJava/build.gradle
This PR updates the Java runtime Gradle configuration to use the latest version of the [Maven publishing plugin](https://github.com/gradle-nexus/publish-plugin/).
The updated plugin was used to publish the 4.4.0 Java runtime to Maven Central: https://central.sonatype.com/artifact/org.dafny/DafnyRuntime/4.4.0
=> chore: update publishing plugin for Java runtime

Source/DafnyCore/Resolver/PreType/PreTypeResolve.Expressions.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4953.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4953.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4953.dfy.refresh.expect, docs/dev/news/4955.fix
=> fix: Fix crash for lookup of non-existing member in new resolver

Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/FunctionCallSubstituter.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4952.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4952.dfy.expect, docs/dev/news/4954.fix
This PR causes 5 kinds of crashes that could happen when a function/method (with a specification) of a trait was overridden in an abstract type.
Fixes #4952
=> fix: Correct cast of EnclosingClass

.github/workflows/nightly-build.yml
This PR resumes publishing nightly builds from `master`. (It was accidentally removed in https://github.com/dafny-lang/dafny/pull/4931.)
=> ci: resume publishing nightly builds from master

.github/workflows/publish-release-reusable.yml
This PR disables the reference manual build during pre-release CI, in order to unblock development while we determine how to fix the refman build failures (see related: https://github.com/dafny-lang/dafny/pull/4993).
=> ci: disable refman build on prerelease CI

Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny3/InductionVsCoinduction.dfy
Revert a change to this file made in PR https://github.com/dafny-lang/dafny/pull/5000, that causes nightly failures such as these: https://github.com/dafny-lang/dafny/actions/runs/7697691415/job/20975253705
=> Fix the nightly build

Source/DafnyCore/AST/Members/ICodeContext.cs, Source/DafnyCore/Verifier/BoogieGenerator.Types.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/github-issue-5029.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/github-issue-5029.dfy.expect
Use full type declaration names in Boogie generation. Failing to do this was leading to spurious warnings about proofs due to contradictory assumptions.
Fixes #5029
`Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/github-issue-5029.dfy`
=> Use full type declaration names in Boogie generation

Source/DafnyCore/AST/Types/Types.cs, Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/Python/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs
This PR contains some minor changes to the compilers. These changes have been carved off from a larger set of changes (for supporting general `newtype`s and `is` expressions), to simplify the reviewing of the latter.
The changes in this PR are:
* Rename parameter of `EmitDowncastVariableAssignment` (`collectionElementType` to `sourceType`).
* Add `nativeType` parameter to ` EmitBitvectorTruncation` (to allow it to be different than `bvType.NativeType`).
* In some places, don't assume that native type of bitvector type is always as wide as the bitvector. (This happens to be true today, but it may not be true in the future (i) when a `newtype` can have a bitvector base type, which will happen soon, and (ii) if `IntBoundedPool` starts supporting bitvector types.
Since the changes are meant …
=> Make smaller changes to compilers

Source/DafnyLanguageServer/LanguageServer.cs
Customize the options used by the language server less, by relying on fewer defaults
=> Customize the options used by the language server less

Source/DafnyCore/Resolver/ModuleResolver.cs, Source/DafnyCore/Rewriters/ExpectContracts.cs, Source/DafnyCore/Rewriters/RewriterCollection.cs, Source/DafnyCore/Rewriters/RewriterErrors.cs, Source/DafnyCore/Rewriters/RunAllTestsMainMethod.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/contract-wrappers/AllExterns.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/contract-wrappers/Inputs/CheckExtern.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/contract-wrappers/TestedExterns.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3839/git-issue-3839a.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3839/git-issue-3839a.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4998.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4998.dfy.expect, docs/dev/news/5068.fix
This PR fills in any type arguments `X` to the `result = F<X>(args)` postcondition that's generated for the method part of a `function-by-method` declaration.
Fixes #4998 
Reviewer notes: The desugaring of `function-by-method` is done in two places in the code. I filled in the type arguments in both places. However, in the second place (which is for `{:test}` functions/methods), `dafny` would crash if any type parameters were declared (even for type parameters that were not auto-init `(0)`). Since the `{:test}` was already not allowed for functions/methods with parameters, I also added error messages if `{:test}` is used with a function/method with type parameters. …
=> fix: Fill in type arguments in implicit function-by-method postcondition

CONTRIBUTING.md
As per the title, this PR just fixes links to `RELEASE_NOTES.md` and `Source` in `CONTRIBUTING.md`.
By clicking on the links in the preview.
----
=> docs: Fix links to `RELEASE_NOTES.md` and `Source` in `CONTRIBUTING.md`

Source/DafnyCore/DafnyCore.csproj, Source/DafnyCore/Options/CommonOptionBag.cs, Source/DafnyCore/Options/DafnyCommands.cs, Source/DafnyLanguageServer/DafnyLanguageServer.appsettings.json, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyLanguageServer/LanguageServer.cs
Add hidden options to configure logging severity and location for the language server, which help to debug language server issue
How to configure:
Output:
Manually
=> Add options to configure logging severity and location for IDE

Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/FunctionCallSubstituter.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4982.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4982.dfy.expect, docs/dev/news/5087.fix
=> fix: Termination override check for certain non-reference trait implementations

Source/DafnyLanguageServer.Test/Lookup/HoverVerificationTest.cs, Source/DafnyLanguageServer/Handlers/DafnyHoverHandler.cs
This is a fix for the broken "assertion batch" anchor -- an example use of it is below:
The anchor was originally `#sec-verification-attributes-on-assert-statements` which currently doesn't exist. The closest existing anchor appears to be [`#sec-verification-attributes-on-assertions`](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-verification-attributes-on-assertions) but I think linking to the section for the anchor [`#sec-assertion-batches`](https://dafny.org/dafny/DafnyRef/DafnyRef#sec-assertion-batches) is better since that section introduces the  _assertion batch_ concept.
I have not compiled the Dafny VSCode extension locally, but this PR changes tests and the CI should be green.
----
<small>By submitting this pull request, I confirm that my contribution is made under the terms of …
=> Fix "assertion batch" anchor

docs/DafnyRef/README.md
This PR fixes a typo and a couple of repetitions in `docs/DafnyRef/README.md`. The changes were done using the GitHub pencil, which probably added a newline at the end.
Eyeballing the preview.
----
=> Fix some typos in `docs/DafnyRef/README.md`

Source/DafnyStandardLibraries/CONTRIBUTING.md, docs/DafnyRef/UserGuide.md
This PR changes the "best known defense against brittleness" anchor in `Source/DafnyStandardLibraries/CONTRIBUTING.md` so that it points to the (only) Reference Manual section that discusses brittleness. Since that section's current anchor ([`#1376-debugging-brittle-verification`](https://dafny.org/dafny/DafnyRef/DafnyRef#1376-debugging-brittle-verification)) has the section number in it, this PR also removes the number from the anchor to make it less brittle (in the general sense of the word).
I ran a jekyll server using the instructions in `docs/DafnyRef/README.md` and the anchor changes as expected. If I'm not mistaken, a CI task will update the online docs.
---- …
=> docs: Link to the _brittle_ section

Source/DafnyCore/Compilers/CSharp/Compiler-Csharp.cs, Source/DafnyCore/Compilers/Cplusplus/Compiler-cpp.cs, Source/DafnyCore/Compilers/Dafny/Compiler-dafny.cs, Source/DafnyCore/Compilers/GoLang/Compiler-go.cs, Source/DafnyCore/Compilers/Java/Compiler-java.cs, Source/DafnyCore/Compilers/JavaScript/Compiler-js.cs, Source/DafnyCore/Compilers/Python/Compiler-python.cs, Source/DafnyCore/Compilers/SinglePassCompiler.cs
This PR renames a virtual method in the compiler. The change was suggested in the (now abandoned and closed) PR https://github.com/dafny-lang/dafny/pull/5053.
Note, the PR does not rename other occurrences of "rune". In particular, .NET has a class `System.Text.Rune` and the Dafny runtime (therefore?) has a class named `Rune` (and inside it, a method `IsRune`). These have not been renamed.
=> chore: Rename EmitIsRuneTest to EmitIsUnicodeScalarValueTest

docs/toc.md
Dafny documentation site page https://dafny.org/latest/toc includes a polyfill from `polyfill.io` for MathJax. The PR replaces `polyfill.io` with `cdnjs.cloudflare.com/polyfill`.
---
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.
[The original creator of the `polyfill.io` has voiced his concern on …
=> docs: remove `polyfill.io` in the toc page

Source/DafnyCore/DooFile.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/separate-verification/app.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/separate-verification/app.dfy.expect
Fixes #5143.
Added this case to `separate-verification/app.dfy`.
`separate-verification/assumptions.dfy` SHOULD have caught this regression, but unfortunately the command that triggers the exception uses `!` to expect a non-zero exit code, and LIT test commands usually only redirect stdout to a file to diff against the expected output, so the extra stderr output with the exception trace is lost.
=> fix: Avoid NPE when building a doo file with —no-verify

Source/DafnyCore/Options/CommonOptionBag.cs
The feature is quite stable now and the warning is no longer necessary.
Fixes #5164.
Manually
=> chore: Remove warning on --type-system-refresh

Source/DafnyCore/AST/Attributes.cs, Source/DafnyCore/Triggers/SplitPartTriggerWriter.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/triggers/emptyTrigger.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/triggers/emptyTrigger.dfy.expect
Fixes #5167
- Let an empty `{:trigger}` attribute have the same meaning as `{:autotriggers false}`, instead of causing a Boogie crash
Alternatively, we could let Dafny throw an error on an empty `{:trigger}` attribute, and update the documentation so that it tells you to either use `{:autotriggers false}` or `{:trigger <trigger>}`
- Added a littish test
=> Do not crash Boogie when an empty {:trigger} attribute occurs

Source/DafnyCore/Dafny.atg
RangeToken is not set for ParensExpression in https://github.com/dafny-lang/dafny/blob/99ad60af5b23ad83b2e49768cb32c8d2599cd60d/Source/DafnyCore/Dafny.atg#L3648 and it is assumed that it is going to be set in ParensExpression definition itself. However, RangeToken is not set in ParensExpression and this PR fixes it.
Let me know if it is required to add a test for this. I couldn't find a similar test on RangeTokens to replicate.
=> set RangeToken for ParensExpression

Source/DafnyDriver/TextVerificationLogger.cs
In previous Dafny releases, `--log-format text` would report overall times with fractions of a second. Recent changes led to that including only whole seconds. This restores the previous behavior.
Existing tests.
=> Restore fractional seconds in text logger

Source/DafnyCore/Backends/DatatypeWrapperEraser.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ErasableTypeWrappers.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ErasableTypeWrappers.dfy.expect, docs/dev/news/5234.fix
This PR makes two changes to when the "erase datatype wrapper" optimization is engaged.
* The optimization is disabled if the datatype implements any traits. (Previously, the optimization was still allowed under this condition, which had caused malformed code, see issue #5233.)
* Allow the optimization in the presence of ghost fields. (Previously, the optimization was disabled if the datatype contained _any_ fields. But ghost fields pose no problems for compilation.)
Fixes #5233
The tests (including the test case from the bug report) were added to `comp/ErasableTypeWrappers.dfy`.
=> fix: Optimize datatype wrappers only in the absence of trait parents

Source/IntegrationTests/TestFiles/LitTests/LitTest/server/counterexample_commandline.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/server/counterexample_commandline.dfy.expect
Remove paths in test that were causing the Windows build to fail
Test is changed
=> Remove paths in test that were causing the Windows build to fail

Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-2026.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-2026.dfy.expect
This file was missing from https://github.com/dafny-lang/dafny/pull/5266/files
=> Fix deep tests path missing

CONTRIBUTING.md
I fixed an outdated URL in the documentation on how to fix nightly tests.
=> Chore: Fixed broken URL

Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs, Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs
Provide more information when waiting for notification times out, which will help debug unstable tests
Change to testing
=> Provide more information when waiting for notification times out

.github/workflows/xunit-tests-reusable.yml
This PR changes how the language server unit tests execute, retrying them up to three times if they fail. Ultimately, this is what we're doing by hand, anyway, so we might as well automate it.
The proper solution to this problem is to ensure that the language server tests don't spuriously fail, but this will accelerate our development process in the meantime.
By running CI normally.
=> Retry LSP tests in case of error

Source/DafnyLanguageServer.Test/Performance/LargeFilesTest.cs, Source/DafnyLanguageServer.Test/Performance/ThreadUsageTest.cs, Source/DafnyLanguageServer.Test/Various/ConcurrentInteractionsTest.cs
- Add more logging to QuickEditsInLargeFile and two other unstable tests
- Fix the retry mechanic for `NoExtraThreadAfterEachChange`, which probably resolves all flakiness in this test.
Test logging change, no additional tests needed
=> Add more logging to QuickEditsInLargeFile

Source/DafnyDriver/Commands/VerifyCommand.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3855.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3855.dfy.expect
Fixes https://github.com/dafny-lang/dafny/issues/5389
- Fix bug in reporting of time taken when a verification timeout occurs
- Make test 3855 stable by redacting the time taken
- Fix is not tested
- Flaky test is updated
=> Timeout reporting

Source/DafnyCore/Pipeline/Compilation.cs, Source/DafnyLanguageServer.Test/Lookup/DocumentSymbolTest.cs, Source/DafnyLanguageServer.Test/ProjectFiles/CompetingProjectFilesTest.cs, Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs
This PR attempts to help debug flaky tests: https://github.com/dafny-lang/dafny/issues/5420, https://github.com/dafny-lang/dafny/issues/5443, https://github.com/dafny-lang/dafny/issues/5436
- Improve logging for `Compilation`
- Turn on more logging for `ProjectFileDoesNotOwnAllSourceFilesItUses`
Not
=> Turn on more logging for `ProjectFileDoesNotOwnAllSourceFilesItUses`

Source/DafnyCore/Backends/Python/PythonCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5469.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5469.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5469.dfy.rs.check, docs/dev/news/5476.fix
=> fix: Apply name mangling to datatype names in Python more often

.github/workflows/integration-tests-reusable.yml, .github/workflows/publish-release-reusable.yml, .github/workflows/release-brew.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml
This reverts PR https://github.com/dafny-lang/dafny/pull/5493 since it breaks nightly.
=> Revert "ci: Use macos-11 in all CI (#5493)"

Source/DafnyCore/AST/Grammar/ProgramParser.cs
Helps with diagnosing https://github.com/dafny-lang/dafny/issues/5460
=> Include stacktrace in parser internal error message

docs/dafny.sty
Add "const", "export" and "expect" to the LaTeX keyword list. These are present in the KDE syntax definition, but missing from the LaTeX keyword list.
This is a documentation-only change.
=> Add `const`, `export` and `expect` to LaTeX keyword list

.github/workflows/integration-tests-reusable.yml, .github/workflows/publish-release-reusable.yml, .github/workflows/release-brew.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml
- Use macos-13 instead of 14 (latest)
Not needed
=> Use Macos13 instead of 14

Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs, Source/DafnyCore/Verifier/ProofObligationDescription.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/proof-obligation-desc/calc-step.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/proof-obligation-desc/calc-step.dfy.expect
Implement `GetAssertedExpr` for `CalculationStep`.
With the new test `proof-obligation-desc/calc-step.dfy`.
=> Implement `GetAssertedExpr` for `CalculationStep`

Source/DafnyCore/AST/Members/Function.cs, Source/DafnyCore/AST/Members/Method.cs, Source/DafnyCore/AST/Members/MethodOrFunction.cs, Source/DafnyCore/Generic/Node.cs, Source/DafnyLanguageServer.Test/CodeActions/CodeActionsTest.cs
Fixes #5355
- Fix null reference exception that occurred when looking at the tokens of a generated node
- Add LSP test
=> Fix null ref in covered tokens

.github/workflows/nightly-build-reusable.yml
We have observed that the Rust compiler fails randomly. To not disrupt the workflow of the nightly release, and as the Rust compiler is still under active development, it does not make sense to include it as part of the nightly.
=> Chore: Omit Rust from the nightly release workflow

.github/workflows/integration-tests-reusable.yml, .github/workflows/nightly-build-reusable.yml
Ensure the nightly won't run the Rust code.
This time, we run the deep tests to ensure everything works as expected.
=> Ensure nightly skips Rust (fixed)

Source/DafnyCore/DafnyFile.cs, Source/DafnyCore/Options/BoogieOptionBag.cs, Source/DafnyCore/Options/DafnyCommands.cs, Source/DafnyCore/Options/DafnyProject.cs, Source/DafnyCore/Options/ProjectFileOpener.cs, Source/DafnyDriver/Commands/ResolveCommand.cs, Source/DafnyDriver/Commands/ServerCommand.cs, Source/DafnyDriver/Commands/VerifyCommand.cs, Source/DafnyDriver/DafnyNewCli.cs, Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs, Source/DafnyLanguageServer.Test/ProjectFiles/ProjectFilesTest.cs, Source/DafnyLanguageServer/LanguageServer.cs, Source/DafnyLanguageServer/Workspace/CachingProjectFileOpener.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/projectFile/projectFile.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/projectFile/projectFile.dfy.expect
- Add `--find-project` option, which allows selecting a project file by traversing up from a certain path. This is useful when working in a particular file and wanting to to a Dafny CLI call that uses the project for that file.
- Extended the existing CLI test `projectFile.dfy`
=> Add --find-project option

Source/IntegrationTests/TestFiles/LitTests/LitTest/metatests/InconsistentCompilerBehavior.dfy.testdafny.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/metatests/TestBeyondVerifierExpect.dfy.testdafny.expect, Source/TestDafny/MultiBackendTest.cs
Until the Rust code generator is finished, we shouldn't block everyone else's work by requiring .rs.check files or even update them every time, since the process is manual and very lengthy
This does not remove the execution of the Rust compiler, only remove the check, so that we still have some kind of coverage. Also, we display non-blocking error messages.
However, this might kill the meta-tests, I'll see how to fix that.
=> Chore: Internal backends should not fail CI

Source/DafnyLanguageServer.Test/Synchronization/CachingTest.cs
Fixes https://github.com/dafny-lang/dafny/issues/5515
Attempt to stabilize ConcurrentCompilationDoesNotBreakCaching test
Test change
=> Attempt to stabilize ConcurrentCompilationDoesNotBreakCaching test

Scripts/prepare_release.py, docs/dev/RELEASE.md
* Document the need to update `.doo` files on each version change.
* Add a `set-next-version` action to `prepare_release.py` and document when and how to use it.
I've manually run the `set-next-version` action locally and confirmed that it updated `Directory.Build.props` appropriately.
=> Update release process

Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs
On Windows, paths were not properly escaped when printing tokens.
We need to ensure deep tests work before merging this PR.
=> Fix Nightly: CsharpCodeGenerator.cs

Source/DafnyCore/TestGenerationOptions.cs, Source/DafnyDriver/Commands/GenerateTestsCommand.cs, Source/DafnyTestGeneration.Test/Setup.cs, Source/DafnyTestGeneration/FirstPass.cs
Introduces a `ignore-warnings` flag to `dafny generate-tests`. 
This is a temporary workaround for https://github.com/dafny-lang/dafny/issues/5607. Run below `nat.dfy` with `dafny generate-tests InlinedBlock nat.dfy --ignore-warnings=true`
```
module M {
method {:testEntry} plus_one(n: nat)
{
}
}
```
=> --ignore-warnings flag for test generation

Source/DafnyCore/AST/Statements/Assignment/AssignStmt.cs, Source/DafnyCore/Rewriters/RunAllTestsMainMethod.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5637.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5637.dfy.expect, docs/dev/news/5638.fix
=> fix: Crash when compiling an empty source file while including testing code

Source/DafnyCore/Backends/Java/JavaCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/separate-compilation/Inputs/producer/timesTwo.dfy, docs/dev/news/5655.fix
- Fix NRE that would occur when using --legacy-data-constructors
- Update existing test to add test-case
=> Fix NRE and add test

Source/DafnyCore/Backends/Java/JavaCodeGenerator.cs, Source/DafnyCore/ConcreteSyntax/ConcreteSyntaxTree.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/separate-compilation/Inputs/producer/timesTwo.dfy
- Fix bad generated Java code when using --legacy-data-constructors
- Updated existing test
=> Fix bad generated Java code when using --legacy-data-constructors

Source/DafnyCore/DafnyCore.csproj, Source/DafnyCore/Options/DafnyCommands.cs, Source/DafnyCore/Options/DeveloperOptionBag.cs, Source/DafnyDriver/Commands/MeasureComplexityCommand.cs, Source/DafnyLanguageServer/LanguageServer.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/measure-complexity.dfy, customBoogie.patch
Add developer options --sprint and --pprint, which are useful for debugging verification at the split level
These options map to Boogie options that are tested at the Boogie level
=> Add developer options --sprint and --pprint

Source/DafnyCore/Resolver/ModuleResolver.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/ForbidNondeterminismResolve.dfy
After #5632, Dafny started complaining about traits lacking constructors (which they can't have) when `--enforce-determinism` was enabled. This changes back to the previous behavior of warning only about classes without constructors.
Updated `dafny0/ForbidNondeterminismResolve.dfy` to include a trait declaration.
=> Don't complain about determinism for traits

.github/workflows/compfuzzci_fuzz.yaml
I have modified the fuzzing workflow to handle PR from forks. Fuzzing will only be triggered on PR created by verified contributors to prevent potential security risks.
**ALL WILL BE FUZZED** mwahaha
This change also fix the following annoying issues:
- Reporting bugs already caught by CI: Fuzzing will now be delayed and only run if all CI checks have passed. This is implemented outside of the workflow, the PR will not be blocked.
- Reporting non-bugs in Rust: Added pattern matching to ignore error that comes from not yet implemented features in Dafny-to-Rust. (sorry Mikael!)
Tested on my own dummy repo
=> Fuzzing on forks

Source/DafnyLanguageServer.Test/Diagnostics/DiagnosticsTest.cs
Fixes #5753
I ensures the flaky test does not test for a single diagnostic but for two, and if there are two the two should be timeouts.
No tests can be performed on a flaky test but at least it looks like it should prevent the issue since that issue was diagnosed.
=> Chore: Fixed non-deterministic with only one assumed timeout instead of two

Source/DafnyCore.Test/WriterFromOutputHelper.cs
Fixes #5723, likely fixes #5713 and fixes #5759
The CI fails every other run because of some unknown "there is no currently active test"
Based on this discussion:
https://github.com/xunit/xunit/issues/2146
it seems we should try/catch writing to the output channel, which this PR implements
The CI should not fail on this PR, and if needed, we can increase assurance that this PR solves the problem correctly.
To ensure the catching code is not deleted, the comment mentions the issue it is fixing.
=> Chore: Fix 'no active test'

Makefile, Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafny/DCOMP.cs, Source/DafnyRuntime/DafnyRuntimeRust/Cargo.lock
Follow-up of https://github.com/dafny-lang/dafny/pull/5786 with two changes
=> Chore: Rust refactorings followup

Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, Source/DafnyRuntime/DafnyRuntimeRust/src/tests/mod.rs
This PR makes it possible to wrap Rust's native string in `Object<>` while printing will print them correctly. I added a test in DafnyRuntimeRust
This PR might break external code which created `Object<>` of things that Dafny did not support originally, but I'm not aware of any other external code that was making use of that. Moreover, there is a workaround by creating the appropriate `Upcast` trait.
=> Chore: Printing of Object<string> will now display the string.

Source/DafnyCore/Backends/Dafny/AST.dfy, Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs, Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafny/DAST.cs, Source/DafnyCore/GeneratedFromDafny/DCOMP.cs, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, Source/DafnyRuntime/DafnyRuntimeRust/src/tests/mod.rs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/loops.dfy
Fixes #5802
Multiset iteration was implemented in the runtime but not imported to the Dafny-to-Rust code generator. Moreover, it did not iterate elements with multiplicity, which might be needed.
This PR adds support for multiset bounded pools so that multisets can be used in quantifiers and comprehensions.
A test in the runtime verifies the multiplicity, and I updated an existing test to test the enumeration in quantifiers and comprehensions.
=> Fix: Ability to enumerate multisets in the Dafny-to-Rust code generator

Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/SubsetTypes.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/SubsetTypes.dfy.expect
Currently nightly is failing: https://github.com/dafny-lang/dafny/actions/runs/11237776009/job/31265011469
- Increase rounding to let SubsetTypes test pass on OSX.
- The change is to let a test pass
=> Increase rounding to let SubsetTypes test pass on OSX

Source/DafnyCore/Backends/GoLang/GoCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ExternCtors-externs/Class.java, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ExternCtors-externs/Library.go, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ExternCtors-externs/Library.py, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ExternCtors.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/ExternCtors.dfy.expect
The Go backend was not passing arguments when invoking an `{:extern}` constructor.
Enabled Go in the existing `ExternCtors.dfy` test case, and refactored it to not require support for classes with both Dafny- and extern-implemented declarations (which is a separate feature).
=> fix: Include arguments to Go external constructor

Source/DafnyCore/Verifier/BoogieGenerator.BoogieFactory.cs, Source/DafnyCore/Verifier/BoogieGenerator.Decreases.cs, Source/DafnyCore/Verifier/BoogieGenerator.DefiniteAssignment.cs, Source/DafnyCore/Verifier/BoogieGenerator.ExpressionTranslator.cs, Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs, Source/DafnyCore/Verifier/BoogieGenerator.Extremes.cs, Source/DafnyCore/Verifier/BoogieGenerator.Fields.cs, Source/DafnyCore/Verifier/BoogieGenerator.Functions.Wellformedness.cs, Source/DafnyCore/Verifier/BoogieGenerator.Functions.cs, Source/DafnyCore/Verifier/BoogieGenerator.Iterators.cs, Source/DafnyCore/Verifier/BoogieGenerator.LetExpr.cs, Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/BoogieGenerator.Reveal.cs, Source/DafnyCore/Verifier/BoogieGenerator.SplitExpr.cs, Source/DafnyCore/Verifier/BoogieGenerator.Types.cs, Source/DafnyCore/Verifier/BoogieGenerator.cs, Source/DafnyCore/Verifier/Datatypes/BoogieGenerator.DataTypes.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrAssignment.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrCall.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrForallStmt.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrLoop.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrPredicateStatement.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrStatement.cs, Source/DafnyCore/Verifier/Statements/IfStatementVerifier.cs, Source/DafnyCore/Verifier/Statements/MatchVerifier.cs
- Extract match and if verification
Pure refactoring, no additional tests needed
=> Extract match and if verification

Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, Source/DafnyRuntime/DafnyRuntimeRust/src/tests/mod.rs
A previous update forced the `T` under `Object<T>` to implement `UpcastObject<dyn Any>` to be able to print it.
However, this trait was never implemented on objects. Arrays can be converted to objects but it's not possible to cast them down to arrays again, because arrays are traits in Rust (dynamic pointers).
Until we wrap arrays with a newtype to cast them back to a regular struct, we can fix the Dafny runtime so that they are still printed as "object"
Second, modify-field!() at the end of a block was triggering parsing issues. I added a block wrapper in the macro to prevent that issue.
Two tests added in the runtime.
<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE. …
=> Fix: Arrays can be printed and modify_field standalone

Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs
Fixes #5851
This PR adds the following safety checks
* If the strong count is not updated, we will panic instead of silently returning a Rc pointer that would cause dangling pointers if dropped. Adding these checks helped me reproduce the soundness issue all the time locally, but obviously did not fix it. I'm keeping it there just in case.
* Itmakes the strong count increment opaque to the compiler, so that it should prevent optimizations that would skip the strong count from increasing. It also makes it opaque at the call site. This did not prevent the compiler from optimizing it away unfortunately in at least one experiment, but I'll keep it just in case it's was another lurking issue.
* Added `#[inline(never)]` to the function from_ref did fix the soundness issue.
* I tried the …
=> Fix: Object::from_ref no longer forgetting to increment the strong count

Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/BoogieGenerator.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrStatement.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5136.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5136.dfy.expect, docs/dev/news/5876.fix
This PR fixes a soundness issue where, previously, type properties of `this` were assumed already in the first phase of `constructor`s. Now they are assumed at the time of the `new;`.
Fixes #5136
The details of the fix are as described in issue #5136.
=> fix: Don’t prematurely assume properties of “this” in constructors

Source/DafnyRuntime/DafnyRuntimePython/Makefile
This PR removes venv/bin so that executing python is straightforward on Windows.
I'm testing this script to release the DafnyRuntimePython 4.9.0 on Windows
=> Chore: Platform-agnostic python commands

Source/DafnyRuntime/DafnyRuntimePython/Makefile
Using a virtual environment avoids polluting the system Python installation.
Reverts dafny-lang/dafny#5880
=> chore: fix Python virtualenv commands on Windows

Source/DafnyCore/AST/TypeDeclarations/TypeSynonymDeclBase.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/reveal/revealInBlock.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/reveal/revealInBlock.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/reveal/revealInExpression.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/reveal/revealInExpression.dfy.expect, docs/dev/news/5882.fix
=> Fix reveal statement inside witness bug

Source/DafnyCore/Backends/Python/PythonCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5184/git-issue-5184.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-5184/git-issue-5184.dfy.expect
Fixes #5184
Tested with original test case in the issue.
=> Handle native string correctly with `SeqWithoutIsStrInference` for python code generation

Source/DafnyCore/AST/Grammar/ParseErrors.cs, Source/DafnyCore/AST/Grammar/ParserNonGeneratedPart.cs, Source/DafnyCore/AST/Grammar/Printer/Printer.Expression.cs, Source/DafnyCore/Dafny.atg, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo0.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo0.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo1.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo1.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo2.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo2.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo3.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo3.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo4.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo4.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo5.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/DecreasesTo5.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/PrettyPrinting.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/PrettyPrinting.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/proof-obligation-desc/trait-decreases.dfy.expect, docs/DafnyRef/Expressions.5.expect, docs/DafnyRef/Expressions.md, docs/dev/news/5891.feat
This PR expands the accepted `decreases to` (and `nonincreases to`) expressions. They now accept any number of left-hand sides and any number of right-hand sides (in particular, 0 LHSs and/or 0 RHSs). While the general form requires parentheses parentheses, this PR also allows a parenthesis-free form when there is exactly 1 LHS and exactly 1 RHS.
The PR also fixes pretty printing of `decreases to` expressions.
The PR also introduces errors for any `ghost` component among the arguments of `decreases to`.
=> Parse more general decreases-to expressions

Source/DafnyCore.Test/DafnyProjectTest.cs, Source/DafnyCore.Test/DooFileTest.cs, Source/DafnyCore/AST/Grammar/IFileSystem.cs, Source/DafnyCore/AST/Grammar/ProgramParser.cs, Source/DafnyCore/DafnyFile.cs, Source/DafnyCore/DafnyMain.cs, Source/DafnyCore/Options/DafnyProject.cs, Source/DafnyCore/Pipeline/Compilation.cs, Source/DafnyCore/Pipeline/Events/FinishedParsing.cs, Source/DafnyCore/Pipeline/IDafnyParser.cs, Source/DafnyCore/Pipeline/ITextDocumentLoader.cs, Source/DafnyCore/Pipeline/TextDocumentLoader.cs, Source/DafnyCore/Rewriters/InductionHeuristic.cs, Source/DafnyCore/Snippets.cs, Source/DafnyDriver/CliCompilation.cs, Source/DafnyDriver/Commands/FormatCommand.cs, Source/DafnyDriver/CoverageReporter.cs, Source/DafnyLanguageServer.Test/Unit/CompilationManagerTest.cs, Source/DafnyLanguageServer.Test/Util/DiagnosticsReceiver.cs, Source/DafnyLanguageServer.Test/Various/ExceptionTests.cs, Source/DafnyLanguageServer/Language/CachingParser.cs, Source/DafnyLanguageServer/Language/DafnyLangParser.cs, Source/DafnyLanguageServer/Workspace/IdeState.cs, Source/DafnyLanguageServer/Workspace/LanguageServerFilesystem.cs, Source/DafnyLanguageServer/Workspace/NotificationPublisher.cs, Source/DafnyLanguageServer/Workspace/ProjectManagerDatabase.cs, Source/DafnyPipeline.Test/FormatterBaseTest.cs, Source/DafnyPipeline.Test/ImplicitAssertionTest.cs, Source/DafnyServer/DafnyHelper.cs, Source/DafnyTestGeneration/Utils.cs
Fixes https://github.com/dafny-lang/dafny/issues/5901 and possibly other failing tests
- For any files open in the editor, record the editor's version number when that file is read, and store this version number throughout compilation so it can be used when emitting notifications for this compilation.
- The change in behavior only occurs for a particular race condition, which is difficult to trigger, so I have not added tests.
=> Fix concurrency bug in reported file version

Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafny/DCOMP.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/newtypes.dfy
Fixes #5923 completely, irrespective of the type of output variables.
The previous fix was only not redeclaring output variables when they were wrapped with `MaybePlacebo`, which is reserved for output variables that don't have a trivial initialization.
This fixes #5923 entirely by just ensuring we don't place output variables as part of the environment of recursive methods, since the `TailRecursive(...)` body already declares them
A new test added to `rust/newtypes.dfy`
=> Fix: Tail-recursion for result copy types in the Dafny-to-Rust backend.

Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafny/DCOMP.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/traits.dfy
Fixes #5992
When upcasting/downcasting, we often need a cloned reference. However, until recently, the references were cloned only if the call site required an owned referenced. Recently, references were borrowed and the borrow converted to a clone only if the ownership of the reference was necessary. However, this was implemented for Upcast, not downcast. Hence, if the same reference needed multiple downcasts, the generated Rust code would fail.
This PR fixes that by reusing the cloning code for upcasting but for downcasting as well.
Modified comp/rust/traits.dfy to account for two test cases that were failing for a user.
<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICEN …
=> Fix: Rust traits downcast now clone their arguments

.github/workflows/msbuild.yml, Makefile, Scripts/bump_version_number.js, Source/DafnyRuntime/DafnyRuntime.csproj, docs/dev/RELEASE.md, docs/dev/VERSIONBUMP.md
The release process stated at the end to increment the patch version for the next release, but also that the release number "may have changed" at the beginning when it "should have changed". Moreover, the instructions on how to update, doo files, dtr files, csproj files and others were missing.
* A description in `docs/dev/VERSIONBUMP.md` that explains how to do version bumping in Dafny
* An executable version of this description in `Scripts/bump_version_number.js`
* A link in the file `README.md` into this new file at the two positions where it can be useful.
* A test runnable via `make bumpversion-test` that will verify that
* The two files `docs/dev/VERSIONBUMP.md`  and  `Scripts/bump_version_number.js` are in sync, à la [Duvet.](https://github.com/awslabs/duvet)
* Unit tests for …
=> Chore: Executable Instructions to bump Dafny's version number

.github/workflows/nightly-build.yml
This PR sets the nightly releases to be taken from the release branch 4.9.1.
It keeps nightly builds on master though. After publishing 4.9.1 and merging it back
to master, we will revert this PR.
=> Chore: Set up nightly and prerelease for 4.9.1

.github/workflows/check-for-workflow-run.js, .github/workflows/nightly-build.yml
This reverts commit 041c925ba1533561651bd4c5238ba1e0d510f39a that seems to be the source of problems in the nightly.
=> Revert "Chore: Set up nightly and prerelease for 4.9.1 (#5995)"

Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/statement/opaqueBlock.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/statement/opaqueBlock.dfy.expect, docs/news/fix.6006
Fixes #6006
- Dafny now havocs the heap of an opaque block when it inherits a non-empty modifies clause from its parent
- Extended test-case
=> Fix opaque block soundness bug

.github/workflows/integration-tests-reusable.yml, Scripts/package.py, Source/DafnyDriver/Commands/ServerCommand.cs, Source/DafnyDriver/DafnyDriver.csproj, Source/DafnyDriver/Legacy/LegacyJsonVerificationLogger.cs, Source/DafnyLanguageServer/DafnyLanguageServer.csproj, Source/DafnyServer/DafnyServer.csproj, Source/DafnyTestGeneration/DafnyTestGeneration.csproj
- Remove the `<RuntimeIdentifier>$(RUNTIME_IDENTIFIER)</RuntimeIdentifier>` property from csproj files that was needed as a workaround but may break things in .NET 8 according to SO
- Remove references from DafnyDriver to DafnyServer, that prevented publishing correctly with .NET 8
- Stop publishing DafnyLanguageServer since it's not used directly.
Tested by existing tests
=> Attempt at fixing nightly.

Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3549a.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-3549a.dfy.expect
Should fix failing nightly: https://github.com/dafny-lang/dafny/actions/runs/12711494070/job/35434956978
The Dafny legacy CLI shows part of a .NET error message as part of it UI. This can not be tested well since the specific error message is not defined as part of .NET, and can be different across .NET versions and platforms.
On Windows it returns:
`Invalid filename: The value cannot be an empty string. (Parameter 'path')`
On other platforms it is:
`Invalid filename: The path is empty. (Parameter 'path')`
Instead of fixing the legacy CLI to remove the ambiguity, I'm removing the test for that ambiguous behavior since the old CLI is deprecated.
Removed a test …
=> Delete test for legacy CLI that tests ambiguous behavior

Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs
=> fix: remove deadlock from Sequence

Makefile, Source/DafnyCore/Backends/Rust/Dafny-compiler-rust-rast.dfy, Source/DafnyCore/Backends/Rust/Dafny-compiler-rust.dfy, Source/DafnyCore/GeneratedFromDafny/DCOMP.cs, Source/DafnyCore/GeneratedFromDafny/RAST.cs, Source/DafnyRuntime/DafnyRuntimeRust/src/system/mod.rs
The Rust formatter is usually _crashing_ on generated files on big codebases.
Since it's hard to pinpoint the cause of the crashing, instead, I change the default generation indentation to 4 spaces like Rust and deactivate formatting on generated files.
Existing tests should pass
=> Chore: No formatting of the generated Rust file but better indent

Source/DafnyCore/Backends/CSharp/CsharpCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6014.dfy
Fixes #6072 
I changed it so that the comparison between the module name and the class name is done on the C# string, not the Dafny string vs. C# string.
I added a check to ensure that in the generated C# code, the class named `A` is not escaped when using `--compile-suffix`
=> Fix: --compile-suffix avoids the extra renaming of homonymous classes

Source/DafnyCore/AST/TypeDeclarations/ArrayClassDecl.cs, Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrStatement.cs, Source/DafnyRuntime.Tests/CsRuntimeTest.cs
Small code improvements to address comments from https://github.com/dafny-lang/dafny/pull/6079
Pure refactoring
=> Small code improvements

Source/DafnyCore/AST/Modules/ModuleDefinition.cs, Source/DafnyLanguageServer.Test/Diagnostics/DiagnosticsTest.cs
Improve LSP diagnostics, so instead of
the IDE shows
For the errors:
`not resolving module '_module' because there were errors in resolving its nested module 'A'"`
`boolean literal used as if it had type int"`
- Added an LSP test
=> Fix angry module LSP diagnostic

Source/DafnyCore/Verifier/Statements/BoogieGenerator.TrCall.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6090.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6090.dfy.expect
=> fix: Add CanCall’s for default-valued parameters of method calls

.github/workflows/nightly-build.yml
This PR sets the nightly releases to be taken from the release branch 4.10.0.
It keeps nightly builds on master though. After publishing 4.10.0 and merging it back
to master, we will revert this PR.
=> Chore: Set up nightly and prerelease for 4.10.0

docs/Snapshots.md, docs/make-snapshot
New link for documentation snapshot as usual +
updated script so that it works on Windows
=> Documentation snapshot for v4.10.0

Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/defaultTimeLimit.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/defaultTimeLimit.dfy.expect
Fix instability in defaultTimeLimit test. Example failed run: https://github.com/dafny-lang/dafny/actions/runs/13332533239/job/37239919604?pr=5948
N/A
=> Fix instability in defaultTimeLimit test

Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/small/07-instantiated-methods.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/small/08-not-all-trait-items-implemented.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/small/10-type-parameter-equality.dfy
=> Disable failing rust tests for windows

Source/DafnyDriver/Legacy/SynchronousCliCompilation.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/projectFile/projectFile.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/projectFile/projectFile.dfy.expect, docs/dev/news/6107.fix
Fixes #6107
Correctly display project files errors when using build command
Updated existing CLI test
=> Correctly display project files errors when using build command

Source/DafnyCore/Resolver/ModuleResolver.cs, Source/DafnyCore/Resolver/PreType/UnderspecificationDetector.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6154a.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6154a.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6154b.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6154b.dfy.expect, docs/dev/news/6155.fix
Fix resolution crash of `>` for datatypes.
Fixes #6154
=> fix: Fix crash in resolution of structural-inclusion greater-than operator

Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/GeneralNewtypeVerify.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/GeneralNewtypeVerify.dfy.expect
Turn off test that was just added which fails on Windows
N/A
=> Turn off test that was just added which fails on Windows

Source/IntegrationTests/TestFiles/LitTests/LitTest/wishlist/git-issue-6158.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/wishlist/git-issue-6158.dfy.expect
Issue #6158 reports an unsoundness. The behavior seems to appear only with Z3 version 4.12.1 (which is what Dafny currently uses). Later versions of Z3 (I tried 4.12.4, 4.12.5, 4.13.0, 4.13.3, 4.13.4, and 4.14.1) do not exhibit the problem. This PR records the unsoundness example. The idea is to move the test from the `wishlist` folder to the `git-issues` folder once the problem has gone away (by some version change somewhere).
=> Record unsound example

Source/DafnyRuntime/DafnyRuntimeRust/Cargo.toml, Source/DafnyRuntime/DafnyRuntimeRust/src/lib.rs, Source/DafnyRuntime/DafnyRuntimeRust/src/tests/mod.rs
append_recursive is now tail recursive in the most common case
Tests added to ensure correctness.
explicit `println!`s are necessary to prove tail recursion.
=> chore: optimize Sequence::to_array()

.github/workflows/check-deep-tests-reusable.yml, .github/workflows/integration-tests-reusable.yml, .github/workflows/msbuild.yml, .github/workflows/publish-release-reusable.yml, .github/workflows/release-downloads-nuget.yml, .github/workflows/release-downloads.yml, .github/workflows/xunit-tests-reusable.yml
ubuntu-20.04 will be [fully unsupported](https://github.com/actions/runner-images/issues/11101) soon.
=> chore(ci): Replace ubuntu-20.04 with ubuntu-22.04 in all workflows

Source/DafnyCore/Verifier/BoogieGenerator.Functions.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/blogposts/TestGenerationWithInliningQuantifiedDefinitions.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6164.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6164.dfy.expect, docs/dev/news/6164.fix
Previously, Dafny generated axioms of the form
``` dafny
// alloc consequence axiom for _module.__default.On
axiom (forall $Heap: Heap, n#0: ref, f#0: int :: 
{ $IsAlloc(_module.__default.On(n#0, f#0), Tclass._module.Referrer(), $Heap) } 
_module.__default.On#canCall(n#0, f#0) && $IsGoodHeap($Heap)
==> $IsAlloc(_module.__default.On(n#0, f#0), Tclass._module.Referrer(), $Heap));
```
for any function whose result type may involve references. This is not sound, since it fails to connect the parameters with the `$Heap`.
The axiom would be sound if the `$Heap` parameter is part of the function and/or its CanCall predicate. In the situation discovered in #6164, the function (named `On`) does not have such a `$Heap` parameter. This PR makes sure that, in those cases, the axiom's antecedent will …
=> fix: Generate alloc consequence axiom only for functions that read the heap

Source/DafnyLanguageServer/DafnyLanguageServer.cs, docs/dev/news/6172.fix
Fixes https://github.com/dafny-lang/dafny/issues/6172. I ensured that two notification messages' parameters that are disregarded anyway in the VSCode extension use the proper LSP semantics of being wrapped with an array or being an object, so that the LSP is compatible with Helix for example. I tested locally that this change does not break the VSCode extension, not sure how to test it furthermore.
=> Chore: Fix compliancy of language server with LSP

.github/workflows/integration-tests-reusable.yml
[The last nightly build failed on windows](https://github.com/dafny-lang/dafny/actions/runs/14245722393/job/39937179775), and the main differences are a bump in the windows-2019 image version and the Rust platform version bumping from 1.85.1 to 1.86.0. Locking down to 1.85.1 to unblock development for now.
`run-deep-tests`
=> chore(ci): Lock down Rust 1.85.1 for now to fix nightly build on Windows

Source/DafnyCore/AST/Expressions/Applications/ActualBindings.cs, Source/DafnyCore/AST/Expressions/Conditional/Patterns/ExtendedPattern.cs, Source/DafnyCore/AST/Expressions/Datatypes/DatatypeValue.cs, Source/DafnyCore/AST/Expressions/Variables/CasePattern.cs, Source/DafnyCore/AST/Expressions/Variables/LetExpr.cs, Source/DafnyCore/AST/Expressions/Variables/LetOrFailExpr.cs, Source/DafnyCore/AST/SyntaxDeserializer/Generated.cs, Source/DafnyCore/AST/SyntaxDeserializer/HandWritten.cs, Source/DafnyCore/Rewriters/InductionHeuristic.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatControlFlow.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatControlFlow.dfy.expect, Source/Scripts/Syntax.cs-schema, Source/Scripts/SyntaxAstVisitor.cs, Source/Scripts/SyntaxDeserializerGenerator.cs, Source/Scripts/SyntaxSchemaGenerator.cs
- Add syntax schema types for `LetExpr`, `LetOrFailExpr`, `CasePattern`, `ExtendedPattern`, and `DatatypeValue`
- Denote `RedundantField`s in the generated syntax schema, so that consumers can avoid the need to provide bogus data
- Note: The representation of redundant fields is likely to change
- Added an integration test for the new syntax schema types
- Manually verified that the new types and `RedundantField` appear as expected in the re-generated syntax schema
=> feat: add schema types for let/let-or-fail and some patterns

Source/DafnyCore/AST/Expressions/Conditional/NestedMatchCase.cs, Source/DafnyCore/AST/Expressions/Conditional/NestedMatchCaseExpr.cs, Source/DafnyCore/AST/Expressions/Conditional/NestedMatchCaseStmt.cs, Source/DafnyCore/AST/Expressions/Conditional/NestedMatchExpr.cs, Source/DafnyCore/AST/Expressions/Conditional/NestedMatchStmt.cs, Source/DafnyCore/AST/Expressions/Conditional/Patterns/DisjunctivePattern.cs, Source/DafnyCore/AST/Expressions/Conditional/Patterns/IdPattern.cs, Source/DafnyCore/AST/Expressions/Conditional/Patterns/LitPattern.cs, Source/DafnyCore/AST/Expressions/LiteralExpr.cs, Source/DafnyCore/AST/Statements/Methods/PrintStmt.cs, Source/DafnyCore/AST/SyntaxDeserializer/Generated.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatControlFlow.dfy, Source/Scripts/Syntax.cs-schema
- Add syntax schema types for match/case: `NestedMatchCase`, `NestedMatchCaseExpr`, `NestedMatchCaseStmt`, `NestedMatchExpr`, `NestedMatchStmt`
- Add syntax schema types for patterns: `DisjunctivePattern`, `IdPattern`, `LitPattern`, `StringLiteralExpr`
- Add syntax schema type for `PrintStmt`
- Extended `inputFormatControlFlow.dfy` integration test to exercise new syntax schema types.
=> feat: add schema types for match/case, more patterns, print

Source/DafnyCore/Rewriters/BitvectorOptimization.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/conversions.dfy, docs/dev/news/6196.fix
Fixes #6196 
I updated the test to ensure it was breaking and that this PR fixes the test.
Basically, a test was testing if the type was a bitvector type, but this type was a synonym type with the new resolver so that needed to be updated.
=> Fix: Bitvector shift in `--type-system-refresh`

Source/DafnyCore/Backends/Dafny/DafnyCodeGenerator.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6212.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6212.dfy.expect
Fixes #6212 
Previously, multiset indexing to retrieve the multiplicity wasn't supported in the Dafny-to-Rust compiler, but it worked seamlessly for multisets of integers because the compiler was treating it silently as a `map<int, int>`.
Added proper support for multisets of any types.
Test added
=> Fix 6212 dafny to rust compilation issue with conversions

Source/DafnyCore/AST/Statements/OpaqueBlock.cs, Source/DafnyCore/Verifier/BoogieGenerator.ExpressionTranslator.cs, Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs, Source/DafnyCore/Verifier/Statements/OpaqueBlockVerifier.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/statement/opaqueBlock.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/ast/statement/opaqueBlock.dfy.expect, docs/news/6217.fix
Fixes #6217
- Let modifies clauses of opaque blocks use the heap before the block as 'old', instead of the one at the start of the method.
- Added a test case to opaqueBlock.dfy
=> Opaque modifies clause

Source/DafnyCore/Backends/Rust/Dafny-compiler-rust-rast.dfy, Source/DafnyCore/GeneratedFromDafny/RAST.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/operators.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/comp/rust/operators.dfy.expect
Fixes #6221 
This is not yet a user visible change since the Dafny-to-Rust compiler is still marked as internal.
Existing tests have been modified. They correctly reproduced the issue and this PR fixes them.
=> Fix: Operators rendering more robust in Rust

.github/workflows/nightly-build.yml
A previous workflow item for releasing Dafny is now crashing nightly builds. I'll revert it for now
=> Chore: revert nightly-build.yml

Source/DafnyCore/AST/Modules/DefaultClassDecl.cs, Source/DafnyCore/AST/Modules/ModuleDecl.cs, Source/DafnyCore/AST/Modules/ModuleDefinition.cs, Source/DafnyCore/AST/SyntaxDeserializer/Generated.cs, Source/DafnyCore/AST/SystemModuleManager.cs, Source/DafnyCore/AST/TypeDeclarations/ArrayClassDecl.cs, Source/DafnyCore/AST/TypeDeclarations/ClassDecl.cs, Source/DafnyCore/AST/TypeDeclarations/ClassLikeDecl.cs, Source/DafnyCore/AST/TypeDeclarations/IteratorDecl.cs, Source/DafnyCore/AST/TypeDeclarations/TopLevelDecl.cs, Source/DafnyCore/AST/TypeDeclarations/TopLevelDeclWithMembers.cs, Source/DafnyCore/AST/TypeDeclarations/ValuetypeDecl.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/cli/inputFormatDeleteSources.dfy, Source/Scripts/SourceToBinary.cs, Source/Scripts/Syntax.cs-schema, Source/Scripts/SyntaxAstVisitor.cs, Source/Scripts/SyntaxDeserializerGenerator.cs, Source/Scripts/SyntaxSchemaGenerator.cs
- Generate the schema and deserialization code, which produces a few changes because of existing changes in master (related to Function and Predicate), and a few changes coming from the above changes, related to the "traits" parameter.
- Process a few comments from https://github.com/dafny-lang/dafny/pull/6263f 
- Simplify serialization related generator code by no longer looking at fields and properties.
- Changes covered by existing tests
=> Syntax serialization simplification

Source/DafnyStandardLibraries/README.md
Fix a broken link in the README.md file for standard library.
Nothing to be tested
=> Fix broken link in Std Library README.md

Source/DafnyCore/AST/Expressions/LiteralExpr.cs, Source/DafnyCore/Resolver/PreType/PreTypeResolve.Expressions.cs, Source/DafnyStandardLibraries/src/Std/Parsers/Core/ParsersBuilders.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/TypeInferenceRefreshErrors.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/TypeInferenceRefreshErrors.dfy.expect, docs/dev/news/6273.fix
This PR fixes a crash where a string literal in the input was being passed to a string format method that interpreted the string as a format string. Characters like unmatched `{`'s in that string had then caused a crash when error messages were printed.
=> fix: Escape string literals in error messages

Source/DafnyCore/AST/Grammar/Printer/Printer.Expression.cs
Fixes a null reference exception when trying to print an unresolved `DatatypeValue`.
=> chore: fix printing unresolved datatype values

Source/DafnyCore/Dafny.atg
This PR removes two misplaced LL(1) resolvers that were flagged by Coco/R as unnecessary and fixes the resulting field location parsing issue.
Coco/R was generating warnings for two misplaced resolvers:
```
-- line 3767 col 8 : warning : Misplaced resolver: no LL(1) conflict.
-- line 4512 col 8 : warning : Misplaced resolver: no LL(1) conflict.
```
These resolvers don't actually resolve any parsing conflicts and add unnecessary complexity.
- `IF(AcceptReferrersAndBacktick())` in `ConstAtomExpression` (line 3767)
- `IF(IsIdentifier(la.kind))` in `FieldLocationSuffix` (line 4512)
Removing the resolvers required restructuring field location parsing to handle backtick consumption correctly:
- Replace resolver with direct backtick matching
- Create `FieldLocationBody` production to separate …
=> chore: Remove misplaced LL(1) resolvers and fix field location parsing

Source/DafnyCore/Resolver/PreType/Flows.cs, Source/DafnyCore/Verifier/BoogieGenerator.Types.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/AsIs-Verify.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/dafny0/AsIs-Verify.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6317a.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6317a.dfy.expect, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6317b.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6317b.dfy.expect, docs/dev/news/6321.fix
Fixes two problems/crashes in the new resolver.
Fixes #6317 
=> Fixes resolver crashes related to datatypes and traits

Source/DafnyCore/AST/Grammar/ParserNonGeneratedPart.cs, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6329.dfy, Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-6329.dfy.expect
Fixes #6329, which is a regression since the introduction of `--referrers`
**Changes:**
- Moved `_field` from conditional default case to explicit case in `IsType()` method
- Ensures consistent parsing regardless of `AcceptReferrers()` setting
**Testing:**
- Build successful, all tests pass + the extra one.
=> Fix field type parsing by moving _field case to explicit token list

Scripts/bump_version_number.js, docs/dev/VERSIONBUMP.md
During minor version patches, the current version bump process rebuilds standard libraries with the new version. However, when the build machine has a different version of Z3, the standard libraries sometimes timeout, making the build process non-deterministic.
This PR modifies the version bump script to update doo files without rebuilding them:
1. **For standard library doo files**: Instead of running `make -C Source/DafnyStandardLibraries update-binary`, the script now:
- Unzips each doo file (which are actually zip archives)
- Updates the `dafny_version` field in the `manifest.toml` file
- Rezips the file
2. **For test doo files**: Instead of rebuilding from source, the script updates the version in the existing doo files using the same approach.
- `Scripts/bump_version_number.js`: …
=> Update doo files without rebuilding to avoid Z3 timeout issues
